### ISSUE TITLE
Console name with spaces

### ISSUE THREAD

**Issue by piebaker** [streetpea/chiaki4deck#1]
Currently, if the console has spaces in its name, the automation script cannot detect this, and simply errors out:
`No Configuration found for 'FIRSTPARTOFCONSOLENAME'`
This can be fixed by putting double quotes around the console name in the script file itself. 
Would be great if this was detected and automated, or was integrated as a user option in the script setup

**Comment by streetpea** [comment]
Thanks for pointing that out, I saw the pattern mine was in and thought they all didn't have spaces. Should work now. Let me know if you have any issues.
