### ISSUE TITLE
[Feedback] Automation - /setup/automation/

### ISSUE THREAD

**Issue by plrguez** [streetpea/chiaki4deck#10]
Hi,

Kudos for the Chiaki updates to Deck and the excellent documentation.

But I think the [Automation section](https://streetpea.github.io/chiaki4deck/setup/automation/) can be improved adding an advice about the setting  "Enable turning On PS4 from Network" on the PS4. [How do I wake up my PS4 console and start using PS4 Remote Play?](https://www.sony.com/electronics/support/articles/SX365501)

I don't know for the PS5, but a similar setup probably exists.

**Comment by siler23** [comment]
You're right I should definitely add this to the documentation. Mine was just already set on so I didn't have to think about it (hence it didn't get added to the documentation). I will add this for the next release. Thanks for pointing this out.

**Comment by streetpea** [comment]
Thanks for pointing this out. I appreciate it. That is something I didn’t have to do so overlooked it. Additionally, yes there is an equivalent setting for PS5. I will definitely update the documentation to include this for the next release.

**Comment by streetpea** [comment]
I added your suggestion to the initial instructions (for first time setup) as well as to the testing your connection subsection in the configuration section https://streetpea.github.io/chiaki4deck/setup/configuration/

**Comment by plrguez** [comment]
> @plrguez I added your suggestion to the initial instructions (for first time setup) as well as to the testing your connection subsection in the configuration section https://streetpea.github.io/chiaki4deck/setup/configuration/

Thank you for your great work!
