### ISSUE TITLE
Bitrate and audio buffer - what do they do?

### ISSUE THREAD

**Issue by darrenhaken** [streetpea/chiaki4deck#100]
I’m trying to understand what the two parameters do but the documentation doesn’t say (or I can’t see it).

can you explain what they do? I notice in the docs you suggest higher values than the defaults.

I am having hunch that higher values (bitrate or audio buffer) are causing occasional streaming meltdowns - white screen, extreme lag etc. But it’s sporadic and hard to prove.

anyway, if you can help me understand the parameters more it would really help me.

**Comment by streetpea** [comment]
The audio buffer is how big of a buffer there is when processing audio (in this case on the Steam Deck). The bigger the buffer the less of a chance to have to drop audio (dropping audio causes breaks in the audio playback that generally come through as crackling sounds added to the audio). However, having too large a buffer can add to audio lag. I used an increased buffer to get rid of the choppiness I was experiencing with the audio. 

The bitrate has to do with the amount of information that is streamed per second. The basic gist of it is that the higher the bitrate the higher the quality of the content (less compression needed to fit the raw file into the amount of space [bits] you're giving it) at the cost of more bandwidth used on the connection. Having a bitrate too high for your connection can lead to an unstable connection. Having said that if you are using a 5GHz connection with local connection the bitrate you can use is dependent on only your wireless router and with my old router using 30 Mbps bitrate was using about 2% of the total bandwidth of the 5GHz lane of my router. I also noticed for my connection using a higher bitrate (still a small amount of my total bandwidth) actually resulted in a more stable connection. I'm not exactly sure why this is but my best guess is that my router is giving the connection some sort of higher precedence / Quality of Service (QoS) when using a higher bitrate which is resulting a more stable connection. 

I decided the values I used through suggestions and results of other users and testing them on my connection. Having said that, the values you should use are dependent on your connection and more specifically your router.
