### ISSUE TITLE
Control issue with Chiaki on my SD

### ISSUE THREAD

**Issue by TPrime411** [streetpea/chiaki4deck#101]
I installed Chiaki on my Steam Deck and got it connected to my PS5, but I'm having some control issues.

1) when I try it in desktop mode, I can connect, operate the menu, and load games. But once I'm in the game, only the A, B, X and Y buttons do anything. I can't move the character at all with the d pad or joysticks.

2) when I try it in Game mode it's worse. I get to the point where it shows my system, and all I can do is highlight it with the touch screen. I can't open it at all with buttons or triggers. They do absolutely nothing.

I mainly want to get it working in game mode, so I don't care so much about desktop mode. Any idea how to fix this issue?

**Comment by streetpea** [comment]
For desktop mode you need to set a different controller profile than the default which is meant for navigating menus/browsers but not for playing games. You can set this by going into Steam and going to your controller settings and setting your desktop mode controller setting to something else. However, given you don't really care about using it in desktop mode you don't need to do this (but this is what would fix your issue in desktop mode).

As for game mode if you are using chiaki4deck by just adding it to the game mode you will need to double tap the touchscreen to launch it (a game controller doesn't work with the menu). However, I would recommend you skip the menu entirely in game mode by using the automation and adding that as a non steam game as shown in the documentation (see https://streetpea.github.io/chiaki4deck/setup/automation/). Then, all you have to do is start chiaki4deck and it will automatically launch into remote play for you. Also, when you are in game mode try using the controller layout chiaki4deck+ mic by gmoney23 to get everything mapped to the Steam deck buttons.

**Comment by TPrime411** [comment]
That helped. Thanks a lot.
