### ISSUE TITLE
Black Screen issue

### ISSUE THREAD

**Issue by shadowglance08** [streetpea/chiaki4deck#102]
I set up everything 2 days ago and it was working fine, today I tried to use the app again and its giving me a black screen, tried tweaking settings but can't seem to be able to solve it. 

I can attach the log if that helps in any way. Would appreciate some advice!

**Comment by streetpea** [comment]
The log would be helpful.

**Comment by shadowglance08** [comment]
Appears that a hard reset of the console did fix the issue. Thank you for the reply though, appreciate it!
