### ISSUE TITLE
Microphone cutting out during play session

### ISSUE THREAD

**Issue by streetpea** [streetpea/chiaki4deck#106]

**Comment by johnhste** [comment]
just an update on this I have played a few times in the last few days no issues since I adjusted my wifi. i will continue to monitor

**Comment by johnhste** [comment]
I updated to the 1.5 version. the mute button now seems to work but it isn't indicated just no audio in the PS4 microphone test

**Comment by streetpea** [comment]
Hmm ... I don't do display anything when you hit the mute button. The PS5 displays a notification when you mute or unmute that is seen through remote play. I'm guessing the PS4 must not have this notification.

**Comment by SupurClay** [comment]
> just an update on this I have played a few times in the last few days no issues since I adjusted my wifi. i will continue to monitor

im currently running through the exact issue with the mic cutting out during my gameplay in party chat. when you say you adjusted your wifi, what did you do and did it fix the mic issue? thanks!

**Comment by johnhste** [comment]
I have my steam deck on it's own wifi ssid.
that seems to have made it a lot more stable. I have had only a few instances where it stopped.
a close and reconnect of chiaki fixes it.
one thing I have observed is that before it cuts out the quality of the  connection drops.

**Comment by SupurClay** [comment]
I see, So my connection is actually really good.(Running PS5 hardwired and running chiaki settings on all default) It feels like there is some sort of a disconnect with the chiaki app and steamdeck. I tried a bunch of settings in the chiaki audio settings but no avail. Also trying different steamOS updates. So far tried stable 3.5.7  and beta builds but no luck..

**Comment by streetpea** [comment]
fixed with 1.6.3
