### ISSUE TITLE
Are there any documentation or parameters to explain the vulkan rendering options “quality，balance，fast” quantitatively?

### ISSUE THREAD

**Issue by GJQ-FUN** [streetpea/chiaki4deck#110]
I have updated the new version 1.5 of chiaki4deck, the renderer change to Vulkan.  I find that the power difference between the three render options is quite large,(10 watts with "quality" , 8 watts with "balance" and 7 watts with "fast", The quality option usually takes up more GPU) .but my eyes can't quite see the difference. Out of curiosity, I want to know the parameters behind these three options.

**Comment by streetpea** [comment]
From the libplacebo documentation (https://libplacebo.org/options/):

```
    default: Default settings, tuned to provide a balance of performance and quality. Should be fine on almost all systems.
    fast: Disable all advanced rendering, equivalent to passing no to every option. Increases performance on very slow / old integrated GPUs.
    high_quality: Reset all structs to their high_quality presets (where available), set the upscaler to ewa_lanczossharp, and enable deband=yes. Suitable for use on machines with a discrete GPU.
```
I also noticed that I get an estimated 8 hours with low quality preset and about 6 hours with high preset on the Steam Deck OLED and since 6 hours is still plenty for my use case I keep it on the high preset

**Comment by GJQ-FUN** [comment]
> From the libplacebo documentation (https://libplacebo.org/options/):
> 
> > default: Default settings, tuned to provide a balance of performance and quality. Should be fine on almost all systems.
> > fast: Disable all advanced rendering, equivalent to passing no to every option. Increases performance on very slow / old integrated GPUs.
> > high_quality: Reset all structs to their high_quality presets (where available), set the upscaler to ewa_lanczossharp, and enable deband=yes. Suitable for use on machines with a discrete GPU.
> 
> ```
> I also noticed that I get an estimated 8 hours with low quality preset and about 6 hours with high preset on the Steam Deck OLED and since 6 hours is still plenty for my use case I keep it on the high preset
> ```


> From the libplacebo documentation (https://libplacebo.org/options/):
> 
> > default: Default settings, tuned to provide a balance of performance and quality. Should be fine on almost all systems.
> > fast: Disable all advanced rendering, equivalent to passing no to every option. Increases performance on very slow / old integrated GPUs.
> > high_quality: Reset all structs to their high_quality presets (where available), set the upscaler to ewa_lanczossharp, and enable deband=yes. Suitable for use on machines with a discrete GPU.
> 
> ```
> I also noticed that I get an estimated 8 hours with low quality preset and about 6 hours with high preset on the Steam Deck OLED and since 6 hours is still plenty for my use case I keep it on the high preset
> ``T

> From the libplacebo documentation (https://libplacebo.org/options/):
> 
> > default: Default settings, tuned to provide a balance of performance and quality. Should be fine on almost all systems.
> > fast: Disable all advanced rendering, equivalent to passing no to every option. Increases performance on very slow / old integrated GPUs.
> > high_quality: Reset all structs to their high_quality presets (where available), set the upscaler to ewa_lanczossharp, and enable deband=yes. Suitable for use on machines with a discrete GPU.
> 
> ```
> I also noticed that I get an estimated 8 hours with low quality preset and about 6 hours with high preset on the Steam Deck OLED and since 6 hours is still plenty for my use case I keep it on the high preset
> ```

Thanks, it's really detailed. My deck is LCD version, so some options of high quality maybe will not work, and consider of its small battery ,maybe default or fast is more suitable.

**Comment by GJQ-FUN** [comment]
> From the libplacebo documentation (https://libplacebo.org/options/):
> 
> > default: Default settings, tuned to provide a balance of performance and quality. Should be fine on almost all systems.
> > fast: Disable all advanced rendering, equivalent to passing no to every option. Increases performance on very slow / old integrated GPUs.
> > high_quality: Reset all structs to their high_quality presets (where available), set the upscaler to ewa_lanczossharp, and enable deband=yes. Suitable for use on machines with a discrete GPU.
> 
> ```
> I also noticed that I get an estimated 8 hours with low quality preset and about 6 hours with high preset on the Steam Deck OLED and since 6 hours is still plenty for my use case I keep it on the high preset
> ```

Thanks, it's really detailed. My deck is LCD version, so some options of high quality maybe will not work, and consider of its small battery ,maybe default or fast is more suitable.
