### ISSUE TITLE
Crashing at launch

### ISSUE THREAD

**Issue by fer-lo** [streetpea/chiaki4deck#112]
Hi everyone! I tried to install chiaki4deck today and it's crashing on launch.
This happens when trying to run it from the desktop or through konsole, and both installing it using discovery and using flatpack.

When I try to run it through konsole I get this error:

> F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Can it be related to me having Chiaki installed on my steamdeck?

**Comment by streetpea** [comment]
That's weird. If you try
```
flatpak run --env=QT_PLUGIN_PATH=/usr/lib/plugins io.github.streetpea.Chiaki4deck
```
does it work?

If that doesn't work can you post the output of this:
```
flatpak run --env=QT_DEBUG_PLUGINS=1 io.github.streetpea.Chiaki4deck
```

**Comment by 17451k** [comment]
I have the same error and crush with Retroarch. After reboot the issue goes away, but then it returns again.

**Comment by streetpea** [comment]
Can you try
```
flatpak override --show
```
and 
```
flatpak override --show io.github.streetpea.Chiaki4deck
```
@17451k are you getting this issue with Chiaki4deck or just with retroarch?

If just with retroarch can you try
```
flatpak override --show org.libretro.RetroArch
```

**Comment by fer-lo** [comment]
This is the output of the previous line you gave me:

> QFactoryLoader::QFactoryLoader() checking directory path "/usr/share/runtime/lib/plugins/platforms" ...
> QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/plugins/platforms" ...
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqeglfs.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqeglfs.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "eglfs"
>         ]
>     },
>     "archreq": 0,
>     "className": "QEglFSIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("eglfs")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqminimal.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqminimal.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "minimal"
>         ]
>     },
>     "archreq": 0,
>     "className": "QMinimalIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("minimal")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqminimalegl.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqminimalegl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "minimalegl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QMinimalEglIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("minimalegl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqoffscreen.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqoffscreen.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "offscreen"
>         ]
>     },
>     "archreq": 0,
>     "className": "QOffscreenIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("offscreen")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqvnc.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqvnc.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "vnc"
>         ]
>     },
>     "archreq": 0,
>     "className": "QVncIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("vnc")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqwayland-egl.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqwayland-egl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland-egl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandEglPlatformIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("wayland-egl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqwayland-generic.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqwayland-generic.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("wayland")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqwayland-xcomposite-egl.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqwayland-xcomposite-egl.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland-xcomposite-egl"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandXCompositeEglPlatformIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("wayland-xcomposite-egl")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqwayland-xcomposite-glx.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqwayland-xcomposite-glx.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "wayland-xcomposite-glx"
>         ]
>     },
>     "archreq": 0,
>     "className": "QWaylandXCompositeGlxPlatformIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("wayland-xcomposite-glx")
> QFactoryLoader::QFactoryLoader() looking at "/usr/lib/plugins/platforms/libqxcb.so"
> Found metadata in lib /usr/lib/plugins/platforms/libqxcb.so, metadata=
> {
>     "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
>     "MetaData": {
>         "Keys": [
>             "xcb"
>         ]
>     },
>     "archreq": 0,
>     "className": "QXcbIntegrationPlugin",
>     "debug": false,
>     "version": 331520
> }
> 
> 
> Got keys from plugin meta data ("xcb")
> QFactoryLoader::QFactoryLoader() checking directory path "/app/bin/platforms" ...
> loaded library "/usr/lib/plugins/platforms/libqxcb.so"
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

I then tried the two lines from your latest message and it didn't seem to do anything.

Should I uninstall it and try again from scratch? Not sure how to uninstall the flatpack installed version.

**Comment by 17451k** [comment]
> @17451k are you getting this issue with Chiaki4deck or just with retroarch?
> 
> If just with retroarch can you try
> 
> ```
> flatpak override --show org.libretro.RetroArch
> ```

My issue is only with Retroarch, I don't use Chiaki4deck yet. This issue thread was the only one that I was able to find through Google with the similar description to what I experience, so I though maybe it has the same cause. 

You command doesn't help and outputs nothing to the screen. However, I think I finally managed to reliably reproduce my issue: it always happens after using Valve's "Nested Desktop" app from the gaming mode. It can be fixed by rebooting and then never using this app again :)

Thanks for the help and fast responses, and sorry that I wasted your time 😓

**Comment by streetpea** [comment]
@fer-lo can you try the following and see if it fixes the error when you re-launch chiaki4deck in the konsole
```
sudo flatpak override --nosocket=fallback-x11 --socket=x11 io.github.streetpea.Chiaki4deck
```

**Comment by fer-lo** [comment]
@streetpea that seems to have worked! I was able to launch it both from the Konsole and from gaming mode after that override (I had previously added it to Steam, not sure if I should remove it and add it again just in case or if there's no need).

Thanks a lot for your help, I'll use it for longer to test it more but I just tried it for a few minutes and it's running great.

**Comment by streetpea** [comment]
@fer-lo that override is a one time thing that makes it so that any way the flatpak is launched it uses the new setting so there is no name to change the non-steam game you created before.
