### ISSUE TITLE
TouchPad swipe action registering as both button press and swipe

### ISSUE THREAD

**Issue by bloodmc** [streetpea/chiaki4deck#118]
Device: ROG Ally Z1 Extreme
OS: Windows 11 22H2
Chiaki build: latest windows release
1080P, 60FPS, 30000 bitrate

Testing Astro's Playroom with 'Controller Demo' in 'TOUCH PAD' screen, swipe shows up as a press along with swipe. Swipe seems to register properly as the animation appears correctly on screen but doesn't work as expected due to a simulated press always appearing in top left corner of touch pad. This causes the action to always register as a press instead of a swipe in games such as Ghost of Tsushima. Where is the simulated press handled so I can debug on my side?

Note: I have TouchPad button mapped to the 'T' keyboard button so it should not be associated to on-screen swipes.

Thanks!

**Comment by streetpea** [comment]
The outer 5% edges of the screen register as touchpad press. If your swipe includes the outer 5% edges of the screen it will be a touchpad press. Otherwise it will just be a touchpad swipe.

**Comment by bloodmc** [comment]
This issue occurs anywhere I press on screen using ROG Ally touchpad.

**Comment by streetpea** [comment]
So right-click and middle-click register as touchpad click (left-click doesn't) ... do you have right-click mapped to a touchpad press?

**Comment by streetpea** [comment]
The Steam Deck touch screen uses touch events when its set to touchscreen only. Is there a touchscreen only mode for the ROG ally?

**Comment by bloodmc** [comment]
Not sure what you mean. ROG Ally has ‘Control Mode’ that lets you choose between keyboard and gamepad mode. I always have it set to ‘Gamepad Mode’ but touchscreen always works in both modes.

As far as mouse touch translation, I have this enabled with touch events disabled and it works perfectly. The reason why touch events do not work is due to my comment above where both x and y always return 0 in HandleTouchEvent causing click to always get triggered. I would just let mouse events handle ROG Ally touch screen as it seems to work perfectly. I’m able to swipe up, down, left, and tight in Ghost of Tsushima without any issues.

**Comment by bloodmc** [comment]
Just tested latest builds and I'm no longer having input issues. I'll close this ticket as it seems to be resolved!
