### ISSUE TITLE
non-local network connection getting error

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#120]
Hi, I use chiaki on my ally and windeck. Just started using chiaki4deck and I've noticed it has issues when connecting from other networks. It will give an error message saying "chiaki session has quit. Unknown ctrl Error." 

I quite literally never have this error or issue when using chiaki on windows. I am hoping you could look into this and possibly figure out why it's doing this.

I have run a few different test myself. 

One of the test I have done is used my phones mobile Hotspot. It successfully wakes the PS5 no problem. Once I go to connect it will give that error message. If I wait a few minutes and try to connect again it will finally connect while using my Hotspot. This confirms for me that my port forwarding is working just fine and that this should be fine to do. 

I can only theorize what is happening is it connects to the PS5 the first time then kicks the person out but the PS5 still thinks someone is connected when they are not, which makes the person have to wait a few minutes before finally being able to connect.

**Comment by OatBehave** [comment]
This is also happening to me too, exact same setup.

**Comment by iTsMute** [comment]
Tested some more.  I am able to connect from other networks just fine.  Seems to be an issue with mobile Hotspots which is a new one for me but understandable. I'll close this ticket.
