### ISSUE TITLE
Remote connection using PSN

### ISSUE THREAD

**Issue by streetpea** [streetpea/chiaki4deck#123]
Connect remotely over psn as an alternative to port forwarding

PSN wake-up example here: https://github.com/grill2010/PlayStationSharp

**Comment by streamingdv** [comment]
I'm in contact with @jbaiter about this feature ;)

**Comment by jbaiter** [comment]
Yup, I'm working on it, but it might be a while, it will require changes in many parts of the codebase, including some API changes. And there are a few other things I might do before it.

And thanks for the invaluable help @streamingdv 🙏
