### ISSUE TITLE
[Feedback] Home - / ps3 support

### ISSUE THREAD

**Issue by JD69Han** [streetpea/chiaki4deck#124]
Please add PlayStation 3 support 🙏🏻🙏🏻🙏🏻

**Comment by streamingdv** [comment]
PS3 only supports Remote Play for a very limited number of games and the protocol is very different. Due to the limited remote play functionality for PS3 and the difference in how it works, I guess this is a bit out of scope for chiaki4deck.

**Comment by JD69Han** [comment]
Interesting, so when it comes to the ps3 would having a CFW installed make any difference for the remote play compatibility or would it still be extremely limited?

**Comment by streetpea** [comment]
closing as out of scope

**Comment by Twig6943** [comment]
Running the ps3 app inside wine might work https://www.youtube.com/watch?v=LvVuWB15po4

Somebody please test & post results to this issue
