### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by davidjirovec** [streetpea/chiaki4deck#126]
Any plans on MacOS version? Original Chiaki supports it.

**Comment by streetpea** [comment]
added see latest release

**Comment by dnestico** [comment]
I just downloaded it and it will not open. Im on MacOS Sonoma 14.0.

<img width="351" alt="Screenshot 2024-01-15 at 9 32 05 PM" src="https://github.com/streetpea/chiaki4deck/assets/3034555/1d7b599e-a76b-45e8-88c4-09072219c116">

**Comment by streetpea** [comment]
Can you try downloading the newly uploaded dmg?

**Comment by dnestico** [comment]
Ayy it opens! Nice UI btw, need to get this on my new OLED asap, just waiting for windows drivers cuz I wanna do it on windows tbh.

<img width="1298" alt="Screenshot 2024-01-15 at 10 43 50 PM" src="https://github.com/streetpea/chiaki4deck/assets/3034555/f48cce2d-3c08-439d-b04a-3c6343c3f9d5">

**Comment by austinarchibald** [comment]
Any plans for an iOS or iPad build? Would love to sideload this onto the Vision Pro in 2 weeks! Thanks again for all your work on this project. I use chiaki4deck on 3 different OSes now, and it's fantastic.
