### ISSUE TITLE
 Error after connecting to ps5

### ISSUE THREAD

**Issue by rlagksmf12** [streetpea/chiaki4deck#128]
Error after connecting to ps5
chiaki session has quiet: unknown error in stream connection

[chiaki_session_2023-12-19_03-36-31-069069.log](https://github.com/streetpea/chiaki4deck/files/13707480/chiaki_session_2023-12-19_03-36-31-069069.log)

**Comment by OatBehave** [comment]
I am also getting this problem after fresh installing and following the guide twice. 

(This is when trying to play away from home)

If launch chiaki4deck it sends the wake-up packet and turns my PS5 on but then the session times out, if I then launch chiaki4deck again it boots into the ps5 homescreen. It's annoying, but it's the only way I can play outside my home address. i'm not sure if this is a bug or something that i've done incorrect during the setup?

**Comment by streetpea** [comment]
This was fixed by 809fdbbef7df5d285f0a76e427e042f8d3ea82a1
