### ISSUE TITLE
Updating view mode after initially running the script

### ISSUE THREAD

**Issue by apharrison964** [streetpea/chiaki4deck#132]
Hi, I don’t know if I just missed it (I looked all over the website) but how do you update the view mode after initially setting up the automation script? I reran it but it didn’t ask me to set the options again.  Sorry if I just missed it!

**Comment by streetpea** [comment]
You can either edit the file /home/deck/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki-launcher.sh and change the current option on the last line of that file (I.e., zoom, stretch or fullscreen) to your desired option or re-run bash <(curl -sLo- https://raw.githubusercontent.com/streetpea/chiaki4deck/main/scripts/gen-launcher.sh)
And recreate the script entirely with your new desired option.

**Comment by apharrison964** [comment]
Great! Thank you - I edited the file and it worked!
