### ISSUE TITLE
Not rumble/hapatics on rog ally

### ISSUE THREAD

**Issue by tovarich86** [streetpea/chiaki4deck#133]
Chiaki4dsck is buttery smooth and clear, but I can't get any rumble/haptics from my  rogally, the chiaki isn't smooth at all but has rumble/haptics

**Comment by streetpea** [comment]
@tovarich86 are you testing chiaki vs chiaki4deck rumble on the same game? I'm asking because PS5 games don't support rumble just haptic feedback which requires either a DualSense controller or a Steam Deck and for the experimental PS5 features to be checked on.

**Comment by tovarich86** [comment]
Yes i was right now playing calisto (ps5) protocol, with chiaki4deck the quality is way better but no haptic .   chiaki the quality is worse,  but has a really strong haptic. Sorry for my bad English

**Comment by streetpea** [comment]
Do you have an attached dualsense controller?

**Comment by streetpea** [comment]
If not I would think haptics wouldn't work for chiaki or chiaki4deck for that game.

**Comment by tovarich86** [comment]
No playing direct from Ally

**Comment by tovarich86** [comment]
Now I see I'm using a fork from the main chaiki, the version that i'm using has this features
Adaptive Triggers (Bluetooth and USB)
Haptic rumble (only USB, may not work)
Emulated haptic rumble (works with USB and Bluetooth)
Built with QT6
Improved colorimetry.

**Comment by streetpea** [comment]
So that has an emulated haptic rumble that isn't in chiaki4deck
