### ISSUE TITLE
V1.5.1 DualSense Haptics and touchpad don’t work

### ISSUE THREAD

**Issue by Nitrob0y** [streetpea/chiaki4deck#134]
Hello I connected my DualSense to my steam deck and everything works besides these two issues

1. Haptics does not work, it rumbles on the steam deck **instead** of the DualSense controller

2. Touchpad button (need it to access Spider-Man menu)

Also I cannot see any Community Controller Layouts anymore even with the default name “chiaki4deck”, but I was able to see it on v1.5.0, is it because 1.5.1 is not an official release/build?

**Comment by streetpea** [comment]
Do you have Steam input disabled for your dualsense controller?

The community layouts is controlled by Steam not the individual app. Not sure why you don't see any community layouts for the non-Steam game.

**Comment by Nitrob0y** [comment]
Sorry what do you mean by steam input disabled for my DualSense?


Also I just tried using chiaki4deck in steam desktop mode and the controller haptics and touchpad is working as intended (but no HDR this way)

**Comment by streetpea** [comment]
See https://streetpea.github.io/chiaki4deck/setup/controlling/#enabling-chiaki4deck-to-work-with-dualsense-dualshock-4, specifically the tab that says Turning off Steam Input (recommended)

**Comment by Nitrob0y** [comment]
That worked!, thanks for the help and quick response!
