### ISSUE TITLE
Double inputs when using an 8bitdo Ultimate Controller via USB

### ISSUE THREAD

**Issue by mattinm** [streetpea/chiaki4deck#139]
I’m using an 8BitDo ultimate controller via USB in 2.4GHz (Xbox) mode with my Steam Deck docked to my TV. When pressing the “Guide” button on the controller, it acts like the PS Button in Chiaki and the Steam button in the Deck interface. While navigating the Deck interface, it also navigates the Chiaki stream.

I believe Chiaki is taking the inputs of the controller directly and not the Steam Input version of the controller. I can further confirm this by changing the face buttons around in the Steam Controller Configuration for Chiaki, but it’s not actually changing them in the app.

I’m not sure if other controllers are effected by this. Native Steam game are not effected. The Guide button brings up the Steam interface as expected and does not send inputs into the game while the Steam interface is open.

**Comment by mattinm** [comment]
Doing a cursory look through the code, this appears to be expected behavior (mostly). What I’m curious about is why Steam Input isn't hiding the raw inputs from SDL2; SteamAPI docs seem to suggest that’s what should happen with SDL >= 2.0.8.

**Comment by nowrep** [comment]
Does this happen in desktop mode? I think it will only ignore the emulated controller if launched from Steam.

**Comment by mattinm** [comment]
This is happening from Game Mode on the Steam Deck using the launcher script to launch Chiaki4Deck per the documentation.

**Comment by nowrep** [comment]
`SDL_GAMECONTROLLER_IGNORE_DEVICES` is the env variable, you may want to check if it's set correctly.

**Comment by mattinm** [comment]
It appears this is an 8BitDo ultimate issue, as Xbox controller via Bluetooth does not have this issue.
