### ISSUE TITLE
Lost Dualsense haptic with latest version

### ISSUE THREAD

**Issue by LordDunlow** [streetpea/chiaki4deck#141]
I recently noticed that after updating to 1.5.0 I lost Dualsense haptic when connected via USB. It was working flawlessly before that.

I verified that Steam Input was disabled.

I also noticed that when it worked before, the controller behaved as if directly connected to the PS5 displaying the single led indicator. (I have Steam settings set to change LED bar to green and no indicator - so previous versions I had green when in Steam menus, but when connected to Chiaki4deck, it changed to blue LED bar and first controller indicator - it no longer does this and remains green.)

This could also be a Steam Deck issue as previous behavior was separate for USB vs BT.  When connected via BT it would allow Steam input enabled and different controller settings than when connected via USB (i.e. Steam input off). It behaved like two separate controllers. Now changes made on one connection type persist when changing the other type.

**Comment by bloodmc** [comment]
Turn on chiaki debugging and upload logs with current version and last version (when it worked).

**Comment by jbaiter** [comment]
Can confirm the issue with a DualSense connected via USB to my laptop, so it's probably not due to any changes in SteamOS, SteamInput or the Deck firmware.
I'll investigate, let's hope Sony didn't change something in the DualSense firmware 🙈

**Comment by streetpea** [comment]
fixed in 1.6.2
