### ISSUE TITLE
Fullscreen on Fedora causes visual problems

### ISSUE THREAD

**Issue by kaibagley** [streetpea/chiaki4deck#142]
OS: Fedora Workstation 39
Chiaki: 2.1.1
Chiaki4deck: 1.5.1

Hey guys, 

I might not be the target audience here, but normal Chiaki doesn't work with H265 for me, and I thought I'd test this version out.

Everything works fine, however when I try and fullscreen (F11), the screen shows the following:

![image](https://github.com/streetpea/chiaki4deck/assets/53884957/8e545291-68e9-4069-97e0-de5a4e59b399)

I can safely F11 again to go back to windowed, and everthing will be normal

**Comment by baranovskis** [comment]
> OS: Fedora Workstation 39 Chiaki: 2.1.1 Chiaki4deck: 1.5.1
> 
> Hey guys,
> 
> I might not be the target audience here, but normal Chiaki doesn't work with H265 for me, and I thought I'd test this version out.
> 
> Everything works fine, however when I try and fullscreen (F11), the screen shows the following:
> 
> ![image](https://private-user-images.githubusercontent.com/53884957/293544696-8e545291-68e9-4069-97e0-de5a4e59b399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTI4NjUsIm5iZiI6MTcwNDIxMjU2NSwicGF0aCI6Ii81Mzg4NDk1Ny8yOTM1NDQ2OTYtOGU1NDUyOTEtNjhlOS00MDY5LTk3ZTAtZGU1YTRlNTliMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE2MjI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZWM2MGRiYjYxMDRmYzEzYTI5MTdiYTY0YjAwMzQ4MmZjMmExZDExNGFjOWM3MDZhY2Y2NzQ4MGEzZWEwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b39i7tuVn-Z5Ca4RuY_Ew1qoB4qWTY4aenHe-Qn0B88)
> 
> I can safely F11 again to go back to windowed, and everthing will be normal

I had a similar issue and solved it with full screen launcher (see https://streetpea.github.io/chiaki4deck/setup/automation/)

**Comment by streetpea** [comment]
1. Nothing in the script itself controls that. Maybe check your display settings or switch the image to a different monitor (its shift+super+arrow on some distros) 
2. Whichever codec you choose in settings is the one it will use

**Comment by kaibagley** [comment]
Just switched to Hyprland recently, on Fedora still, and I can fullscreen without visual bugs. Not sure if it was some other package I installed in the process though...

**Comment by streetpea** [comment]
Closing as it seems you resolved your issue. You can also select to launch into fullscreen via the settings without needing to use a script.
