### ISSUE TITLE
No audio when using on Windows

### ISSUE THREAD

**Issue by Jremdog** [streetpea/chiaki4deck#143]
Hi guys, 

long time user on Steam Deck but also wanted to use on my desktop. The screen streams just fine but I get no audio at all and I've checked all options and tried to troubleshoot online but cant find many people using this on Windows.

Any idea why this might be?

Thanks in advance and thanks for all your hard work.

**Comment by bloodmc** [comment]
I can confirm this issue occurs when chiaki is configured for `Auto` sound device in settings. If `Auto` picks up a device not currently connected (airpods etc..) then the user will experience no audio. 

Bug is on this line 
https://github.com/streetpea/chiaki4deck/blob/main/gui/src/streamsession.cpp#L726

As per SDL docs https://wiki.libsdl.org/SDL2/SDL_OpenAudioDevice, the passed in device name should be a first attempt then you should always fallback to the default output device if not successful. The current code does not fallback by passing `nullptr` for name.

In my test case, chiaki picked up unconnected airpods which I even removed from windows settings. Not too familiar with chiaki codebase but there is probably a bug with the auto sound detection on windows at least? A disconnected bluetooth audio device should never be chosen.

@Jremdog as a workaround, simply configure the chiaki audio output to one of your audio devices in list that you want to use.

Checking git history, it looks like this bug was introduced from @nowrep 's SDL PR so it would be best for him to chime in. Would be nice to also include the actual audio device name that could not be opened instead of just an SDL error.

**Comment by nowrep** [comment]
That's a bug in widgets settings dialog, the auto device should be saved as empty string in settings instead of `"Auto"`.

**Comment by nowrep** [comment]
If you select `Auto` it should save empty string and it will try to open default device (`nullptr`).

**Comment by Jremdog** [comment]
Hi @bloodmc , thanks for the help.

I tried this but no success, the no audio issue remains - ![image](https://github.com/streetpea/chiaki4deck/assets/71636267/1122a87b-0bef-42c6-88eb-ca16d536a519)

I had a look at the audio settings on the PS5 and it still indicates that the audio is being output device as 'HDMI Device (AV Amplifier) which is the same as playing normally on the console via my TV - 
![image](https://github.com/streetpea/chiaki4deck/assets/71636267/6af6f433-ea3c-4eab-891f-9ce718bd4d9a)

However, the microphone however shows input device as 'Microphone on Remote Play'  

Not sure if this might have something to do with it.

**Comment by bloodmc** [comment]
> If you select `Auto` it should save empty string and it will try to open default device (`nullptr`).

On my debug build, I had `Auto` selected and it still attempted to open my disconnected airpods. The name passed was `AirPods Pro`. How about if the first attempt fails then retry with the default device if the audio device name was not empty? This solves the issue on my end.

**Comment by bloodmc** [comment]
> Hi @bloodmc , thanks for the help.
> 
> I tried this but no success, the no audio issue remains - ![image](https://private-user-images.githubusercontent.com/71636267/294512216-1122a87b-0bef-42c6-88eb-ca16d536a519.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Njc4MjksIm5iZiI6MTcwNDQ2NzUyOSwicGF0aCI6Ii83MTYzNjI2Ny8yOTQ1MTIyMTYtMTEyMmE4N2ItMGJlZi00MmM2LTg4ZWItY2ExNmQ1MzZhNTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE1MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZWM1NDUyYTgyMzA1ODcxNjdlYmZjMWJjNDNhODE3NjgxOThlYjdiYTYwZGZkY2I4NjdjNDE3ODdiNjVmMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VcXy7C5_0YRVbgNQhxu8C2czKgU2AiJpCBbCA4Mw6aQ)
> 
> I had a look at the audio settings on the PS5 and it still indicates that the audio is being output device as 'HDMI Device (AV Amplifier) which is the same as playing normally on the console via my TV - ![image](https://private-user-images.githubusercontent.com/71636267/294512460-6af6f433-ea3c-4eab-891f-9ce718bd4d9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Njc4MjksIm5iZiI6MTcwNDQ2NzUyOSwicGF0aCI6Ii83MTYzNjI2Ny8yOTQ1MTI0NjAtNmFmNmY0MzMtZWEzYy00ZWFiLTg5MWYtOWNlNzE4YmQ0ZDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE1MTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczN2JkN2I0MTQyYTgxMTE2MDBlZDJiMmQxNGZhZTk4ODYyOTI5OWVmNmIxMzc1NTI1NjcxODVlZjE3YjRjNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0toICFWXvqL0wQNZfpbuLXhQ_tqI0uHM7THfhi4msuQ)
> 
> However, the microphone shows input device as 'Microphone on Remote Play'
> 
> Not sure if this might have something to do with it.

Just to confirm, what build are you using? As you are still having issues, the only other thing you can do is wait until they add more debugging so we can confirm if it is selecting the proper audio device or add the fallback as I suggested.

**Comment by Sildurs-shaders** [comment]
Looking at the commit history these changes are not live yet yeah? Running into the same issue on Windows 11, no audio whatsoever, using the latest realtek drivers with a DT 990 Pro.

**Comment by Johnnydana** [comment]
> Looking at the commit history these changes are not live yet yeah? Running into the same issue on Windows 11, no audio whatsoever, using the latest realtek drivers with a DT 990 Pro. Also the 1.5 release has the zip file name Chiaki4deck-win_x64-VC-1.4.1, inside another zip.
> 
> EDIT: The lack of audio is caused by setting my audio device higher than the windows default of 24bit 48000hz. Anything other than that causes this and it can be fixed by using the qtaudio_windows library but that introduced a lot of crackling noises. Not sure if this is worth opening a new issue for.

I don't understand how this is still an issue, but my chiaki defaulted to QT audio and would be crackle hell, then when I removed it whole thing was muted because of what you said, your post helped me fix it. Had terrible audio delay but set the buffer in the 4000 and it fixed it.
