### ISSUE TITLE
Nothing happens after running install command

### ISSUE THREAD

**Issue by kremlinjanitor** [streetpea/chiaki4deck#17]
I've have been trying for the past few days to install chiaki4deck but every time i run the install command Konsole just seems to hang or gives a 401 error
![image](https://user-images.githubusercontent.com/42277961/197594499-70cbba24-7994-4f4e-ade2-251ab1370a56.png)

**Comment by streetpea** [comment]
Hi, do you have internet access from you Steam Deck? Right now it’s saying you can’t reach the page. If I put this url into my web browser it works fine https://github.com/streetpea/chiaki4deck/releases/download/v1.2.0/re.chiaki.Chiaki4deck.flatpakref. Can you try that url on your Steam Deck in a browser?

**Comment by kremlinjanitor** [comment]
Doesn't seem like that link is want to load at all. I know the wifi connection I'm on is perfectly fine since I'm using AnyDesk to remote into the Deck.

**Comment by kremlinjanitor** [comment]
Yep link is working fine on my desktop.

**Comment by streetpea** [comment]
Ok yeah so that’s why it’s not working on your Steam Deck (for some reason it isn’t able to get to  the github release page). Can you try just visiting github on your Steam Deck?

**Comment by kremlinjanitor** [comment]
Seems to timeout for that as well. Just as a test i opened up steam and the store page loads just fine. Something to do with Firefox maybe? Kind of at a loss as to what could be causing this.

**Comment by streetpea** [comment]
Hmm so it seems like a general issue with internet access to GitHub on your deck and not related to the flatpak install specifically. Can you try a different website and see if that works (to rule out GitHub blocking you for some reason?)

**Comment by kremlinjanitor** [comment]
Oh wow so the github homepage just now loaded. So that's a full 7 minutes roughly to load that webpage.
Also looks like just trying to load google is going to take the same amount of time.

**Comment by streetpea** [comment]
I had this same issue a while back after a steam deck update and it was a dns thing. Can you look at your system logs and tell me if you see dns timeouts? The command is: journalctl (you can use shift + G to get to the end of the logs to see the most recent messages)

**Comment by kremlinjanitor** [comment]
Seems like there's some _Failed to send hostname_ errors in there
![image](https://user-images.githubusercontent.com/42277961/197600827-bcfcdb27-161a-421a-ba80-f4323b9f4a81.png)

**Comment by kremlinjanitor** [comment]
After changing the DNS settings for the IPV4 to use 8.8.8.8 that seems to have fixed the page loading issues. I can now reach the projects Github page with no issues. ill try running the install command again to see if it still has problems.

**Comment by streetpea** [comment]
Ok, yea that’s what fixed the dns issue for me a few months ago.

**Comment by kremlinjanitor** [comment]
the install command still doesn't seems to be doing anything from what i can tell. Its been sitting like this for the past few minutes.

![image](https://user-images.githubusercontent.com/42277961/197602591-01e2c6b5-428d-42f7-bb1f-2360bc56ce1b.png)

**Comment by kremlinjanitor** [comment]
More hostname reply errors 
![image](https://user-images.githubusercontent.com/42277961/197603179-2aa95728-0e2c-4b8f-abed-4526165d5a85.png)

**Comment by streetpea** [comment]
It’s possible the change you made didn’t get picked up by the konsole yet. You might need to restart your Steam Deck for that if you haven’t already.

**Comment by kremlinjanitor** [comment]
Alrighty seems the reboot helped it, finally have some progress on a download.
![image](https://user-images.githubusercontent.com/42277961/197603993-50e001fa-d869-49d8-b630-143733fe9438.png)
Thanks so much for the help!

**Comment by streetpea** [comment]
Awesome! Since this was just a general Steam Deck wifi issue there isn’t anything to do on my end so I’ll close this issue. Having said that, if you have any other questions, issues or feature requests/feedback lmk.
