### ISSUE TITLE
Discover on SteamDeck offers to downgrade 1.5.0 to 1.4.1

### ISSUE THREAD

**Issue by outcoldman** [streetpea/chiaki4deck#173]
Curious, is there a reason why on SteamDeck Discover Chiaki4deck suggests to downgrade from 1.5.0 to 1.4.1? I believe it has been showing it like a few days after 1.5.0 has been released. 

![IMG_4285](https://github.com/streetpea/chiaki4deck/assets/597158/64317b66-94cd-4030-99fd-29ca7b60d05d)

**Comment by streetpea** [comment]
It shows 1.5.1 as the latest version on my Steam Deck. When you run `flatpak upgrade` in the konsole what does it say?

**Comment by outcoldman** [comment]
I feel like the issue can be that Whats New is not updated, and it shows 1.4.1 as last released notes. Maybe this is a reason why it shows like a downgrade to 1.4.1? Anyway, excited to see 1.6.0 soon!

**Comment by lcorsini** [comment]
I tried today to update from discover and got a "refresh to 1.5.1" so it seems that flathub is doing something but 1.6 is still not available

**Comment by streetpea** [comment]
1.6.1 is the latest version on Flathub now https://flathub.org/apps/io.github.streetpea.Chiaki4deck
