### ISSUE TITLE
1.6 not available on discover store

### ISSUE THREAD

**Issue by Jaredmf** [streetpea/chiaki4deck#176]
checked with both konsole and the store gui - any idea why I can't update?

![ksnip_20240115-223324](https://github.com/streetpea/chiaki4deck/assets/10677813/16e0cdbf-02ba-49c6-a764-a1a0e31989f0)
![ksnip_20240115-223404](https://github.com/streetpea/chiaki4deck/assets/10677813/6daa5ace-f06c-498d-ba49-27afc71b5d87)

**Comment by chanksworld** [comment]
I second this.. might take a while to update i guess?

**Comment by nabel0** [comment]
same here

**Comment by streetpea** [comment]
It's not released yet on discover store it takes time to go through the release process.

**Comment by nabel0** [comment]
> It's not released yet on discover store it takes time to go through the release process.

Is there an easy way to migrate from the flatpack to the appimage version on the steamdeck

**Comment by nabel0** [comment]
> > Is there an easy way to migrate from the flatpack to the appimage version on the steamdeck?
> 
> Download the appimage version, run chmod +x on your downloaded appimage and run it. Update your shortcuts to point to the file path of the appimage instead of flatpak run io.github.streetpea.Chiaki4deck

But with this way it wont pick up my flatpack configuration (Chiaki-launcher.sh and Chiaki.conf). Where are thos files stored for the appimage?

**Comment by streetpea** [comment]
The flatpak should be updated now...If you still want to use the appimage you can copy the settings file with `cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf to ~/.config/Chiaki/Chiaki.conf` and replace flatpak run io.github.streetpea.Chiaki4deck with your appimage location in Chiaki-launcher.sh

**Comment by geenaxion** [comment]
![20240117_030011](https://github.com/streetpea/chiaki4deck/assets/10777018/e705e318-8cdc-4f1c-b71a-4593d17e4fa5)


1.6 is not showing up on mine but 1.4.1
Currently using 1.5.1

**Comment by geenaxion** [comment]
Nevermind. I used the konsole command flatpak update and mine is already updated to 1.6
Thanks!
