### ISSUE TITLE
Windows v1.6 - No Fullscreen

### ISSUE THREAD

**Issue by Malnoth** [streetpea/chiaki4deck#178]
Windows v1.6:

When the stream is started, there does not appear to be a way to enter true full screen. 
After clicking the 'maximize' button in the navbar, the window expands, but the top bar remains (minimize, full screen, close buttons).
In version 1.5 I was able to double click anywhere in the window and it would go to true full screen. This does not appear to be the case in 1.6. Likewise, 'Alt+Enter' does not enter full screen either.

**Comment by nowrep** [comment]
F11 for fullscreen.

**Comment by Malnoth** [comment]
Thanks,

F11 doesn't work for me, but ctrl+F11 does enter full screen.
I'm using Windows 11 if that makes a difference.
