### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by datnodude** [streetpea/chiaki4deck#18]
I'm having difficulty getting my SD connected to my ps5. I'm using an erro 6+ router. I've tried toggling my ps5 from lan to WiFi and vice versa. The SD is on the same network and said but it won't find my ps5. I was able to register it once but it can't find it afterwards. I've tried turning of upnp on the router, tried forcing both devices to use 5ghz signal, nothin seems to work. any ideas? thanks

**Comment by streetpea** [comment]
Are remote play and the other necessary settings on in your ps5 settings? You can find these in the new to using chiaki4deck tab in [this section](https://streetpea.github.io/chiaki4deck/setup/configuration/#registering-your-playstation)?

**Comment by streetpea** [comment]
If so, it probably has to do with either your wireless connection (there are usually settings for discovering wired devices on the router from the given wireless network as well as letting devices communicate / blocking specific devices.) or router settings or (less likely but possible) network settings for the given connection on your Deck (perhaps you choose a setting that doesn’t allow connection with other local devices / didn’t select the network as a home network).

**Comment by datnodude** [comment]
> Are remote play and the other necessary settings on in your ps5 settings? You can find these in the new to using chiaki4deck tab in [this section](https://streetpea.github.io/chiaki4deck/setup/configuration/#registering-your-playstation)?

ps5 settings are fine. I can connect via the PS remote App on my phone

**Comment by streetpea** [comment]
Then, it sounds like a settings issue on either your Steam Deck wireless connection or router as I mentioned above.

Can you try setting your PlayStation to a static ipv4 ip (on your router) and then pinging that ip (use command: `ping -c1 ip_address` where ip_address is your ip_address in a konsole window) from your Steam Deck to make sure it can reach it? 

You can also try from other devices. If you see it works from other devices but not your Steam Deck then you have confirmed that something is preventing it in your connection settings.

**Comment by datnodude** [comment]
> Then, it sounds like a settings issue on either your Steam Deck wireless connection or router as I mentioned above.
> 
> Can you try setting your PlayStation to a static ipv4 ip (on your router) and then pinging that ip (use command: `ping -c1 ip_address` where ip_address is your ip_address in a konsole window) from your Steam Deck to make sure it can reach it?
> 
> You can also try from other devices. If you see it works from other devices but not your Steam Deck then you have confirmed that something is preventing it in your connection settings.

I figured out if I manually add the host with the registered system, then toggle the SD wifi the correct host will pop up with the ps5 in standby mode as it should be. I don't know why but it works so I'll take it. thanks for the help

**Comment by datnodude** [comment]
resolved, user issue
