### ISSUE TITLE
Invalid PSN ID

### ISSUE THREAD

**Issue by hvmzx** [streetpea/chiaki4deck#181]
First of all, thanks for the great work you guys do !

I have tried the latest 1.6.0 appImage and it keeps throwing the Invalid PSN ID error. Also what is the PSN Login button next to the ID field ? When I click it, it opens an empty page.

**Comment by nowrep** [comment]
It only works with flatpak (qtwebengine nightmare with appimage).

**Comment by hvmzx** [comment]
Oh ok, weird that I get PSN ID error though because it used to work perfectly before using the base64 id

**Comment by streetpea** [comment]
@hvmzx you can copy your config from the flatpak build just use: `cp ~/.var/app/io.github.streetpea.chiaki4deck/config/Chiaki/Chiaki.conf ~/.config/Chiaki/Chiaki.conf` and then run the appimage again

**Comment by eskay993** [comment]
I'm having the same issue with Invalid PSN with both the flatpak version as well as the appimage (both on 1.6.0). Tried regular Chaiki appimage and it connected first time. So there might be something with the latest release causing an issue?

As a workaround I have also copied over my `Chiaki.conf` from regular Chaiki and it works, but just reporting it as someone else encountering this issue that it's not rtestr4iced to the appiamge.

**Comment by Connor898** [comment]
Getting this issue as well, first time setting up this on my steamdeck, getting the error code on my PS5: CE-110032-7

**Comment by delano8** [comment]
Same issue here (first setup).

**Comment by Connor898** [comment]
Still happening to me as well unfortunately

**Comment by delano8** [comment]
Indeed fixed for me after updating

**Comment by eskay993** [comment]
Fixed for me with 1.6.1. Thank you!
