### ISSUE TITLE
Windows 11 - PS5 DualSense Features Causing Crash

### ISSUE THREAD

**Issue by Suckmylittlefinger** [streetpea/chiaki4deck#187]
I got chiaki4deck working ok on Windows with default settings. After enabling the PS5 Features option to get adaptive triggers to work on my controller, every attempt at starting Chiaki causes remote play to crash. I need to restart my console and disable this option to get Chiaki working again
[chiaki_session_2024-01-16_13-56-07-955955.log](https://github.com/streetpea/chiaki4deck/files/13954694/chiaki_session_2024-01-16_13-56-07-955955.log)

**Comment by ibrahimqatar** [comment]
I can confirm I have the same problem

**Comment by ericma15** [comment]
me too

**Comment by B4NeRj3e** [comment]
Same here

**Comment by plexecutor** [comment]
Happens on Steam Deck also.
