### ISSUE TITLE
Feature Request: In app Analog sensitivity

### ISSUE THREAD

**Issue by hvmzx** [streetpea/chiaki4deck#192]
The sensitivity of the camera/movements has to often be modified between remote and local playing, as it's pretty slow on the Steam Deck from my experience.

Having the possibility to set up the sensitivity from chiaki would totally remove that necessity of always changing it when moving from deck to PS5.

**Comment by jbaiter** [comment]
Can't you do that via Steam? You can modify the controller profile and increase the scale/response curve/deadzones to suit your preferences.

**Comment by hvmzx** [comment]
Oh I didn't know this was a thing (new steam user). No need for this then, thanks !
