### ISSUE TITLE
[Feature Request] Enable vkbasalt post processing

### ISSUE THREAD

**Issue by karlosHelli** [streetpea/chiaki4deck#194]
It'd be great if [vkbasalt](https://github.com/DadSchoorse/vkBasalt) worked with chiaki4deck.
I tested with by enabling `ENABLE_VKBASALT=1` with `vulkan` as the Hardware Decoder, but it did not have any effect.
This could allow usage of various post processing shaders.

**Comment by jbaiter** [comment]
Our rendering backend (libplacebo) has support for custom shaders that can be applied as part of its postprocessing pipeline:

- API: https://github.com/haasn/libplacebo/blob/master/src/include/libplacebo/shaders/custom.h
- Shader language (mpv syntax): https://libplacebo.org/custom-shaders/

I think it should be relatively easy to add a configuration option for a path to a directory with custom shaders that can then be applied, would that work for you?

**Comment by nowrep** [comment]
It does work with vkbasalt.

**Comment by KishanPRao** [comment]
You're right!
I'm not sure if there's a way to get the system-wide install of vkbasalt working with a flatpak package, but installing the flatpak version of vkbasalt worked.
Thanks!
And thanks @jbaiter for knowledge sharing!
