### ISSUE TITLE
CE-110032-7 invalid PSN ID Chiaki4Deck 1.6.1

### ISSUE THREAD

**Issue by Benyo85** [streetpea/chiaki4deck#198]
Unfortunately I still have the error CE-110032-7. Despite version 1.6.1 the registration does not work.

**Comment by Benyo85** [comment]
It can't be due to the wrong ID being entered, as it works immediately with the old Chiaki version without 4Deck with the registration

**Comment by streetpea** [comment]
Fixed in the latest version of Chiaki4deck
