### ISSUE TITLE
Pinging the console throws an error, but connecting works

### ISSUE THREAD

**Issue by IrealiTY** [streetpea/chiaki4deck#2]
Hey, hi, thanks for your mods to the remote play app :D 

Had to remove this section from the script to get it to work, not sure why i can't ping my console from the steam deck (other network devices work fine)

```sh
ping -c 3 -w 30 xxx.xxx.xxx.xx &>/dev/null
sleep 1
```

also, I suggest maybe adding a longer sleep command after the wake-up (I use 4 :) )

**Comment by streetpea** [comment]
The ping command will wait up to 30 seconds for availability already with a minimum of 3 seconds, continuing once 3 successful pings (1 every second) are received. If the device is not up the ping command won’t return until later. If ping isn’t working for you I’d suggest a sleep of 10 seconds to be safe … I have found 4 to be inadequate.

**Comment by IrealiTY** [comment]
Yeah, I need to check why exactly ping is not working, I woke up the console manually and pinged from the deck to make the tests and got not response - I do think it must be something on my end, but it's good to know that it still works and yo u can connect nonetheless.

**Comment by streetpea** [comment]
You should be able to update now by (either updating the flatpak in the discover store or run flatpak update in the console) and going back through https://streetpea.github.io/chiaki4deck/setup/automation/ to update your launch script. It should work for you now as it no longer requires ping. Let me know how it goes.
