### ISSUE TITLE
WLAN Yes! lan Wire No 

### ISSUE THREAD

**Issue by Benyo85** [streetpea/chiaki4deck#202]
Streaming from the PS5 only works if the PS5 is connected to the WiFi. If it is connected to the cable, the connection to Chiaki4deck is lost immediately after starting. What could be the reason?

**Comment by jbaiter** [comment]
- Please enable debug logging and post a log of a connection that is lost immediately after startup. You can find the path to the logfiles in the settings.
- Are you using a discovered host to connect to the PS5 or a manually registered one? If it's the latter, the IP address is probably different between the wired and the wireless PS5.

**Comment by Benyo85** [comment]
![IMG_8785](https://github.com/streetpea/chiaki4deck/assets/156963252/8081b6be-1187-4c25-819c-b12b07c4225d)
![IMG_8786](https://github.com/streetpea/chiaki4deck/assets/156963252/d1797ba5-ebf2-4715-9391-bacd5a0cb263)

**Comment by Benyo85** [comment]
![IMG_8785](https://github.com/streetpea/chiaki4deck/assets/156963252/35d07be7-3ab8-41a6-83a8-82df0c334e91)
![IMG_8786](https://github.com/streetpea/chiaki4deck/assets/156963252/03ea9014-73c0-4df5-a986-2cc3638992b7)

**Comment by Benyo85** [comment]
Finaly it Works. Thanks

**Comment by Oncle-BOB** [comment]
Good evening, i also have this problem but i have the impression that there is a bug in a particular condition.

If
- ps5 in lan and steamdeck in lan = works
- ps5 on wifi and steamdeck on wifi = works
- ps5 on wifi and steamdeck on lan = works
- ps5 on lan and steamdeck on wifi = not work

in the latter case if you configure with console discovery it does not work. If you configure manually it works but if you close chiaki and restart it it will no longer work.

Here are my logs when it works and no longer works

[chiaki_session_good.log](https://github.com/streetpea/chiaki4deck/files/14089302/chiaki_session_good.log)
[chiaki_session_fail.log](https://github.com/streetpea/chiaki4deck/files/14089301/chiaki_session_fail.log)
