### ISSUE TITLE
1.6.1 flatpak has stutters, appimage is fine

### ISSUE THREAD

**Issue by Jaxsown** [streetpea/chiaki4deck#204]
Hi, i've bad performance in the latest patch, it stutter for 2 sec every 10 sec. The appimage is fine but it use 12w vs 7w of the flatpak.
1.5 .1 flatpak is also fine.
Tested on a steam deck lcd and a oled.

**Comment by d00maz** [comment]
i can confirm, i got the same issue,feels like the frametimes are worse and theres stutter.
going back to 1.5.1 makes it flawless

ive tried different bitrates, that changed nothing.

is there a way to generate any useful information?

**Comment by nowrep** [comment]
> The appime is fine but it use 12w vs the 7w of the flatpak.

There's currently issue with appimage build where it unintentionally uses alsa audio backend which triggers some bug in SDL and its alsa hotplug thread is at 100% cpu use. Fixed in #199

You can set `env SDL_AUDIOBACKEND=pipewire %command%` to workaround it until there is a new build.

**Comment by nowrep** [comment]
> is there a way to generate any useful information?

Please post screenshot with performance overlay enabled. Also what settings are you using: frame limit, disable frame limit, allow tearing?

**Comment by hvmzx** [comment]
> 1.6.1 flatpak https://github.com/streetpea/chiaki4deck/assets/143872583/99c82228-69ed-420c-ad25-1dbaa59d9737
> 
> 1.6.1 appimage same config https://github.com/streetpea/chiaki4deck/assets/143872583/945b02ae-8c91-4719-b7d7-bd4c26094f1f
> 
> Sry i had to cut the video lenght for 10mo limitation

The difference is quite significant, also do you have HDR on both ?

**Comment by Jaxsown** [comment]
> > 1.6.1 flatpak https://github.com/streetpea/chiaki4deck/assets/143872583/99c82228-69ed-420c-ad25-1dbaa59d9737
> > 1.6.1 appimage same config https://github.com/streetpea/chiaki4deck/assets/143872583/945b02ae-8c91-4719-b7d7-bd4c26094f1f
> > Sry i had to cut the video lenght for 10mo limitation
> 
> The difference is quite significant, also do you have HDR on both ?

Nope, hdr disabled on both
