### ISSUE TITLE
Stopping a session freezes the app on Windows

### ISSUE THREAD

**Issue by ibrahimqatar** [streetpea/chiaki4deck#212]
This was a bug ever since 1.6, sometimes the app just freezes and I have to kill it through task manager or it will crash.

I have tested this on my Legion go on Windows 11

**Comment by Ev0lutionSm0ke** [comment]
Same issue I have. Screen goes black and freezes.  Legion Go as well.

**Comment by Mindofone** [comment]
I have tested this on my desktop PC with Win 11, same experience.

**Comment by streetpea** [comment]
Do you have logs when this happens. Without logs , it hard to say what’s happening

**Comment by Mindofone** [comment]
Here is a log from me
[chiaki_session_2024-01-18_17-28-49-915915.log](https://github.com/streetpea/chiaki4deck/files/13999890/chiaki_session_2024-01-18_17-28-49-915915.log)
