### ISSUE TITLE
Black screen when dying on God of War Ragnarok

### ISSUE THREAD

**Issue by ibrahimqatar** [streetpea/chiaki4deck#213]
When I get killed in the game then press X to restart from last checkpoint, the screen turns black and never comes back unless I restart the session (which freezes as per my previous issue I submitted).

I'm on Legion Go using Windows 11.

This problem is not present on 1.5.0

Here is a link for the log file:

https://ia601309.us.archive.org/17/items/chiaki_session_2024-01-20_00-05-48-720720/chiaki_session_2024-01-20_00-05-48-720720.log

**Comment by lkuczborski** [comment]
Yeah, same here. It freezes very often with Ragnarok on ROG Ally too. Tested on release 1.6.1.

**Comment by lkuczborski** [comment]
Just got the freeze on the Prince of Persia: The Lost Crown too. The video stream was stopped (freeze frame) but I was stil able to control the console with the Ally, just the video was frozen on one frame.

**Comment by ibrahimqatar** [comment]
I also noticed that this happens when I press the ps button and then choose the home icon, this happens as well

**Comment by Ev0lutionSm0ke** [comment]
> Just got the freeze on the Prince of Persia: The Lost Crown too. The video stream was stopped (freeze frame) but I was stil able to control the console with the Ally, just the video was frozen on one frame.

Yup, this happens on my Legion Go. Screen is black on handheld but i can use it as a controller pretty much

**Comment by nowrep** [comment]
Please post logs (make sure to enable verbose logging) instead of just saying "me too". Thanks.

**Comment by lkuczborski** [comment]
This relates to #212 and possibly #207. Tried to record logs now but even though verbose logging is enabled there is no file at the path shown in chiaki4deck.

**Comment by nowrep** [comment]
#212 is completely different issue, and should be fixed with b6aaaf1e9539cc40df4870d678a31.

This and #207 is same issue as #103, #125 and #138.

**Comment by streetpea** [comment]
@lkuczborski it might be that the file is hidden. Make sure you are displaying hidden files.

**Comment by streetpea** [comment]
> #212 is completely different issue, and may already be fixed.
> 
> 
> 
> This and #207 is same issue as #103, #125 and #138.

Some of those are the opposite issue where incoming packets are still being accepted but outgoing packets aren't being accepted by the ps

**Comment by lkuczborski** [comment]
> @lkuczborski it might be that the file is hidden. Make sure you are displaying hidden files.

Yeah, it was hidden. Attaching recorded logs.

[chiaki_session_2024-01-20_15-12-05-319319.log](https://github.com/streetpea/chiaki4deck/files/14000487/chiaki_session_2024-01-20_15-12-05-319319.log)
[chiaki_session_2024-01-20_15-23-52-431431.log](https://github.com/streetpea/chiaki4deck/files/14000488/chiaki_session_2024-01-20_15-23-52-431431.log)
[chiaki_session_2024-01-20_15-28-19-482482.log](https://github.com/streetpea/chiaki4deck/files/14000489/chiaki_session_2024-01-20_15-28-19-482482.log)
[chiaki_session_2024-01-20_15-38-39-840840.log](https://github.com/streetpea/chiaki4deck/files/14000490/chiaki_session_2024-01-20_15-38-39-840840.log)
[chiaki_session_2024-01-20_16-39-41-276276.log](https://github.com/streetpea/chiaki4deck/files/14000491/chiaki_session_2024-01-20_16-39-41-276276.log)
[chiaki_session_2024-01-20_16-45-21-065065.log](https://github.com/streetpea/chiaki4deck/files/14000492/chiaki_session_2024-01-20_16-45-21-065065.log)

**Comment by nowrep** [comment]
Please enable verbose logging.

**Comment by lkuczborski** [comment]
> Please enable verbose logging.

Hmm, I did. But maybe it was not active for every log I sent?

**Comment by lkuczborski** [comment]
Attaching one more. Verbose Logging was enabled during this session.

[chiaki_session_2024-01-21_09-04-11-840840.log](https://github.com/streetpea/chiaki4deck/files/14000578/chiaki_session_2024-01-21_09-04-11-840840.log)

**Comment by nowrep** [comment]
Thanks. When in this state, can you still send controller input to the console (check on TV)? Also can you check network activity in task manager?

**Comment by lkuczborski** [comment]
Just checked when it froze while browsing inventory in God of War: Ragnarok. I was still controlling the game via controls (checked on TV) and frame was frozen on one frame. The network activity showed around 10-14 MB/s usage and around 4 MB/s while doing nothing.

**Comment by lkuczborski** [comment]
> Thanks. When in this state, can you still send controller input to the console (check on TV)? Also can you check network activity in task manager?

Just checked when it froze while browsing inventory in God of War: Ragnarok. I was still controlling the game via controls (checked on TV) and video was frozen on one frame. The network activity showed around 10-14 MB/s usage and around 4 MB/s while doing nothing.

**Comment by nowrep** [comment]
I think this is a deadlock, can you get a backtrace when it freezes? If possible also with debug build.

**Comment by lkuczborski** [comment]
> I think this is a deadlock, can you get a backtrace when it freezes? If possible also with debug build.

You mean with verbose logging enabled or with different build of Chiaki? Also how do I get backtrace on Windows 11 (no specific dev tools installed as it is ROG Ally)? :)

**Comment by nowrep** [comment]
WinDbg should work https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by nowrep** [comment]
Debug build here https://github.com/nowrep/chiaki4deck/actions/runs/7601098941

**Comment by ericma15** [comment]
> Debug build here https://github.com/nowrep/chiaki4deck/actions/runs/7601098941

i use your version，when freeze it show erro.
![Microsoft Visual C++ Runtime Library 2024_1_21 23_22_48](https://github.com/streetpea/chiaki4deck/assets/27952575/5cda331c-8070-45a1-ac0b-192c3365ef86)

**Comment by ibrahimqatar** [comment]
> Debug build here https://github.com/nowrep/chiaki4deck/actions/runs/7601098941

![image](https://github.com/streetpea/chiaki4deck/assets/18020735/548eb377-7ddd-4b1e-a132-d1f4807f1b2a)

I get this error when going to home and then resuming the game. I tapped on retry and the whole device stopped responding and I had to hard restart..

I tried again after restarting, going to home and coming back a couple of times triggered the same message above. Here is the log:

https://ia601309.us.archive.org/19/items/chiaki_session_2024-01-21_18-25-13-744744/chiaki_session_2024-01-21_18-25-13-744744.log

**Comment by ericma15** [comment]
here is x64 dbg output when freeze. version is 1.6.1
![chiaki exe - PID_ 19976 - 线程_ 主线程 16672 - x64dbg  管理员  2024_1_21 23_30_04](https://github.com/streetpea/chiaki4deck/assets/27952575/cd54a5a8-b569-4dee-ac29-d5ac3812639b)
![chiaki exe - PID_ 19976 - 线程_ 主线程 16672 - x64dbg  管理员  2024_1_21 23_30_18](https://github.com/streetpea/chiaki4deck/assets/27952575/d1e3da15-44bf-4a1f-94b4-a37dc5133226)
![chiaki exe - PID_ 19976 - 线程_ 主线程 16672 - x64dbg  管理员  2024_1_21 23_30_27](https://github.com/streetpea/chiaki4deck/assets/27952575/74b8a839-1866-47e6-862a-e0c8a7576ba6)
![chiaki4deck 2024_1_21 23_29_58](https://github.com/streetpea/chiaki4deck/assets/27952575/4abb1259-5304-404d-8492-8493f6e5bb6c)

**Comment by nowrep** [comment]
What codec do you use? Also can you get backtrace from the debug build (the one you posted is from 1.6.1 release?)

**Comment by ericma15** [comment]
> What codec do you use? Also can you get backtrace from the debug build (the one you posted is from 1.6.1 release?)

d3d11va

**Comment by nowrep** [comment]
Codec from settings: H264 / H265 / H265 HDR

**Comment by ericma15** [comment]
here is info, the thread 24848 is the backtrace
![chiaki exe - PID_ 19976 - 线程_ 主线程 16672 - x64dbg  管理员  2024_1_21 23_44_44](https://github.com/streetpea/chiaki4deck/assets/27952575/9dd629a5-7f57-47c5-bf04-f84f5cba2e10)
![chiaki exe - PID_ 17832 - 模块_ kernelbase dll - 线程_ 24848 - x64dbg  管理员  2024_1_21 23_45_12](https://github.com/streetpea/chiaki4deck/assets/27952575/352eec2b-40c8-4a00-ad61-47166d5bb627)
![chiaki exe - PID_ 17832 - 模块_ kernelbase dll - 线程_ 24848 - x64dbg  管理员  2024_1_21 23_46_31](https://github.com/streetpea/chiaki4deck/assets/27952575/b32bb556-ae40-4a93-bb21-1cefe4b1d3d6)
![chiaki exe - PID_ 19976 - 线程_ 主线程 16672 - x64dbg  管理员  2024_1_21 23_30_04](https://github.com/streetpea/chiaki4deck/assets/27952575/35b13290-2f5b-4b25-9dba-f44ba4f28f43)

**Comment by ericma15** [comment]
> Codec from settings: H264 / H265 / H265 HDR



> Codec from settings: H264 / H265 / H265 HDR

H265

**Comment by ericma15** [comment]
> here is info, the thread 24848 is the backtrace ![chiaki exe - PID_ 19976 - 线程_ 主线程 16672 - x64dbg 管理员 2024_1_21 23_44_44](https://private-user-images.githubusercontent.com/27952575/298394384-9dd629a5-7f57-47c5-bf04-f84f5cba2e10.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTIzOTcsIm5iZiI6MTcwNTg1MjA5NywicGF0aCI6Ii8yNzk1MjU3NS8yOTgzOTQzODQtOWRkNjI5YTUtN2Y1Ny00N2M1LWJmMDQtZjg0ZjVjYmEyZTEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE1NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3OGJhMWU2MTZlOGMzMWJhZTA3NzcyNjNkMjViODA0MTIxNGFiYzFlZjRjZGIxZWI0NDIyYzcwMDMwNTJhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sbrBTcB0nD1OGLyY5urK7IjG_L0xjMVhynZaFj7J-8) ![chiaki exe - PID_ 17832 - 模块_ kernelbase dll - 线程_ 24848 - x64dbg 管理员 2024_1_21 23_45_12](https://private-user-images.githubusercontent.com/27952575/298394392-352eec2b-40c8-4a00-ad61-47166d5bb627.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTIzOTcsIm5iZiI6MTcwNTg1MjA5NywicGF0aCI6Ii8yNzk1MjU3NS8yOTgzOTQzOTItMzUyZWVjMmItNDBjOC00YTAwLWFkNjEtNDcxNjZkNWJiNjI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE1NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNjc3YmQwZTcyMjdkYzRkNDMyMDk3YTgzNDA1MWQ1N2YzNjdmZjFjOWQ4OTI3ZjJmMDgxNWZlZGYwYjdlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKgPWnBw90NJECESUzYrvyKzdy74yIGEJJdqOnQrLuQ) ![chiaki exe - PID_ 17832 - 模块_ kernelbase dll - 线程_ 24848 - x64dbg 管理员 2024_1_21 23_46_31](https://private-user-images.githubusercontent.com/27952575/298394395-b32bb556-ae40-4a93-bb21-1cefe4b1d3d6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTIzOTcsIm5iZiI6MTcwNTg1MjA5NywicGF0aCI6Ii8yNzk1MjU3NS8yOTgzOTQzOTUtYjMyYmI1NTYtYWU0MC00YTkzLWJiMjEtMWNlZmU0YjFkM2Q2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE1NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1MTU5NTNmOTlhNjNjMmI4NDUyMjJhM2VmMzI3MDc0NmNjZjNkMjQ2YTcxZDY0NTcwNDc5OWNjM2E2NDFjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qv6CTrmkOUAKprOTJw-pgkUEaN52OEHt-EOotdClDLE)

this is your debug build version. Seems x64_dbg cannot parse the symbol.

**Comment by nowrep** [comment]
Please try this build and post log (not verbose): https://github.com/nowrep/chiaki4deck/actions/runs/7602369673

> Maybe another build with -g ？

No idea why it doesn't show symbols, they are in the exe.

**Comment by ericma15** [comment]
> Please try this build and post log (not verbose): https://github.com/nowrep/chiaki4deck/actions/runs/7602369673
> 
> > Maybe another build with -g ？
> 
> No idea why it doesn't show symbols, they are in the exe. The symbols are probably in different format, since this is msys build and not msvc.

here is log without vetbose.
[chiaki_session_2024-01-22_00-26-35-093093.log](https://github.com/streetpea/chiaki4deck/files/14002009/chiaki_session_2024-01-22_00-26-35-093093.log)

**Comment by nowrep** [comment]
Should be fixed in this build: https://github.com/nowrep/chiaki4deck/actions/runs/7602500674

**Comment by ericma15** [comment]
> Should be fixed in this build: https://github.com/nowrep/chiaki4deck/actions/runs/7602500674

It works for me. Now it run well. Hope this merge to main branch ASAP.
