### ISSUE TITLE
Improper framepacing on Steam Deck.

### ISSUE THREAD

**Issue by liaml777** [streetpea/chiaki4deck#218]
Version 1.6.1 exhibits improper frame pacing on Steam Deck. Gamescope frame limiter does not work. Issue happens independent of resolution,  frame rate or bitrate settings, but the impact of the stutters get worse with lower settings.

![20240120_131517](https://github.com/streetpea/chiaki4deck/assets/157259156/48600a1f-16b1-4bdb-befe-3e247f7d4879)
![20240120_130615](https://github.com/streetpea/chiaki4deck/assets/157259156/bc4fe49a-5032-4ca7-a297-98406d08df89)

Rolling back to 1.5.1 fixes the issue.

**Comment by LordNoxington** [comment]
Also ran into this issue. I believe a PR that fixes it has already been merged, but hasn't been pushed as a release.

**Comment by plexecutor** [comment]
Noticed issue as well as soon as I upgraded to 1.6.1 on my deck. Glad to hear a PR is already inthe works. Looking forward to the fix.

**Comment by Jaxsown** [comment]
> Also ran into this issue. I believe a PR that fixes it has already been merged, but hasn't been pushed as a release.

#205 i believe

**Comment by streetpea** [comment]
closing as this is a dup of #205 and presumably been fixed as reported there. Will release soon
