### ISSUE TITLE
Steam deck OLED internal Mic stops working during gameplay.

### ISSUE THREAD

**Issue by SupurClay** [streetpea/chiaki4deck#223]
Audio settings is set to default. During game play the mic is working fine until about 5-10mins into the game,my friends could not hear me and the app is not registering a mic icon when speaking. I would need to close out the chiaki app and reconnect during gameplay and mic will start to work again. Is there anyone going through the same issue? Other then that, chiaki4deck app is working flawlessly. Thanks!

[chiaki_session_2024-01-22_22-07-22-534534.log](https://github.com/streetpea/chiaki4deck/files/14019276/chiaki_session_2024-01-22_22-07-22-534534.log)
[chiaki_session_2024-01-22_22-12-57-777777.log](https://github.com/streetpea/chiaki4deck/files/14019277/chiaki_session_2024-01-22_22-12-57-777777.log)
[chiaki_session_2024-01-22_22-23-02-120120.log](https://github.com/streetpea/chiaki4deck/files/14019278/chiaki_session_2024-01-22_22-23-02-120120.log)

 SteamOS
 - Version 3.5.7
 - Steam Deck OLED 512gb
 - Chiaki4deck Version  1.6.2

**Comment by chanksworld** [comment]
I'm having this issue as well on OLED Deck, Chiaki 1.6.0
