### ISSUE TITLE
[BUG] High power draw (TSP)

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#226]
**Describe the bug**
I've gotten atleast 40 hours of gaming in with the new chiaki4deck and it's been flawless. One thing I have noticed is my total system power sometimes will shoot up to 8.4w which dramatically kills the overall battery life. It usually sits at 5.4w with the same exact brightness and games. It's very random and I am unable to reproduce the issue. I thought I had fixed it after changing my bitrate but after a week of playing with max HDR brightness and speakers at 5.4w I am now getting stuck at a power draw of 8.4w. 

I have tried resetting my router. I have restarted my PS5 (that fixed the issue one time but didn't work again for me). I have made sure there is nothing else downloading in the background. 

In the bigger picture of things this is a nothing burger but the little things bother me lol. 

At 5.4w I get a little Over an hour of battery life for 10% battery. 100% battery I get a little Over 10 hours vs 8.4w I'm getting 6 1/2 hrs of battery life from 100% battery. That's pretty big chunk of change gone. 

**Desktop (please complete the following information):**
 - OS: latest stable branch
 - Device OLED Steam Deck
 - Chiaki4deck Version 1.6.2
![20240122_230944](https://github.com/streetpea/chiaki4deck/assets/120707099/2784fc35-6be5-40b3-8ace-6b3450cf433b)
![20240123_185652](https://github.com/streetpea/chiaki4deck/assets/120707099/1cc8a782-b9a7-46cb-aa44-2b5ca4a48631)

As you can see in the pictures above the tsp is drastically different but this is the same game and same settings for everything. Sometimes it settles around 7w and other times it shoots up to 8.4w. Before it would sit at 5.4w with the same settings on every single game I played.

**Comment by nowrep** [comment]
You don't show CPU power draw on second screenshot. If the power draw difference isn't increased CPU or GPU usage I'm not sure there's anything to do about it.

**Comment by iTsMute** [comment]
> You don't show CPU power draw on second screenshot. If the power draw difference isn't increased CPU or GPU usage I'm not sure there's anything to do about it.
> 
> I assume you have Fast preset enabled in settings, which currently doesn't work so that would explain it.

The cpu/gpu usage is the same. I think this has more to do with steam os power managment than with chiaki but just incase I wanted to post the issue to bring awareness to it incase there is something that can be done on chiakis end. It is super weird that it has no issues with all the same settings at 5.4w but then get stuck at 7w-8.4w eventually. 

Power managment for the wifi module is on btw. 

I've had one person in the past say it has to do with hdr, however my week long of playing multiple games at max hdr 5.4w debunked that. Literally no changes buy more power draw.

**Comment by iTsMute** [comment]
![20240129_215742](https://github.com/streetpea/chiaki4deck/assets/120707099/e1fb3035-a3aa-48ad-9b01-28533dc7dd58)
![20240129_215746](https://github.com/streetpea/chiaki4deck/assets/120707099/943af721-7a19-4e99-9935-5b87ade5b9f7)


Here is the 8.4w happening. I've tried beta branch out for Steam os and it went all the way to 9w. 

I'll try disabling wifi 6 next to see if that has ant effect

**Comment by nowrep** [comment]
As I already said, the issue is that it's not possible to set Fast preset. It will be fixed in next release.

**Comment by iTsMute** [comment]
> As I already said, the issue is that it's not possible to set Fast preset. It will be fixed in next release.

Is there a known time frame for the next update release?

**Comment by streetpea** [comment]
1.6.3 that includes the fix got released yesterday

**Comment by iTsMute** [comment]
> As I already said, the issue is that it's not possible to set Fast preset. It will be fixed in next release.

Is there a known time frame for the next update release?

> 1.6.3 that includes the fix got released yesterday

Awesome thank you

**Comment by iTsMute** [comment]
Can confir

**Comment by hvmzx** [comment]
@iTsMute Do you have an hdr display? Because i can activate the hdr in chiaki4deck and I got the hdr badge on the deck but i don't believe it does render the game as such because my display isn't hdr.

**Comment by iTsMute** [comment]
Seems the issue is back unfortunately 😕 

I've tried about everything on my end. Not sure if the "Fast" preset is not sticking again.

**Comment by iTsMute** [comment]
Reopening issue. 1.6.5 fixed this issue completely I Could play all games at 5.4w., Updated to 1.6.6 and now tsp is sitting around 6.2w-6.4w

**Comment by iTsMute** [comment]
Welp I was wrong. It seems to be indicating something to do with my own network. I've just hopped on to my ps5 from a different network and tsp is sitting at 5.7w. Sorry about that 😅
![Uploading 20240409_212654.jpg…]()
