### ISSUE TITLE
[BUG] Automatic script set stream quality ever at "High Quality" even if is selected "Default Quality" in chiaki app

### ISSUE THREAD

**Issue by TedMosly** [streetpea/chiaki4deck#231]
**Describe the bug**
When connect to my PS4 trought the automatic script, it set stream quality ever to "High Quality" even if is selected "Default Quality" in chiaki app

**Expected behavior**
Automatic script follow the app settings

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version 3.5
 - Device Steam Deck
 - Chiaki4deck 1.6.2

**Comment by nowrep** [comment]
Yes

**Comment by streetpea** [comment]
fixed with release 1.6.3
