### ISSUE TITLE
[BUG] Sometimes PS doesn't appear in list

### ISSUE THREAD

**Issue by kaibagley** [streetpea/chiaki4deck#232]
**Describe the bug**
Sometimes registered PS5 won't appear in the interface

**Debug Log**
Log is not being created

**To Reproduce**
Steps to reproduce the behavior (only occurs sometimes):
1. Register a PS5 and successfully use it
2. Open Chiaki4deck
3. PS5 not showing up (sometimes)

**Expected behavior**
PS5 always shows up

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Latest
 - Device: PC
 - Chiaki4deck Version: 1.6.2

**Comment by streetpea** [comment]
If you add it manually it will always show up, if you just add it via the discovered connection it will only show up if it’s discovered locally. There are a number of reasons why it won’t be discovered with the main reason being it isn’t on the local network.
