### ISSUE TITLE
Reconnecting after power interruption to ps5

### ISSUE THREAD

**Issue by rahulvigneswaran** [streetpea/chiaki4deck#234]
When in rest mode if there is a power interruption, ps5 defaults to a screen where we need to manually press the ps button on the dualsense and press okay to get into the login screen. It’s not possible to remote play till this routine is done. 

Is there a way to bypass this or do we have any leads in it?

**Comment by jbaiter** [comment]
Does it work as you expect with the official app?

**Comment by rahulvigneswaran** [comment]
No it doesn't. That's why I was enquiring if there is any workaround to bypass this power interruption routine.

**Comment by rahulvigneswaran** [comment]
Thank you!
