### ISSUE TITLE
[BUG] Audio output fails to recognize and send to Steam Deck

### ISSUE THREAD

**Issue by Rinaldus7** [streetpea/chiaki4deck#235]
LCD Deck 512GB
Chiaki4deck version 1.6.2
Updated from 1.4.2 and latest update seems to have broken audio outputting. Remote play now only sends audio to TV or PS5 Headphones(if connected).

No changes to audio settings in chiaki4deck or on the PS5's audio settings resolve issue. Neither did a fresh install of Chiaki4Deck. Regular Chiaki works fine.

**Comment by streetpea** [comment]
Please post a log of when you are running into this issue.

**Comment by streetpea** [comment]
The log of a session where this is happening. You can find the log directory by opening Chiaki4deck and looking in the main settings for log directory. Using the flatpak on Steam deck this will be /home/deck/.var/app/io.github.streetpea.Chiaki4deck/data/Chiaki/Chiaki/log

**Comment by Rinaldus7** [comment]
That makes much more sense. Here you are. Removed IP Addresses though, figured that'd be fine.

[chiaki_session_2024-01-29_11-21-50-683683.log](https://github.com/streetpea/chiaki4deck/files/14087114/chiaki_session_2024-01-29_11-21-50-683683.log)

**Comment by streetpea** [comment]
What are your current audio settings in Chiaki4deck?

**Comment by Rinaldus7** [comment]
Output Device: Auto
Input Device: Auto
Buffer Size: Deafult(5760)
Speech processing: Noise suppresion +echo cancellation checked on
Noise to Suppress: 6dB
Echo to suppress: 30dB

**Comment by streetpea** [comment]
Can you please try manually selecting the ACP/ACP3X/ACP6x Audio Coprocessor Speaker audio device as your audio output?

**Comment by Rinaldus7** [comment]
Tried it again, still no dice. I tried the headphones one as well, as well as the virtual and filter chain sinks. With all settings, audio still defaults to outputting through the TV Speakers.

**Comment by streetpea** [comment]
Audio should play through both your Steam deck and tv speakers not one or the other

**Comment by streetpea** [comment]
Can you post another log with verbose logging enabled please?

**Comment by Rinaldus7** [comment]
I'd absolutely be down to, but could you explain how?

**Comment by Rinaldus7** [comment]
And do you want the log to have the audio output set to auto or to the ACP/ACP3X/ACP6x Audio Coprocessor Speaker?

**Comment by streetpea** [comment]
Leave it at acp...you can enable verbose logging by clicking the verbose logging checkbox in the general tab in the settings

**Comment by Rinaldus7** [comment]
Here it is
[chiaki_session_2024-01-29_16-47-51-838838.log](https://github.com/streetpea/chiaki4deck/files/14090143/chiaki_session_2024-01-29_16-47-51-838838.log)

**Comment by streetpea** [comment]
Can you try running the flatpak with `flatpak run --env=SDL_AUDIODRIVER=pulse io.github.streetpea.Chiaki4deck`?

**Comment by Rinaldus7** [comment]
That did it! Very cool. Thanks so much.

Soooo. Would you be able to tell me how I get this to launch like this from Gaming Mode? What would I put in for the launch options? I would be VERY grateful.

**Comment by streetpea** [comment]
FYI you can also use `flatpak override --unset-env SDL_AUDIODRIVER` and then you won't need to launch with any envvars

**Comment by streetpea** [comment]
Which SteamOS version are you on (preview, beta or stable)? Also did you install any pacman packages on your Steam Deck or change pipewire specifically? (Just trying to figure out why pipewire isn’t working on your system)

**Comment by Rinaldus7** [comment]
> FYI you can also use `flatpak override --unset-env SDL_AUDIODRIVER` and then you won't need to launch with any envvars

I don't know enough about envvars to unset them. What could that potentially affect in the future?

> Which SteamOS version are you on (preview, beta or stable)? Also did you install any pacman packages on your Steam Deck or change pipewire specifically? (Just trying to figure out why pipewire isn’t working on your system)
And I'm on Stable at the moment. And no I don't think so. I don't know what pacman packages are, nor what pipewire is. So I wouldn't have changed those myself. Maybe Emudeck or [7thDeck](https://github.com/dotaxis/7thDeck) made some changes and I'm just not aware of them? I feel like those are the bigger non-steam apps that I have installed on my Deck. Ones that installed by running various scripts through konsole.

Also let me know if you'd like me to close this or anything.

**Comment by nowrep** [comment]
Can you try if you can also reproduce this with appimage?

**Comment by dkinnard** [comment]
> > FYI you can also use `flatpak override --unset-env SDL_AUDIODRIVER` and then you won't need to launch with any envvars
> 
> I don't know enough about envvars to unset them. What could that potentially affect in the future?
> 
> It’s specifically upsetting the envvar for pipewire for the io.github.streetpea.Chiaki4deck flatpak since it uses pipewire to support dualsense haptics with an attached dualsense but pipewire isn’t working for audio as a driver for your Steam Deck

If you are still trying to get this to work, the correct command is 

```flatpak override --user --env=SDL_AUDIODRIVER=pulse io.github.streetpea.Chiaki4deck```
