### ISSUE TITLE
[ RUMBLE ] --- Windows/controllers function.

### ISSUE THREAD

**Issue by Bardok1984** [streetpea/chiaki4deck#237]
With Chiaki4deck Steam deck users are able to enjoy playing with Rumble in PS5 games.

The haptic Rumble from PS5 is "translated" by Chiaki4deck which forces it to work on Steam deck as Standard Rumble .

Nevertheless, what about native Windows hanheld users? 

Asus rog Ally
Lenovo Legion Go
Onexplayer 
Aya neo 

All of these Devices have integrated controllers as well as are recognized same as Xbox controller . So, could some day make Chiaki4deck can give Rumble function as well as Steam deck has?

Perhaps with the 1.6.3 ?? When Will be It out?

I really BEG PLEASE the inclusion of Vibration/Rumble for Ps5 games when using Windows on these consoles, regardless of Its nature.

**Comment by streetpea** [comment]
This is already implemented and will be included in the next release.

**Comment by Bardok1984** [comment]
Main...you mean in Chiaki4deck 1.6.2??

With this versión just Steam deck on Steam os has Rumble with the beta experimental option...ps5 haptic Rumble works as Standard Rumble.

However with Legión Go, or Asus Rog Ally...there is No Rumble , nothing.. even using chiaki4deck 1.6.2 and enabling the experimental option...

Will the Chiaki4deck 1.6.3 Include this function to work on Windows consoles such as Lenovo Legion Go or Asus Rog Ally ??

Could you confirm this please?? When Will be ready the 1.6.3???

Thank you so much for your invaluable support

**Comment by streetpea** [comment]
No by main I mean the main branch of the code. This is the current version of the code which has been updated since last release. When the time for the next release comes the current version of main is tagged and released.

**Comment by Bardok1984** [comment]
Oh, I really feel so thankfull for your support

I Will try that given Build to see if I can make Rumble function work on my Lenovo Legion Go with windows and let you know soon

Anyway, I really wish soon the main 1.6.3 version to make ps5 haptic games giving US vibration with Windows consoles through Chiaki4deck.

Thank you so much, you are breathtaking

**Comment by Bardok1984** [comment]
Would that Build make Rumble (ps5 haptic vibration) function work on Windows consoles ? (Legion Go for instance) ????

I Will try It.

When could be ready/out the 1.6.3 main versión of Chiaki4deck? This spring?

Thank you so much,

**Comment by streetpea** [comment]
added with 1.6.3
