### ISSUE TITLE
Off-topic, getting account id outside of steamdeck

### ISSUE THREAD

**Issue by JimZiii** [streetpea/chiaki4deck#24]
I apologize for cluttering your github instead but the original git had been locked to read only and moved to somewhere else where u can't find anywhere to ask this question.

I'm trying to get my account id the regular way explained on the official page but its not working.
Is it possible to use some of your processes to get my account id even if i don't own a steamdeck? And if it is, then how?

**Comment by streetpea** [comment]
Hi, not sure if you are on Linux or not. However, you can download and use the flatpak if you are on Linux. While a lot of the updates made are focused on improving the Steam Deck everything works on other Linux machines as well. You would just need to have flatpak installed on your system to run that command. You could also use it or just uninstall it afterward. You can also run the same command in the docs using the Chiaki flatpak just substitute re.chiaki.Chiaki4deck with re.chiaki.Chiaki once you install that flatpak. If you are not on Linux or don’t want to install a flatpak there is a site [here](https://psn.flipscreen.games/) that lets you get your id if you set it to public (it then searches for it like anyone else could if you do that). You can also of course use python on a computer of your choosing as long as you use the older version of requests.

**Comment by streetpea** [comment]
Oh, I just saw that you already closed the issue. Glad you figured it out :)

**Comment by JimZiii** [comment]
Thank you for the reply, you responded at the same time as i deleted it.
I found the problem i was having.
But thnx anyways
