### ISSUE TITLE
[BUG] Duplicate entry

### ISSUE THREAD

**Issue by hvmzx** [streetpea/chiaki4deck#244]
When having a manual remote PS5, it shows as 2 entries (1 manual and the other one discovered).

I also discovered that when disabling the discovery with the bottom left corner icon, it switches back on after relaunching the app or starting a session and closing it. It would be great that it just stays disabled so one doesn't have too many entries.

**Desktop (please complete the following information):**
 - SteamOS
 - Version 3.5.7
 - Steam Deck
 - Chiaki4deck Version 1.6.2

**Comment by nowrep** [comment]
That's expected if the remote IP is different from discovered IP.

> It would be great that it just stays disabled

Discovery is required for auto-wakeup  and auto-connect.
