### ISSUE TITLE
[Feedback] Controller Options - /setup/controlling/

### ISSUE THREAD

**Issue by Jijerry1112** [streetpea/chiaki4deck#249]
I am sorry I can't see the chiaki4deck+mic layout on the community layout page. Could you pls reupload one to the Steam community page?

**Comment by fballan93** [comment]
I'm having the same exact issue can't find the controller layout out anywhere although my app name is chiaki4deck

**Comment by dEEkAy2k9** [comment]
i found another one that does the same. it's called "chiaki4deck+ mic".
you have to look for the one that has got CONTROL + stuff mapped on grip buttons.
