### ISSUE TITLE
[BUG] random disconnects

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#250]
After about 30 minutes stream disconnects randomly. 

Latest stable branch and latest chiaki 1.6.3

**Comment by streetpea** [comment]
Please post logs for a session where this occurs with verbose logs enabled

**Comment by iTsMute** [comment]
> Please post logs for a session where this occurs with verbose logs enabled

Will do!

**Comment by InsaneDad** [comment]
Same problem on win 11
[chiaki_session_2024-02-09_00-26-07-658658.log](https://github.com/streetpea/chiaki4deck/files/14214701/chiaki_session_2024-02-09_00-26-07-658658.log)

**Comment by iTsMute** [comment]
> Same problem on win 11 [chiaki_session_2024-02-09_00-26-07-658658.log](https://github.com/streetpea/chiaki4deck/files/14214701/chiaki_session_2024-02-09_00-26-07-658658.log)

@streetpea

**Comment by streetpea** [comment]
Does it exit out of Chiaki4deck completely or just back to the menu?

**Comment by iTsMute** [comment]
> Does it exit out of Chiaki4deck completely or just back to the menu?

I plan on getting log info for you aswell. 

I've had it completely exit the app once on oled deck and go back to just the menu twice.

**Comment by streetpea** [comment]
Do you have a log from when this happens on Linux (I've noticed the windows logs are not complete compared to the Linux version) ... if it's closing out to the menu there is likely something causing it to close such as the console going to sleep (possibly triggered by hdmi cec functionality via TV) while if it's closing completely it's likely a crash of Chiaki4deck etc. in which case it'd be helpful to reproduce this under gdb and get a backtrace

**Comment by iTsMute** [comment]
> Do you have a log from when this happens on Linux (I've noticed the windows logs are not complete compared to the Linux version)? ... if it's closing out to the menu there is likely something causing it to close such as the console going to sleep (possibly triggered by hdmi cec functionality via TV) while if it's closing completely it's likely a crash of Chiaki4deck etc. in which case it'd be helpful to reproduce this under gdb and get a backtrace to figure out what's triggering it

I have been unsuccessful at reproducing this issue and have not been able to get logs 😕
