### ISSUE TITLE
Failed to Parse Host Address

### ISSUE THREAD

**Issue by edeesis** [streetpea/chiaki4deck#255]
**Describe the bug**
I've had to unregister and re-register my PS5 a few times after updating to the latest version.

After initial registration, it works fine, and connects, but if I put it in sleep mode, after that it won't be able to wake up, and the address field is empty.

**Debug Log**
[chiaki_session_2024-02-19_10-55-25-061061.log](https://github.com/streetpea/chiaki4deck/files/14336018/chiaki_session_2024-02-19_10-55-25-061061.log)
[chiaki_session_2024-02-19_10-43-43-166166.log](https://github.com/streetpea/chiaki4deck/files/14336020/chiaki_session_2024-02-19_10-43-43-166166.log)
[chiaki_session_2024-02-19_10-41-41-704704.log](https://github.com/streetpea/chiaki4deck/files/14336021/chiaki_session_2024-02-19_10-41-41-704704.log)

**To Reproduce**
1. Register a console
2. Put console to sleep
3. Open Chiaki 
4. Select console, noting that the address field is empty
5. See error

**Expected behavior**
The registered console should have an address, and selecting it should connect.

**Screenshots**

![image](https://github.com/streetpea/chiaki4deck/assets/1738038/71ec9046-d862-4ee9-8b05-e9a1dcf1a0eb)

![image](https://github.com/streetpea/chiaki4deck/assets/1738038/28c434ac-b332-4355-ac1d-469092c781a7)

![image](https://github.com/streetpea/chiaki4deck/assets/1738038/23852b43-0f1c-4acd-bc20-e994e9d30589)

**Desktop (please complete the following information):**
 - OS: Steamdeck 
 - Version 3.5.7, build 20231122.1
 - Device Steam Deck
 - Chiaki4deck Version 1.6.3

**Comment by streetpea** [comment]
Fixed in 197624e97b6f3d583da988539bd8ce1bd9b94805

**Comment by niklasalkin** [comment]
I'm on 1.6.5 and getting this.

**Comment by streetpea** [comment]
@niklasalkin did you recently set up your connection or did you do so before 1.6.5 … also can you take a screenshot of your main menu with your consoles?

**Comment by dk-mushiyoke** [comment]
same deal, 1.6.5 fresh installed on an opensuse machine, manually added my ps5, entered the console ip address but showed up as empty address

![image](https://github.com/streetpea/chiaki4deck/assets/10867172/eb1f8171-d909-4b07-8f96-1f997416cb9b)

**Comment by streetpea** [comment]
@niklasalkin @dk-mushiyoke from the screenshot shared it looks different than this issue as you just have one registration not a duplicate one. Can you open a new issue for this please?

**Comment by dk-mushiyoke** [comment]
will do, thanks @streetpea
