### ISSUE TITLE
Variable zoom

### ISSUE THREAD

**Issue by mandiller** [streetpea/chiaki4deck#262]
Please consider adding a variable zoom option for the screen on Steam Deck.
At the moment, you can only toggle one zoom level, which fills the whole Steam Deck screen, at the expense of chopping off the sides of the stream.
If you allow the user to adjust how much zoom there is, then the user can decide how much of the screen of the side of the stream to lose and how much to increase the height by.
The xbox remote play/cloud app XBPlay has a zoom option the user can set on the Steam Deck. It's just a slider going from 1.0x to higher. A stream zoom of 1.05-1.10 seems to be quite good to make the screen just a bit more full screen for the Deck's 16:10 screen without losing too much at the sides. A similar slider option for Chiaki4Deck would be amazing.

**Comment by weakvar** [comment]
It would be also great to have 2 scaling options: scale to fill and scale to fit.

**Comment by weakvar** [comment]
@streetpea can you please give me some advice: I'd like to contribute, do you have an instruction how to build and run chiaki4deck on deck or macOS? I'll try to implement some feature requests.

**Comment by streetpea** [comment]
Steam Deck: https://streetpea.github.io/chiaki4deck/diy/steamdeckdev/ 
Mac: https://github.com/streetpea/chiaki4deck/blob/main/.github/workflows/build-macos.yml ... you won't need to use the deploy stage if you just run locally from your build dir.
