### ISSUE TITLE
[BUG] Application crashes on startup (SD OLED)

### ISSUE THREAD

**Issue by andreylugovtsov** [streetpea/chiaki4deck#263]
Hi!
I haver an oled model with the latest software updates available at the moment.
I've installed chiaki4deck via desktop's Store application.
It's crashing on launch. Icon would shortly show up in the taskbar and then disappear.
When `flatpak run --env=QT_DEBUG_PLUGINS=1 io.github.streetpea.Chiaki4deck` is executed, there is a normal prompt to determine PSN account id.
Meanwhile chiacki runs fine.
Tried a solution from https://github.com/streetpea/chiaki4deck/issues/112 `sudo flatpak override --nosocket=fallback-x11 --socket=x11 io.github.streetpea.Chiaki4deck`, but it didn't help.
Also tried reinstalling/rebooting - no luck.

**Comment by brucetony** [comment]
Same error occurring for me, here is the output of running `flatpak run io.github.streetpea.Chiaki4deck`:
```bash
(deck@steamdeck ~)$ flatpak run io.github.streetpea.Chiaki4deck > ~/tmp/chiaki_error.txt
F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"
chiaki.gui: [libplacebo] Initialized libplacebo v7.342.0 (API v342)
chiaki.gui: [libplacebo] Spent 47.890 ms enumerating instance extensions
chiaki.gui: [libplacebo] Creating vulkan instance with extensions:
chiaki.gui: [libplacebo]     VK_KHR_get_physical_device_properties2
chiaki.gui: [libplacebo]     VK_KHR_surface
chiaki.gui: [libplacebo]     VK_EXT_swapchain_colorspace
chiaki.gui: [libplacebo]     VK_KHR_external_memory_capabilities
chiaki.gui: [libplacebo]     VK_KHR_external_semaphore_capabilities
chiaki.gui: [libplacebo]     VK_KHR_get_surface_capabilities2
chiaki.gui: [libplacebo]     VK_KHR_portability_enumeration
chiaki.gui: [libplacebo]     VK_KHR_xcb_surface
chiaki.gui: [libplacebo]     VK_KHR_surface
chiaki.gui: [libplacebo] Probing for vulkan devices:
chiaki.gui: [libplacebo]     GPU 0: AMD Radeon Graphics (RADV VANGOGH) v1.3.274 (integrated)
chiaki.gui: [libplacebo]            uuid: 00:00:00:00:04:00:00:00:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]     GPU 1: llvmpipe (LLVM 17.0.6, 256 bits) v1.3.274 (software)
chiaki.gui: [libplacebo]            uuid: 6D:65:73:61:32:34:2E:30:2E:31:00:00:00:00:00:00
chiaki.gui: [libplacebo] Vulkan device properties:
chiaki.gui: [libplacebo]     Device Name: AMD Radeon Graphics (RADV VANGOGH)
chiaki.gui: [libplacebo]     Device ID: 1002:1435
chiaki.gui: [libplacebo]     Device UUID: 00:00:00:00:04:00:00:00:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]     Driver version: 6000001
chiaki.gui: [libplacebo]     API version: 1.3.274
chiaki.gui: [libplacebo] Using async transfer (queue 1)
chiaki.gui: [libplacebo] Using async compute (queue 1)
chiaki.gui: [libplacebo] Creating vulkan device with extensions:
chiaki.gui: [libplacebo]     VK_KHR_swapchain
chiaki.gui: [libplacebo]     VK_KHR_push_descriptor
chiaki.gui: [libplacebo]     VK_KHR_external_memory_fd
chiaki.gui: [libplacebo]     VK_EXT_external_memory_dma_buf
chiaki.gui: [libplacebo]     VK_EXT_external_memory_host
chiaki.gui: [libplacebo]     VK_KHR_external_semaphore_fd
chiaki.gui: [libplacebo]     VK_EXT_pci_bus_info
chiaki.gui: [libplacebo]     VK_EXT_image_drm_format_modifier
chiaki.gui: [libplacebo]     VK_KHR_video_queue
chiaki.gui: [libplacebo]     VK_KHR_video_decode_queue
chiaki.gui: [libplacebo]     VK_KHR_video_decode_h264
chiaki.gui: [libplacebo]     VK_KHR_video_decode_h265
chiaki.gui: [libplacebo] Spent 13.797 ms creating vulkan device
chiaki.gui: [libplacebo] Memory heaps supported by device:
chiaki.gui: [libplacebo]     0: flags 0x0 size 3050M
chiaki.gui: [libplacebo]     1: flags 0x1 size 6101M
chiaki.gui: [libplacebo] Memory summary:     0 used     0 res     0 alloc, efficiency 100.00%, utilization 100.00%, max page:  381M
chiaki.gui: [libplacebo] shaderc SPIR-V version 1.6 rev 1
chiaki.gui: [libplacebo] Initialized SPIR-V compiler 'shaderc'
chiaki.gui: [libplacebo] GPU information:
chiaki.gui: [libplacebo]     GLSL version: 450 (vulkan)
chiaki.gui: [libplacebo]       max_shmem_size:            65536
chiaki.gui: [libplacebo]       max_group_threads:         1024
chiaki.gui: [libplacebo]       max_group_size[0]:         1024
chiaki.gui: [libplacebo]       max_group_size[1]:         1024
chiaki.gui: [libplacebo]       max_group_size[2]:         1024
chiaki.gui: [libplacebo]       subgroup_size:             64
chiaki.gui: [libplacebo]       min_gather_offset:         -32
chiaki.gui: [libplacebo]       max_gather_offset:         31
chiaki.gui: [libplacebo]     Limits:
chiaki.gui: [libplacebo]       thread_safe:               1
chiaki.gui: [libplacebo]       callbacks:                 1
chiaki.gui: [libplacebo]       max_buf_size:              6397714432
chiaki.gui: [libplacebo]       max_ubo_size:              4294967295
chiaki.gui: [libplacebo]       max_ssbo_size:             4294967295
chiaki.gui: [libplacebo]       max_vbo_size:              6397714432
chiaki.gui: [libplacebo]       max_mapped_size:           6397714432
chiaki.gui: [libplacebo]       max_buffer_texels:         4294967295
chiaki.gui: [libplacebo]       align_host_ptr:            4096
chiaki.gui: [libplacebo]       host_cached:               1
chiaki.gui: [libplacebo]       max_tex_1d_dim:            16384
chiaki.gui: [libplacebo]       max_tex_2d_dim:            16384
chiaki.gui: [libplacebo]       max_tex_3d_dim:            2048
chiaki.gui: [libplacebo]       blittable_1d_3d:           1
chiaki.gui: [libplacebo]       buf_transfer:              1
chiaki.gui: [libplacebo]       align_tex_xfer_pitch:      1
chiaki.gui: [libplacebo]       align_tex_xfer_offset:     4
chiaki.gui: [libplacebo]       max_variable_comps:        0
chiaki.gui: [libplacebo]       max_constants:             18446744073709551615
chiaki.gui: [libplacebo]       max_pushc_size:            256
chiaki.gui: [libplacebo]       align_vertex_stride:       1
chiaki.gui: [libplacebo]       max_dispatch[0]:           65535
chiaki.gui: [libplacebo]       max_dispatch[1]:           65535
chiaki.gui: [libplacebo]       max_dispatch[2]:           65535
chiaki.gui: [libplacebo]       fragment_queues:           1
chiaki.gui: [libplacebo]       compute_queues:            1
chiaki.gui: [libplacebo]     External API interop:
chiaki.gui: [libplacebo]       UUID: 00:00:00:00:04:00:00:00:00:00:00:00:00:00:00:00
chiaki.gui: [libplacebo]       PCI: 0000:04:00:0
chiaki.gui: [libplacebo]       buf export caps: 0x9
chiaki.gui: [libplacebo]       buf import caps: 0x19
chiaki.gui: [libplacebo]       tex export caps: 0x9
chiaki.gui: [libplacebo]       tex import caps: 0x19
chiaki.gui: [libplacebo]       sync export caps: 0x1
chiaki.gui: [libplacebo]       sync import caps: 0x0
chiaki.gui: Component not ready
 QList(qrc:/Main.qml:171:9: Type ManualHostDialog unavailable
            ManualHostDialog { }
            ^, qrc:/ManualHostDialog.qml:9:1: Type DialogView unavailable
    DialogView {
    ^, qrc:/DialogView.qml:72:17: Non-existent attached object
                    Material.roundedScale: Material.SmallScale
                    ^)
```

**Comment by MatthiasMose** [comment]
My log looks similar. I'm using the lcd steam deck.

**Comment by Golden-z** [comment]
I don't know much about this particular language but from what I can tell it looks like it's having trouble loading assets for the GUI. Possibly specifically because it's importing an older version of QtQuick.Controls as it doesn't define a version number.

![image](https://github.com/streetpea/chiaki4deck/assets/162030611/e5cb794d-e3ed-4276-b876-fc55056069e8)

The error indicates it must be importing a version older than 6.5 when the button rounding (material.roundedscale) feature was added.

Non-existent attached object
                    Material.roundedScale: Material.SmallScale
                    
Theoretically I think that using import QtQuick.Controls 6.6.2 would correct this issue but I'm not familiar enough with github and linux to test this.

**Comment by devusb** [comment]
https://github.com/streetpea/chiaki4deck/pull/261 this solved the same error for me.

**Comment by MrNerdly** [comment]
Hi, I'm pretty new with my  steamdeck, how do I impliment the changes listed in #261?

**Comment by jz5678910** [comment]
Fresh install of Chiaki4Deck also crashing here upon launch. LCD model. No error or window of any kind. Icon opens in the task bar and spins for a few seconds and then stops and disappears.

**Comment by simoalx** [comment]
Are you going to do a release so we can get the update through Flatpack?

**Comment by brucetony** [comment]
Hold tight all, the maintainer needs time to check the suggested changes, test the, and release a new version. You can compile the suggested changes yourself and install, otherwise you'll have to wait a bit for an official patch to be released

**Comment by streetpea** [comment]
so checking into this an update in the base layer `org.kde.Platform//6.6` yesterday caused this ... you can fix this locally running 
```sudo flatpak upgrade org.kde.Platform//6.6 --commit a7443e846cf67d007fcecda5c9dc27844001cfb8929064395cfc25c6d71d9474```

while waiting for an update that works with the latest version of the platform layer or alternatively use the appimage

**Comment by jz5678910** [comment]
> so checking into this an update in the base layer `org.kde.Platform//6.6` yesterday caused this ... you can fix this locally running `sudo flatpak upgrade org.kde.Platform//6.6 --commit a7443e846cf67d007fcecda5c9dc27844001cfb8929064395cfc25c6d71d9474`
> 
> while waiting for an update that works with the latest version of the platform layer or alternatively use the appimage

This works, but just a PSA, after running this there will be an update listed on the discover store, running it will break chiaki again.

**Comment by streetpea** [comment]
@jz5678910 if you want to prevent this you can temporarily mask updates to the kde platform with ```flatpak mask org.kde.Platform//6.6 ``

**Comment by simoalx** [comment]
> so checking into this an update in the base layer `org.kde.Platform//6.6` yesterday caused this ... you can fix this locally running `sudo flatpak upgrade org.kde.Platform//6.6 --commit a7443e846cf67d007fcecda5c9dc27844001cfb8929064395cfc25c6d71d9474`
> 
> while waiting for an update that works with the latest version of the platform layer or alternatively use the appimage

This isn't working for me sadly, still getting the same error after running this (and the command worked, I can see the update pending in Discover)
