### ISSUE TITLE
[BUG] Can't Connect To PS5

### ISSUE THREAD

**Issue by dmandrone** [streetpea/chiaki4deck#265]
**Describe the bug**
Since updating to the latest version, Chiaki4Deck is not allowing me to connect to my console / fully add it to the application. My console is already registered within the app and can confirm that it automatically detects it on the local network when not connected to Tailscale. When connected to Tailscale, it's no longer present and going through the registration process does not work. When registering, it will provide the log box/pop-up showing that it's registering/connecting fine but it will redirect to the main page of the app and all of the respective information just entered will be gone and it will only show the IP address. When clicking on the console, all information is forced to be re-entered again, looping over and over as you try the process again.

I previously had no issues whatsoever connecting with the previous version of Chiaki4Deck. Additionally, as a control of some sort, I used the original Chiaki app to see if it was isolated to 4Deck, and can confirm I was able to register and connect to my console without issue on Chiaki. Not sure what changed in 4Deck in the latest update causing this to occur.

Screenshot of the connection log box below (physical picture from a video I took of the Deck).

**Debug Log**
Verbose logging enabled, but no log is being generated within the log folder. Assuming because no connection is actually being truly made?

**To Reproduce**
1. Connect to Tailscale
2. Open Chiaki4Deck -> Add New Console
3. Once all info is entered, click 'Register' to finalize adding/connect to Console
4. See error / lack of information

**Expected behavior**
I expect that the console would be present in the list already as it's listed within the registered consoles || And/or when manually registering/adding the console again, it would actually keep the information and allow me to connect.

**Screenshots**
![Screenshot_20240305_102155_Studio](https://github.com/streetpea/chiaki4deck/assets/19500231/d30045a0-f505-4242-80fb-162e0b927b64)

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version 3.5.17
 - Device Steam Deck
 - Chiaki4deck Version 1.6.3

**Comment by dmandrone** [comment]
The process from the picture above is me going through the process of adding a manual registration.

It hasn't appeared in the registered console drop down since the latest update for me.

**Comment by Destreyf** [comment]
Just wanted to chime in here, I am experiencing a similar issue, however I am trying to play remote. 

I have the ports forwarded, and it'll work fine when I am on my local network, but I just get a blank screen with no items whenever I am on a different network even after adding a manual connection pointed to my ip address.

Setting up the automatic connect just results in a spinning waiting for console message.

I have many other services forwarded to my house so I am fairly confident I have the port forwarding setup correctly.

**Comment by jbaiter** [comment]
@Destreyf 

> even after adding a manual connection pointed to my ip address.

This would be the *external* IP address of your internet connection, correct?

> I have many other services forwarded to my house so I am fairly confident I have the port forwarding setup correctly.

Did you forward UDP as described in https://streetpea.github.io/chiaki4deck/setup/remoteconnection/#port-forwarding? Most other services use TCP.

**Comment by Destreyf** [comment]
> @Destreyf
> 
> > even after adding a manual connection pointed to my ip address.
> 
> This would be the _external_ IP address of your internet connection, correct?
> 
> > I have many other services forwarded to my house so I am fairly confident I have the port forwarding setup correctly.
> 
> Did you forward UDP as described in https://streetpea.github.io/chiaki4deck/setup/remoteconnection/#port-forwarding? Most other services use TCP.

Yes, external ip, I even tried it with my dynamic dns hostname. And tried it against both of my Internet providers as I have a dual wan setup at home.

**Comment by JimmyJMA** [comment]
I reproduce this issue.

I can register PS5 in local network, but with external IP process is sucessfull but PS5 is not registered.
My port is setup correctly because with original version of chiaki, i can connect to my PS5 with external IP.

**Comment by streetpea** [comment]
I'm able to reproduce, the console is registering successfully but that manual console entry isn't being updated to reflect that the console is registered. It should be a relatively easy fix when I get a chance to look at it. For now a workaround is if you add the manual console when connected to the local network the console should show up to choose from in the dropdown instead of register on first connection. If you choose this, the manual console will start registered so you won't run into this issue and it will work.

**Comment by JimmyJMA** [comment]
Thanks for the tip, it work

**Comment by Destreyf** [comment]
> I'm able to reproduce, the console is registering successfully but that manual console entry isn't being updated to reflect that the console is registered. It should be a relatively easy fix when I get a chance to look at it. For now a workaround is if you add the manual console when connected to the local network the console should show up to choose from in the dropdown instead of register on first connection. If you choose this, the manual console will start registered so you won't run into this issue and it will work.

Sadly this isn't the case for me, it showed up fine on my local network and when adding the manual entry as described, but as soon as I switch to my hotspot both console items disappear.

I left my deck at work, but I'm going to try to resetting the configuration entirely and redoing the pairing process.

**Comment by dmandrone** [comment]
> > I'm able to reproduce, the console is registering successfully but that manual console entry isn't being updated to reflect that the console is registered. It should be a relatively easy fix when I get a chance to look at it. For now a workaround is if you add the manual console when connected to the local network the console should show up to choose from in the dropdown instead of register on first connection. If you choose this, the manual console will start registered so you won't run into this issue and it will work.
> 
> Sadly this isn't the case for me, it showed up fine on my local network and when adding the manual entry as described, but as soon as I switch to my hotspot both console items disappear.
> 
> I left my deck at work, but I'm going to try to resetting the configuration entirely and redoing the pairing process.

+1 to this scenario

**Comment by streetpea** [comment]
Can you share screenshots of what you see when you create the registered manual connection when on same WiFi and different WiFi.

**Comment by Zac-DAgostino** [comment]
I have this same problem. I managed to record the behaviour. In the vid my deck is on my phone hotspot instead of the wifi. Tailscale is installed on the phone and on my pc which is routing traffic to the ps5. 

I confirmed I was able to run ‘tailscale ping’ to get a pong back from the ps5 before trying. 

https://github.com/streetpea/chiaki4deck/assets/63575335/50a1e258-722d-47da-9584-68bae24d59f0

**Comment by Kamron92** [comment]
> I have this same problem. I managed to record the behaviour. In the vid my deck is on my phone hotspot instead of the wifi. Tailscale is installed on the phone and on my pc which is routing traffic to the ps5.
> 
> I confirmed I was able to run ‘tailscale ping’ to get a pong back from the ps5 before trying.
> 
> I can set it up manually on the same network but when I am on a different network the registered ps5 doesn’t appear in the dropdown unfortunately.
> 
>  IMG_1598.mov

I also have same problem. Don't know what to do. Last week everything was perfect, but from yesterday something went wrong when I decided to reinstall chiaki4deck

**Comment by chuck-alt-delete** [comment]
I want to also add that yesterday everything was working great but today I saw a spinning red circle when connecting to my registered PlayStation 5. I unregistered and went to register and see
`Regist timed out waiting for search response`

My ps5 is still automatically discovered, but I can’t connect.

The only thing I can think is there was a system update on ps5.

I downloaded the remote play app on iOS and actually couldn’t connect. I restarted my ps5 and then could connect, but Chiaki still can’t connect.

**Comment by chuck-alt-delete** [comment]
Update: I attempted to connect manually over cellular on my Tailscale vpn (it was not automatically discovered, which was different when I successfully tested it yesterday). I did not get the same search timeout. I got the same behavior a previous poster mentioned where it seemed successful but then did not start streaming.
