### ISSUE TITLE
[BUG] vulkan hardware decoder not working

### ISSUE THREAD

**Issue by IWasAMistake0** [streetpea/chiaki4deck#269]
Downloaded Chiaki4deck for Windows on the Legion Go. Can't use Vulkan hardware decoder. When I select it and start the ps5 I can hear it but I just have a black screen. Ive changed the nitrate from 800- 10000 up to 30000 and have no fixes. On regular chiaki if I select d3d11va or dxva2 I get an error saying hardware encoder failed. I don't know if the 2 are connected or not that's why I'm mentioning it. Anyone know a fix?

**Comment by streetpea** [comment]
Can you please post a log of a session where this happens?
