### ISSUE TITLE
Wireless dualsense haptics?

### ISSUE THREAD

**Issue by lyndonguitar** [streetpea/chiaki4deck#271]
is this feature possible? or is using USB-cable for Dualsense still the norm?

Sorry for creating an issue/entry. Just wanted to ask a question and i dont know where else to ask it

**Comment by streetpea** [comment]
It’s not possible. The audio device used for the haptics isn’t available via Bluetooth.

**Comment by jbaiter** [comment]
It technically is available via Bluetooth, but I think it uses a custom protocol on top of that and not one of the standard ones for audio.

I'm not aware of anyone having done the neccessary reverse engineering work to learn how to get audio (and thus haptics) working wirelessly.

There were some initial attempts in 2020, but I don't think much has come of it until today:
https://github.com/Ohjurot/DualSense-Windows/issues/7
