### ISSUE TITLE
[BUG] issue with performance , rectified after restart of steam deck oled

### ISSUE THREAD

**Issue by hasskhan** [streetpea/chiaki4deck#272]
**Describe the bug**
So chaiki4deck 1.63 runs flawlessly for first few minutes and then suddenly it would have frame rates between 45 -55 . It also highlights connection issue though I have a very high speed internet / wifi / Ethernet . This gets fixed once I restart my deck . It wasnt happening before the recent update . 

**Debug Log**
Please attach a log with verbose logging enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. SteamOS]
 - Device [e.g. Steam Deck]
 - Chiaki4deck Version [e.g. 1.6.2]

**Additional context**

**Comment by hasskhan** [comment]
https://github.com/streetpea/chiaki4deck/assets/65784227/e9f54f4b-0943-49e0-91d2-e78ac4c92696

OS: [e.g. SteamOS] steamos
Version [e.g. 22] 3.5.17
Device [e.g. Steam Deck]. Steam deck 
Chiaki4deck Version [e.g. 1.6.2]. 1.6.3

**Comment by EternisRequiem** [comment]
This is also happening with me (On both the old re.Chiaki4Deck and io.chiaki4deck, but older version seems worse).  I've got an OLED on current beta release (3.5.17)

I can go sometimes 30-40 minutes but as soon as I start getting any sort of packet loss/stuttering, it spirals and no amount of time will it get back up to 30/60 fps, I have to restart.  Sometimes (rarely) restarting Chiaki4deck will give me another few minutes, but it begins to happen once again and only resolves on a full SteamDeck reboot.

**Comment by hasskhan** [comment]
Completely agree and I have the oled . Though it works fine on the portal but on deck once the fluctuation starts it just gets worse .

**Comment by streetpea** [comment]
Based on the

**Comment by hasskhan** [comment]
Thank you so much and you are absolutely spot on . I tried the fix from  crypbyte33 and it completely fixed the issue . Leaving the link for others https://steamdeckhq.com/news/cryobyte33-fix-wi-fi-on-your-steam-deck-oled/
