### ISSUE TITLE
[BUG] Overwhelming trackpad haptics in some games

### ISSUE THREAD

**Issue by prajwalkman** [streetpea/chiaki4deck#273]
**Describe the bug**
When playing Jedi Survivor, the trackpads keep rumbling whenever I attack. It's also very noisy, seems like it's not respecting the rumble intensity set in the settings. I want to be able to disable vibration for chiaki on the deck's side, but steam controller settings expose no such option. The only other way is the global settings in steam quick settings, but even they don't seem to work. It would be best to expose an option in Chiaki to ignore or block rumble data.

This is on OLED.

**Comment by prajwalkman** [comment]
I don't see "DualSense Emulation" in the Settings. Do you mean "PS5 features"? But that would disable HDR too right?

**Comment by streetpea** [comment]
PS5 features is just haptics and adaptive triggers on ps5, haptics on steam deck or rumble translated from haptics on controllers without haptics. The Steam Decks haptics are noisy which is probably what you are experiencing... you can also hear them when the system is turning on.

**Comment by prajwalkman** [comment]
Thank you, I disabled it and all good now.
