### ISSUE TITLE
[BUG] Can't find "chiaki4deck+ mic" by "gmoney23" layout anywhere

### ISSUE THREAD

**Issue by urbanracer34** [streetpea/chiaki4deck#276]
I installed chiaki4deck on my Steam Deck following up to https://streetpea.github.io/chiaki4deck/setup/controlling/ and I cannot find the "chiaki4deck+ mic" by "gmoney23" layout anywhere.

I can confirm the name of the application in steam is correct. I can connect to my PS5 just fine but the button layout is out to lunch.

Where do I go from here?

**Comment by niklasalkin** [comment]
Just want to second this. Been setting it up today and have to rely on users templates

**Comment by streetpea** [comment]
You can now use the add steam shortcut option to automatically add this now on Steam Deck as of the latest release. Note: If you are using flatpak please wait for version 1.6.4 to become available (might take a few hours)

**Comment by urbanracer34** [comment]
Will we have to delete and readd the shortcut to steam in order for it to work? Or will it be automatic?

**Comment by streetpea** [comment]
You can use a new name to create a new shortcut or the existing name to update the shortcut

**Comment by urbanracer34** [comment]
Thank you.

**Comment by urbanracer34** [comment]
Will the guide be updated as well?

**Comment by streetpea** [comment]
See automated process for auto-connect or standard launch tab here https://streetpea.github.io/chiaki4deck/setup/steaming/
