### ISSUE TITLE
Modify the game rumble intensity

### ISSUE THREAD

**Issue by pelle1101** [streetpea/chiaki4deck#278]
I currently have the 512GB OLED model.

It would be nice (if it's not already available) to have an option to modify the intensity of the game rumble. When I am in game, the game rumble is maxed out causing noise.

**Comment by andrewcharlton87** [comment]
Totally second this one, it's pretty much the only remaining flaw after the recent overhaul of c4d. The haptics are just annoyingly loud. 

There is also an issue where if you have an external pad, the vibration still goes through steam deck itself. Not sure if this is chiaki or steam related.

**Comment by streetpea** [comment]
Unfortunately, the only way to make the noise quieter is to adjust the setting on the deck. Otherwise, the haptics are just that loud (you can also hear them during startup). Another option would to be to use rumble instead of haptics which would be less/not noisy for worse quality. Would you like that option @andrewcharlton87 @pelle1101?

**Comment by andrewcharlton87** [comment]
> Unfortunately, the only way to make the noise quieter is to adjust the setting on the deck. Otherwise, the haptics are just that loud (you can also hear them during startup). Another option would to be to use rumble instead of haptics which would be less/not noisy for worse quality. Would you like that option @andrewcharlton87 @pelle1101?

Thanks for the quick reply; I think it would be great to have an optional setting for that, if it's not too much to ask. Especially if I'm playing while my partner/children are sleeping it would be nice to have a quieter option that still allows some feedback. 

Awesome work so far!

**Comment by pelle1101** [comment]
> Unfortunately, the only way to make the noise quieter is to adjust the setting on the deck. Otherwise, the haptics are just that loud (you can also hear them during startup). Another option would to be to use rumble instead of haptics which would be less/not noisy for worse quality. Would you like that option @andrewcharlton87 @pelle1101?

I have adjusted the haptic feedback within the SD settings to a 1, but this had no effect in c4d. Unless there is a way for c4d to apply the SD haptic settings, having the option to use rumble instead of haptic would be nice to have.

Thank you for your work on this!

**Comment by streetpea** [comment]
quieter haptics for steam deck made the default by a2c2657dbea6d7733f35a8ff18d16a4dc21a40c0
