### ISSUE TITLE
Adding a "Restore to Default" for keys setup

### ISSUE THREAD

**Issue by tyloopanda** [streetpea/chiaki4deck#279]
So I installed Chiaki4deck on my SD, latency and buttons all works really well, except for one part where games like Elden Ring I cannot open the maps.

As I was doodling around the keys setup page, I changed PS button from "ESC" to another button, and realize I cannot change it back to "ESC" because SD literally doesn't have that button. If I want to change the PS key back to default, I would either have to grab an external keyboard and connect to my SD, or re-install Chiaki4deck again (and then re-pair my PS5)

Please I beg, add a "Restore Default" to keys page, for ppl who have messed up the original keys setup.

**Comment by streetpea** [comment]
Can’t you bring up the virtual keyboard with Steam + x and then hit esc on there?

**Comment by tyloopanda** [comment]
That's exactly the tricky part, as you can see the virtual keyboard doesn't have a "ESC" button.
![steam-deck-virtual-keyboard-1](https://github.com/streetpea/chiaki4deck/assets/105297101/a488c27d-5734-4336-9e78-4028c1b7d4dd)

in order to press "ESC", I would have to press the Steam button and left on the d-pad. but that would close the whole key binding page

**Comment by streetpea** [comment]
There was an issue with escape key closing the dialog instead of being set, that is now fixed in main

**Comment by InigoSJ** [comment]
Could this be reopened? I have messed with the  mapping and I want to go back to default so that I can use Steam community layouts. Adding the button won't hurt and it will definitely help people
