### ISSUE TITLE
Borealis GUI?

### ISSUE THREAD

**Issue by jbaiter** [streetpea/chiaki4deck#28]
Chiaki on Switch uses a more handheld-friendly gui implemented with [borealis](https://github.com/natinusala/borealis). The library supports both Switch and PC platforms.
The implementation in the [`switch` subdirectory](https://github.com/streetpea/chiaki4deck/tree/main/switch) is not specifically tied to the Switch either, some code is cleary tailored to the Switch's specifics, but most of it is cleanly separated with a `__SWITCH__` prepocessor flag, so making it work on the Deck shouldn't be too hard, I think.

A big advantage of this UI over the current Qt GUI on the Deck would be that changing settings from game mode would be a lot less cumbersome, and we could even implement something like switching bitrate/resolution/fps on the fly via an onscreen-menu (which would restart the session in the background), in cases where the connection is bad and users want to override the default.

Here's a video of the Boreali GUI in action on the switch:
https://www.youtube.com/watch?v=n57Y4GgwrSY

**Comment by streetpea** [comment]
That does seem nice in general. Can you navigate it with a controller? I’m seeing if implementing this would also solve #4

**Comment by jbaiter** [comment]
Yes, that should solve that issue, Borealis supports both gamepad and touch input 👍🏾 
I've managed to compile it on my Linux laptop last night, runs fine there, will test how it works on the Deck next week :-)

**Comment by szszoke** [comment]
> Here's a video of the Boreali GUI in action on the switch:
> https://www.youtube.com/watch?v=n57Y4GgwrSY

It looks like the video is not available anymore.  Regardless, it would be great to have a GUI that works well with controllers.

**Comment by perroboc** [comment]
mmm I've been meaning to give it a go to update de UI in Chiaki4deck using QT or QML. I reviewed borealis, and it seems it's been abandoned (https://github.com/natinusala/borealis/branches/active shows no active branches, last update was on 2021-04-05).

I don't promise anything, though!

**Comment by streetpea** [comment]
Not sure if this still makes sense with the new Gui

**Comment by jbaiter** [comment]
No it doesn't :-D
