### ISSUE TITLE
[BUG] Chiaki.exe throws errors upon launch (1.6.4)

### ISSUE THREAD

**Issue by dkflint723** [streetpea/chiaki4deck#281]
**Describe the bug**
Unable to run the latest version 1.6.4. 

**To Reproduce**
Upon trying to launch the latest version of chiaki I get errors saying libzvi-0.dll, libjxl.dll, and libjxl_threads.dll are missing.

**Expected behavior**
The program should launch.

**Screenshots**
![image](https://github.com/streetpea/chiaki4deck/assets/5694781/c27cb9bb-13bf-49e0-bc0b-65dc7ac9095a)
![image](https://github.com/streetpea/chiaki4deck/assets/5694781/548b9307-84d8-48c8-ae89-af2c7eab67fe)
![image](https://github.com/streetpea/chiaki4deck/assets/5694781/2aa59e03-350b-45a8-a419-c61f7c6c6afa)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2 22631.3296
 - Device Desktop PC
 - Chiaki4deck Version 1.6.4

**Comment by streetpea** [comment]
fixed and uploaded new msys2 build
