### ISSUE TITLE
[BUG] Rumble/Haptics of DualSense not working on PS5 games on MacOS

### ISSUE THREAD

**Issue by agonzalezramos** [streetpea/chiaki4deck#283]
**Describe the bug**
As title says, Rumble/Haptics not working on PS5 games on MacOS. I've tried many versions and I cannot find a way to solve it out. Rumble works on PS4 games and also Adaptive Triggers on PS5.  Worth to mention that I tried also the windows version, and it that case the rumble works.

**Desktop (please complete the following information):**
 - OS:  MacOS
 - Version: 13.6.5
 - Device Macbook Air M1 and iMac intel 2020
 - Chiaki4deck Version  1.6.4

thanks!

**Comment by streetpea** [comment]
I tested this out and the haptics audio is playing to the core audio driver but nothing is produced. Since there is no other SDL audio driver for Mac I'm not sure of how to fix this. In the meantime, I enabled the haptic rumble for MacOS using the DualSense.

**Comment by agonzalezramos** [comment]
Hi streatpea, sorry, but I didn't understand. At the beginning of your message, I get that you don't know how to fix it, but in the final sentence, you end up enabling it? This would appear on the next 1.6.5?

By the way, this user fixed it https://www.reddit.com/r/remoteplay/comments/10ub0vu/chiaki_with_qt6_adaptive_triggershaptics_supports/, but the video is not as smooth as yours one. Probably because in his version forces to use a decoder that in your version is not necessary (always talking about MacOS). Maybe it helps.

**Comment by streetpea** [comment]
Do you have emulated rumble checked in your settings for that build?

**Comment by streetpea** [comment]
@agonzalezramos you can try the haptic rumble in this build from the main branch https://github.com/streetpea/chiaki4deck/actions/runs/8336435603/artifacts/1337357074

**Comment by agonzalezramos** [comment]
@streetpea, yes! now it works! Is there any chance to be stronger? thanks for the quick answer!!
