### ISSUE TITLE
(Windows) Portable option

### ISSUE THREAD

**Issue by Rahzadan** [streetpea/chiaki4deck#284]
Would it be possible to add an option allow all configs/logs/console registrations to reside inside the Chiaki4Deck folder? In addition, I tried looking for the config on my PC, but all I found were caches and logs in **C:\Users\<user>\\AppData\Roaming\Chiaki\Chiaki** and **C:\Users\<user>\\AppData\Local\Chiaki\Chiaki** - where does Chiaki4deck for windows store the configs?

**Comment by streetpea** [comment]
On Windows the configs are stored like other windows configs in the Windows registry

**Comment by Rahzadan** [comment]
Could a portable version be made, where the configs/logins/pins/console registrations are stored in a json (or something) inside the application folder instead? A few apps accomplish this by creating a blank "portable.txt" file in the application root, or a specifically-named folder where the portable contents will automatically go (if folder exists). I frequently freshly reinstall my OS, and portable apps mean that I can put these apps on a separate drive and they work just as before on a new machine.
