### ISSUE TITLE
[BUG] Cannot access PS5 while Steam Deck is on VPN

### ISSUE THREAD

**Issue by Cook13s7777** [streetpea/chiaki4deck#286]
**Describe the bug**
At home, Steam Deck can connect via Wi-Fi or Ethernet to my PS5. I can connect to PS5 remotely (without VPN), using port forwarding (I would prefer not to use Port Forwarding as I get a lot of snoop attempts). However, I cannot connect to it in game mode (spinning circle then Chiaki4deck quits) with automation. PS5 does not appear as discoverable (if I use hostname or IP). If I attempt to manually register it, it will not register with an error that regist does not receive a response. I think I can identify this part as what seems to be that the PS5 sends out an invalid response packet, I do have logs for this. I wonder if Chiaki is not sending a established or related packet for the PS5 to establish a handshake properly. Just an fyi from a security standpoint, best practice is to drop invalid packets from entering internal LAN. I do have VLANs setup on my network, but my firewall rules are setup correctly as Moonlight works just fine with Steam Deck VPN enabled,  and I am using the exact same rules for it. I can disable RFC1918 and PS5 is still not able to register.

I seem to have the same problem as this [error](https://github.com/streetpea/chiaki4deck/issues/265) but I use unifi network devices and Wireguard for VPN.

Steam Deck with VPN connection enabled, appears with an internal IP of 192.168.X.X from my unifi console. This VLAN is allowed access to the VLAN that contains my PS5 and my PC. When at home, the Steam Deck has a different subnet but still is able to connect just fine without VPN.

Official PS App works fine with all my firewall rules enabled.

**Debug Log**
I do not have a log to provide as the error does not appear even with verbose log. I will provide a screenshot of this error later tonight.

**To Reproduce**
1. Connect to 'Wireguard VPN', connection successfully established. All home network devices are accessible.
2. Open Chiaki -> attempt to add new console
3. Manually enter information (external or internal IP), click 'Register' to add console
4. Error appears in Chiaki / no other information found (appears for both internal and external IP)

**Expected behavior**
I expect the console to show up, as it's already been registered internally. Or if manually setup, to keep the information and allow connection from either internal, external, or tunneled from external to internal connection.

**Screenshots**
These errors for invalid state only show up when I attempt to connect or register.
![image](https://github.com/streetpea/chiaki4deck/assets/111649841/2b7f2876-5122-474b-a133-8516bd482a07)
![image](https://github.com/streetpea/chiaki4deck/assets/111649841/99e2cb6b-8a21-44b5-a591-29bab25c244a)

Port forwarding should be the last resort option, you might get the attention of some bad actors. Dshield is fine here but others may take advantage.
![image](https://github.com/streetpea/chiaki4deck/assets/111649841/b609c644-575c-4b80-ad11-8c5ae70f1bdd)

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version: 3.5.17
 - Device: Steam Deck
 - Chiaki4deck Version: 1.6.4

**Additional context**

**Comment by Cook13s7777** [comment]
Looks like I was able to add it this time but trying to launch it provides me with this error.

Failed to initialize Stream Session: Chiaki Session Init failed: Failed to parse host address

I have two new Console listings with hostname of ps5, one with broadcast and one without. Neither will connect. The one with the external ip doesn’t work with VPN which makes sense but I’ll keep trying different things. This time I do not have any error logs inside my firewall but I’ll have to try again later to see if the triggers do supply something in my network logs.

**Comment by Cook13s7777** [comment]
![IMG_2878](https://github.com/streetpea/chiaki4deck/assets/111649841/d73d841f-8344-43b1-984e-795760495bbd)
![IMG_2879](https://github.com/streetpea/chiaki4deck/assets/111649841/5df45baf-ce39-47c4-b513-f5f6da96ddd5)
![IMG_2876](https://github.com/streetpea/chiaki4deck/assets/111649841/4a93fb0e-7965-45c1-9102-47ed33c844ec)
![IMG_2880](https://github.com/streetpea/chiaki4deck/assets/111649841/4310723e-5adf-43e0-a72f-2be19e4658c8)

**Comment by Cook13s7777** [comment]
OK I think I've got a workaround for this.. it's not exactly what I would like but it works.
Currently, no port forwarding involved.

So I'm using the automation script.. not sure if it's the one listed at this location: io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki-launcher.sh

Starting at line 33, I believe this is where the script, provided in the documentation, asks for you to provide an Internal IP and wifi SSID (it was set to my PS5 IP and the particular SSID at home) then the External IP which is my WAN IP. 
Success: Steam Deck is (VPN on) Internal, Port forwarding state doesn't matter
Success: Steam Deck is (VPN off) Internal, Port forwarding state doesn't matter
Success: Steam Deck (VPN off) External, PS5 Port Forwarding On
Fail: Steam Deck (VPN off) External, PS5 Port Forwarding Off // This is intended, I added it anyway for posterity
Fail: Steam Deck (VPN on) External, PS5 Port Forwarding Off
Fail: Steam Deck (VPN on) External, PS5 Port Forwarding On

So I am currently on a remote public network, no where near my home. While staring at this script I decide, to change the SSID at Line 33 to the public SSID that it's currently connected to.. and what do you know.. it works! While on VPN and port forwarding off! Is it possible to modify this block of code to check the internal IP first regardless if the first argument fails before trying the external IP? I would still like it to try to reach the external IP upon failure but getting that to work with VPN might be another process altogether or perhaps a way to utilize 'allowedIPs' in a VPN, to check internal before going external.

**Comment by 5at0ri** [comment]
ive also got this issue, could you say which script you changed, im a bit of a noob when it comes to this stuff. i set up tailscale and i know that i can receive pings from my ps5 as ive tested for it but the console doesnt show up in the chiaki app so i assume its something to do with the app. hopefully this gets fixed as i have no way to remote play outside of my network but this. on the local network it works fine and flawlessly but outside it doesnt

**Comment by Cook13s7777** [comment]
> ive also got this issue, could you say which script you changed, im a bit of a noob when it comes to this stuff. i set up tailscale and i know that i can receive pings from my ps5 as ive tested for it but the console doesnt show up in the chiaki app so i assume its something to do with the app. hopefully this gets fixed as i have no way to remote play outside of my network but this. on the local network it works fine and flawlessly but outside it doesnt.
> 
> EDIT: i have resolved this with a different solution if anyone is wondering. after some trial and error and looking at other issues, i connected to my home network, manually added my console on it, tested it and it was fine, so then i switched over to hotspot, and since its manually added it stayed showing up. this was not the case when i hadn't manually added the console and assumed it would show up in discovered when using tailscale since it should be part of the same network, but its fine because now while i was connected to hotspot i clicked on the console and remote play worked! so basically just add it manually while on the same local network first, can then it should be fine and remote play should work great with tailsscale :)

Glad to hear you had success. Tailscale works differently than what I’m setup for. To answer your question, anyway, this is referring to the automation section in the documentation site for setting up game mode portion. It seems to be using a different script for launching versus the launcher for the flatpack.. at least when I try to add the shortcut for Chiaki4deck flatpack, it’s pointing to something else versus the automation script. I can’t answer these exactly, I’m sure someone else may chime in with better knowledge. Tailscale might have some extra features to make it work with the deck and these situations. However, for me, just attempting to add it while connected to VPN, and searching for it didn’t work. I sort of understand why it wasn’t from a high level view.

Chiaki is looking for a console, and script says “Check if SD is connected to this wifi SSID”
If so, connect using internal IP.
Otherwise, use external IP.

In most use cases, this makes sense. Not everyone has a VPN, even less so multiple networks/vlans. In my case, I’m already dialed in internally via VPN, but not using an internal SSID. So it uses external IP, the issue with that is I’m routed out to the internet. Of course, Chiaki won’t find it unless I forward the ports or do some more routing magic. I’d rather Chiaki, just test the internal connection first before routing back outward. So I changed the external IP to my internal IP in the script. Also, I could just not setup an external IP but I’m not sure how the script would look. So that’s about as much as where I am. Maybe sometime later, I’ll look into how tailscale does it.

**Comment by streetpea** [comment]
@Cook13s7777 the newer autoconnect feature (found on the consoles tab of the settings page) should do what you want. When on your home network. Register your ps5. Then add a manual connection by pressing the + button and enter your remote ip and select your already registered console from the dropdown. Now it should automatically launch your console, checking if the local is available first and then the remote.

**Comment by Cook13s7777** [comment]
> @Cook13s7777 the newer autoconnect feature (found on the consoles tab of the settings page) https://streetpea.github.io/chiaki4deck/setup/configuration/#auto-connect should do what you want. When on your home network. Register your ps5. Then add a manual connection by pressing the + button on the main chiaki4deck menu https://streetpea.github.io/chiaki4deck/setup/remoteconnection/#test-connection and enter your remote ip and select your already registered console from the dropdown. Now it should automatically launch your console, checking if the local is available first and then the remote. If you just have the old shortcut with the launcher script you can create a new Steam shortcut with the button on the main chiaki4deck menu https://streetpea.github.io/chiaki4deck/setup/steaming/.

Ahhh I didn’t realize that was the newer way of loading in game mode. I just followed the docs page, and it referred to that method. I will give that a try and report back my findings.

**Comment by streetpea** [comment]
It just got updated to the main method in the docs with 1.6.4 so if you installed before then that's probably why you used the other method. The auto connect is simpler to setup and works for most users. The automation script is something you can setup if you have specific use cases that require something more fine-tuned atm (I.e., for whatever reason the auto connect doesn't meet your needs)

**Comment by Cook13s7777** [comment]
Reporting back. I am on v1.6.5, so I removed everything and started fresh. Took the steam deck off VPN, by default it's connected to my IoT vlan via wifi, same vlan as PS5. PS5 is automatically discovered. Joined to VPN and it disappeared, I had to manually re-add as the internal IP to have it show up. Wasn't able to discover it while on VPN, but I assume that's because PS5 sends out broadcast packets, only to the same subnet/VLAN that the PS5 is on. New way works, just had to note that you it does require manually adding the internal IP, auto-discovery not possible between VLANs, it seems without special routing.

**Comment by QedC** [comment]
Same issue as mentioned above. The PS5 did not show up when connected through site-to-site vpn. 
The solution for me was to **delete the configuration file**, start chiaki4deck and re-add the PS5. 

It works flawlessly, and it even auto detect through VPN.
