### ISSUE TITLE
[BUG] Stuck at loading Screen with error Takion failed to send raw: Connection refused

### ISSUE THREAD

**Issue by Zackmon** [streetpea/chiaki4deck#287]
**Describe the bug**
After clicking on my PS5 to connect , Chiaki get stuck on the loading screen , although it says connected on the PS5
**Debug Log**
Please attach a log with verbose logging enabled.

**To Reproduce**
[chiaki_session_2024-03-20_23-10-24-227227.log](https://github.com/streetpea/chiaki4deck/files/14672117/chiaki_session_2024-03-20_23-10-24-227227.log)

1. Go to 'Chiaki home screen'
2. Click on 'connected PS5'
3. Screen will get stuck on loading

**Expected behavior**
to be able to see the PS5 Remote session

**Screenshots**
![Screenshot_20240320_231121](https://github.com/streetpea/chiaki4deck/assets/1449870/5bd924b5-7469-4855-b122-190713e4ce5d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 on KDE 5.24.7 both on Wayland and X11
- Hardware : AMD Ryzen Threadripper 3970X & AMD 7900 XTX
 - Chiaki4deck Version 1.6.4 both flatpak and appimage 

**Additional context**
it's working fine on my SteamDeck with steam OS , the issue seems to happen only on my desktop

**Comment by mjsjml** [comment]
I have same problem. But version 1.6.1 works for me (nothing after this).

**Comment by Zackmon** [comment]
@mjsjml thank you for the sugesstion , you are right , when I tried the 1.6.1 AppImage it worked for me 

not sure what broke it on the latest release

**Comment by mjsjml** [comment]
@streetpea neither works for me.  They both freeze in similar fashion.

**Comment by streetpea** [comment]
How about this build https://github.com/streetpea/chiaki4deck/actions/runs/8466611976/artifacts/1366394472?

**Comment by Zackmon** [comment]
Hi @streetpea , 

the last appimage shared by you is working for me 
https://github.com/streetpea/chiaki4deck/actions/runs/8466611976/artifacts/1366394472

**Comment by streetpea** [comment]
ok so the last appimage was the 1.6.1 code run today to make sure a change of dependencies didn't cause it. So it seems some change from v1.6.1 to v1.6.2 caused it. Can you try this build: https://github.com/streetpea/chiaki4deck/actions/runs/8473822822/artifacts/1368208702? It reverts more changes from 1.6.1 to 1.6.2 to try to identify what's causing this as there isn't an obvious candidate atm

**Comment by Zackmon** [comment]
Hi , 
the last version you shared didn't work, I tried to go through the logs but couldn't catch anything abnormal on it 

attaching it just in case 
[Uploading chiaki_session_2024-03-29_03-01-28-089089.log…]()

**Comment by streetpea** [comment]
It’s still giving the same error as before

**Comment by streetpea** [comment]
@Zackmon do you have pipewire set up on your system? If not the audio won’t be able to connect and that can block the stream session thread causing this.

**Comment by Zackmon** [comment]
Hi @streetpea 

you are correct , pipewire was the issue.

it's seems that it's not installed by default on Ubuntu 22.04 

after installing it , both latest version of appimage and flatpak worked for me 

Thank you for the help

**Comment by streetpea** [comment]
Glad to help. The dualsense haptics require pipewire so it was set as the only enabled audio backend starting with 1.6.2 in the appimage and set as the audio banckend via an environment variable in the flatpak. I’ll add a note that pipewire is required to the releases page so others don’t run into this.

**Comment by PowerPenguini** [comment]
1.9.1 Has the same problem for me

**Comment by streetpea** [comment]
@PowerPenguini do you have pipewire installed?

**Comment by PowerPenguini** [comment]
Worked like a charm, thanks :)

**Comment by Tomaasci** [comment]
I have 1.9.5, same issue though the pipewire package is installed. Could it be because (I think that) I run all my audio through pulse?

**Comment by streetpea** [comment]
@Tomaasci  can you post a log?

**Comment by streetpea** [comment]
@Tomaasci you might need to additionally install pipewire-pulse

**Comment by Tomaasci** [comment]
I did install pipewire-pulse, and then tried it, this is the log from that attempt (I redacted the IP addresses and other potentially identifiable information, all should be in <these brackets>). 

[chiaki_session_2025-02-22_10-56-36-590590-redacted.log](https://github.com/user-attachments/files/18921737/chiaki_session_2025-02-22_10-56-36-590590-redacted.log)
