### ISSUE TITLE
[BUG] v1.6.5 isn't available on Flathub

### ISSUE THREAD

**Issue by weakvar** [streetpea/chiaki4deck#289]
**Describe the bug**
Cannot update chiaki4deck to the latest version on Flathub.

**To Reproduce**
1. Go to Flathub
2. Click on chiaki4deck
3. The latest version is 1.6.4

**Comment by streetpea** [comment]
There was a problem with the flathub build. They said it may be a problem with their backend and that guy is out so it may be a little while. I’ll make it available on flathub as soon as possible.

**Comment by weakvar** [comment]
> There was a problem with the flathub build. They said it may be a problem with their backend and that guy is out so it may be a little while. I’ll make it available on flathub as soon as possible.

Thanks!

I'm thinking about switching to AppImage. How is the AppImage update process organized? Will I have to set everything up again after each update?

**Comment by streetpea** [comment]
You have to download and unpack. Ideally just delete the old appimage and replace it with the new one. That is the only setup you would need to do (other than running chmod +x on the new appimage) each time

**Comment by weakvar** [comment]
> You have to download and unpack. Ideally just delete the old appimage and replace it with the new one. That is the only setup you would need to do (other than running chmod +x on the new appimage) each time

Thanks for your help!
