### ISSUE TITLE
Hardware decoding not working - vaapi

### ISSUE THREAD

**Issue by herbzhao** [streetpea/chiaki4deck#29]
The original Chiaki works using vaapi but not the chiaki4deck, somehow. 
NOt sure whether it is realted to the new steam os update

**Comment by zucram** [comment]
Same problem. Latest stable release 3.4.2

**Comment by jmanbc** [comment]
Same problem with stable release 3.4.2

**Comment by streetpea** [comment]
@herbzhao @zucram @jmanbc can you try going into desktop mode and upgrading your flatpaks and then trying this again? It seems that an update to the runtime that chiaki4deck uses broke this in an update yesterday. They released a patch today which seems to fix the issue (at least it does on my Steam Deck). Chiaki pointed to a slightly different version of this runtime which didn't have the issue.

**Comment by YGn31** [comment]
Same problem with stable release 3.4.2, but solved after upgrading the flatpaks.

**Comment by herbzhao** [comment]
Thanks for the quick fixes. It is all good now.

**Comment by preacha** [comment]
I get this error again since today.
