### ISSUE TITLE
Discover Store credits “Unknown Developer”

### ISSUE THREAD

**Issue by tank-dude** [streetpea/chiaki4deck#294]
In the Steam Deck Discover Store, Chiaki4deck is listed but credits “Unknown Developer.” Is that the same version? I’ve seen videos where StreetPea is credited in the store. Should I just install through the Konsole?

**Comment by streetpea** [comment]
That’s weird it shows streetpea on flathubs website so it should also show on steams discover store https://flathub.org/apps/io.github.streetpea.Chiaki4deck

**Comment by streetpea** [comment]
It must be a glitch I see unknown author on my Steam Deck too through the discover store but it’s correctly displaying on Flathub. Anyway yes it’s the right one and you can install it if it’s distributed by Flathub
