### ISSUE TITLE
HDR cyberpunk 2077

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#295]
Hi, I've noticed the HDR option within cyberpunk does not show unless your TV/Monitor that supports HDR is also on. This is not the case for all games one example is Ratchet and clank: Rift apart. In this game you can toggle the Auto setting under the 120hz mode and it toggles HDR off and on within the game allowing you to see the difference between the two easily. 

With cyberpunk 2077 you can do the same thing as long as your hdr tv/monitor is also on and there is a big difference when you can enable the HDR setting in the game settings and you cannot. 

My question is if it's possible to trick games like cyberpunk 2077 into detecting a HDR monitor in use when it's not or detecting the Decks HDR display instead. It feels like HDR is not working via chiaki when a game does this, just feels like you are making the screen brighter not the highlights of the individual game.

**Comment by streetpea** [comment]
The PS5 has to get an HDR signal for it to transmit HDR video via the stream. In order to get this, it needs an attached HDR TV or a way to spoof the signal. We haven't been successful (using the multiple gadgets we've tried to spoof the signal). So the only way we've found to succeed with this is by attaching a compatible HDR tv and depending on the TV having it on (some work with it off others don't).

**Comment by iTsMute** [comment]
> The PS5 has to get an HDR signal for it to transmit HDR video via the stream. In order to get this, it needs an attached HDR TV or a way to spoof the signal. We haven't been successful (using the multiple gadgets we've tried to spoof the signal). So the only way we've found to succeed with this is by attaching a compatible HDR tv and depending on the TV having it on (some work with it off others don't).

Gotcha that's a bummer it seems to be game dependent rather than tv/monitor dependent from my testing but nonetheless unfortunate situation. I appreciate the response and your work greatly.
