### ISSUE TITLE
[BUG]It's maybe a bug on mac , gpu usage and temperature are too high 

### ISSUE THREAD

**Issue by whetherTsmile** [streetpea/chiaki4deck#296]
I use macbook air m1 and chiaki4deck's version is arm  1.6.5

https://github.com/streetpea/chiaki4deck/assets/17883634/84d2feb2-764f-4598-b243-b21af91c8191

![IMAGE 2024-03-27 20:02:42](https://github.com/streetpea/chiaki4deck/assets/17883634/6dff7074-4120-4605-acf5-e5933c51f3c3)
gpu usage and temperature is high

https://github.com/jbg77/chiaki
Then i use this fork, it works good

**Comment by streetpea** [comment]
Have you tried adjusting the render preset in the video tab of the settings and see if that has any effect?

**Comment by whetherTsmile** [comment]
> Have you tried adjusting the render preset in the video tab of the settings and see if that has any effect? Btw that fork uses a completely different rendering backend as Chiaki4deck switched to Vulkan via libplacebo (moltenvk for Vulkan on Mac) from OpenGL. Also try enabling the video toolbox hw decoder

yes, it's good with default or fast render preset

**Comment by streetpea** [comment]
If its fine of default or fast render preset then maybe the high quality preset is too much for your computer? see https://libplacebo.org/options/#global-preset for details. Anyway, it seems like this has to do with the lib placebo backend chiaki4deck uses rather than chiaki4deck itself.
