### ISSUE TITLE
Adding screen filters/postprocessors (e.g. sharpening - super resolution)

### ISSUE THREAD

**Issue by Invenisso** [streetpea/chiaki4deck#298]
It would be nice to add the ability to enable various post-processing filters, e.g. sharpening (super resolution), pretending to be a CRT monitor, black and white, etc. If you like this idea, please start with sharpening filter, because many games are slightly blurry during streaming and this is hard for the eyes.

**Comment by streetpea** [comment]
Libplacebo applies the ewa_lanczosharp upscaler and debanding already on the high quality preset (default for chiaki4deck). For other post-processing needs you can look at using something like vkbasalt https://github.com/DadSchoorse/vkBasalt which is compatible with chiaki4deck

**Comment by streetpea** [comment]
@Invenisso Also take a look at your bitrate and resolution settings. For a 1080p resolution, 30,000 is a good place to start for bitrate and you may want higher if the image still looks blurry to you.

**Comment by Invenisso** [comment]
Thank you for quick answer. I'll check out your tips. 
One more question - I have version 1.6.5 on original Steam Deck. There is no placebo hardware decoder (only vulcan and vaapi). Am I missing something?

**Comment by streetpea** [comment]
The hardware decoders for Linux are vulkan and vaapi. The rendering backend is vulkan provided by libplacebo. There is no selecting this, it's used behind the scenes. You can just select the quality preset behind the scenes.

**Comment by Invenisso** [comment]
vkBasalt solves my problem. I'm closing the issue. Thank you for your work.

**Comment by BMarques** [comment]
Does this apply to windows 11 as well?

**Comment by streetpea** [comment]
@BMarques  vkbasalt is for windows. However, you can use reshade choosing the Vulkan option (as opposed to dx10/dx11). Someone mentioned successfully doing this with reshade 4.5.0
