### ISSUE TITLE
it works but closes immediately after launch no matter what decoder is used [BUG]

### ISSUE THREAD

**Issue by mrmanguymaleperson** [streetpea/chiaki4deck#299]
it seems like it just shuts down and disconnects from the remote play

as for the debug log i cant provide that as i don't know how to access it and when chiaki shuts down it goes down along with the log menu

i have a bare bones computer gt710 but i know for a fact that that shouldn't be an issue since i have decent bandwidth and other adjacent programs work (regular chiaki and remote play) although this one seems to provide the best quality so far which is why i am rooting for it to work altho 1 second of screen sharing isn't enough to tell if the whole stream is gonna be that high quality ( i did try it on lower resolutions it opens for like 1 second on the game play or menu settings of the ps then shuts down)

i am on windows 10 
as for the console it is a ps4

**Comment by streetpea** [comment]
Open the settings and look for the log directory there go to that directory and extract logs. Without logs it will be pretty much impossible to tell what's happening. Alternatively you can download debug view https://download.sysinternals.com/files/DebugView.zip and launch it in the background and see what comes up on there when running Chiaki4deck.

**Comment by illusio26** [comment]
I'm having the same issue. I've attached my log file if that's helpful. 
[chiaki_session_2024-04-04_16-08-47-056056.log](https://github.com/streetpea/chiaki4deck/files/14877328/chiaki_session_2024-04-04_16-08-47-056056.log)

**Comment by streetpea** [comment]
@illusio26 based on your logs the PlayStation is going into sleep mode, terminating the connection and causing the stream to close. Do you any devices connected to the router PlayStation via hdmi that could be turning it off via hdmi-cec such as a TV?

**Comment by streetpea** [comment]
@illusio26 the stem of the problem seems to be that you are getting an invalid session id and using it. I added a check for the id size to filter out the invalid session id and set a fallback id that's valid if a valid id isn't received. Those changes (now in the main branch) should fix this issue. You can verify by testing the new release when it comes out.
