### ISSUE TITLE
Not working on steam deck (gaming mode + desktop mode)

### ISSUE THREAD

**Issue by nakedkurt** [streetpea/chiaki4deck#30]
When in desktop mode, I can remote play my PS5 via Chiaki4deck but left joystick can't move a character & it just serves as the same functions as D-pad, right joystick can't work too, XYB buttons too, only button A works...tried community controller mapping but still not working~ found that I can control the game by wireless keyboard...but I just want to control the game by steam deck's joysticks & buttons.

When in gaming mode, the loading page goes forever...already installed Proton GE...

Had deleted and reinstalled Chiaki4deck too yet none of them working~ too frustrated~!

**Comment by streetpea** [comment]
Hi @nakedkurt as far as desktop mode are you specifically changing the desktop mode configuration for the Steam Deck? You can change it from your Steam settings when you launch Steam in desktop mode (see https://www.reddit.com/r/SteamDeck/comments/t6c4w6/steam_deck_desktop_mode_configurations/) 

As far as gaming mode, you mentioned Proton GE. You shouldn’t be using proton at all with Chiaki/chiaki4deck as it’s a Linux executable not a windows one (turning proton compatibility on will cause it to fail to lunch in Steam / gaming mode).

**Comment by nakedkurt** [comment]
Finally it works in gaming mode after removing Proton and changing desktop mode configuration.
Not sure whether I configured correctly or not...your comment certainly helped~! Many thanks~

**Comment by streetpea** [comment]
Awesome! I’ll close this now since it seems like your issue is resolved.
