### ISSUE TITLE
[BUG] Manually adding a PS5, address comes back empty

### ISSUE THREAD

**Issue by dk-mushiyoke** [streetpea/chiaki4deck#302]
**Describe the bug**
Manually adding a PS5, address comes back empty, connecting and waking up resulting in errors

**Debug Log**
For some reason logs were not being populated correctly
[chiaki_session_2024-03-30_20-46-50-279279.log](https://github.com/streetpea/chiaki4deck/files/14813937/chiaki_session_2024-03-30_20-46-50-279279.log)
[chiaki_session_2024-03-30_20-47-54-113113.log](https://github.com/streetpea/chiaki4deck/files/14813938/chiaki_session_2024-03-30_20-47-54-113113.log)

**To Reproduce**
1. Go to 'Settings' -> 'Consoles'
2. Click on 'Register New'
3. Enter console details
![image](https://github.com/streetpea/chiaki4deck/assets/10867172/5be1abc4-024a-431f-9580-2bf2f64f6f7b)
4. Register and go to home page
5. Observe newly added connection
![image](https://github.com/streetpea/chiaki4deck/assets/10867172/54f923b3-68ea-4f44-8224-2d17dec7ffd2)
![image](https://github.com/streetpea/chiaki4deck/assets/10867172/7a9ae407-3d5d-408f-9703-29d8b8cc3ddc)
![image](https://github.com/streetpea/chiaki4deck/assets/10867172/6aee5692-ace9-485c-af8f-562cd8360efa)

**Expected behavior**
Address field is saved, connecting or waking up console works as expected

**Actual behavior**
Address field is empty, connecting or waking up console resulting in errors

**Screenshots**
See steps to reproduce

**Desktop (please complete the following information):**
 - OS: opensuse slowroll
 - Version: N/A
 - Device: desktop computer
 - Chiaki4deck Version: 1.6.5

**Comment by streetpea** [comment]
Have you tried manually adding with plus button on the main menu (putting in ip and then registering later)...just want to see how that works for you

**Comment by streetpea** [comment]
Btw session logs are saved from stream sessions. For stuff using gui before session is launched you can get logs by launching via cli such as `flatpak run io.github.streetpea.Chiaki4deck` for flatpak build in terminal...anyway I'll try to reproduce locally

**Comment by dk-mushiyoke** [comment]
@streetpea appreciate your fast response, I deleted the old entry and tried the plus button, when i went to register it added a new entry with no address
![image](https://github.com/streetpea/chiaki4deck/assets/10867172/74ba8adf-2282-4599-86dc-b90808dccd3e)

Log file from trying out the plus button, with the register successful response redacted - the response looks like it contains sensitive data, let me know if you need it, I can send it to you privately.
[output.log](https://github.com/streetpea/chiaki4deck/files/14814368/output.log)

Thank you for your assistance
