### ISSUE TITLE
Does chiaki4deck work on Windows handheld consoles?

### ISSUE THREAD

**Issue by weakvar** [streetpea/chiaki4deck#303]
Based on the name of the project, I guess it was originally intended for Steam Deck. But I see that there are builds for Windows. Can you please tell me if chiaki4deck also works as well on Windows 11 as it does on Steam Deck? Ordered a Lenovo Legion Go to play on PlayStation 5 in portable mode, because PS Portal is no good (very poor streaming quality compared to chiaki4deck). 

@streetpea I just want to say thank you so much for what you're doing. chiaki4deck has breathed new life into the original chiaki ❤️

**Comment by streetpea** [comment]
Yes!
