### ISSUE TITLE
Implement upscaling technologies

### ISSUE THREAD

**Issue by weakvar** [streetpea/chiaki4deck#304]
I wonder if it is possible to implement upscaling technologies in chiaki4deck? For example, to upscale a 1080p video stream to 2K. Kinda like AMD released Radeon FSR upscaling for video playback not too long ago. Basically, chiaki4deck just streams video. I don't know if there is an SDK for this, maybe just enabling the setting in Adrenaline would be enough.

**Comment by streetpea** [comment]
See #298 to see if any of that would interest you

**Comment by weakvar** [comment]
Thanks, will try that solution
