### ISSUE TITLE
Problems with controller vibration on version 1.6.6 for Windows

### ISSUE THREAD

**Issue by weakvar** [streetpea/chiaki4deck#307]
**Describe the bug**
Controller vibration stopped working. If you run chiaki4deck through Steam, there is no vibration at all. But if you run chiaki4deck as a normal program (I mean run chiaki.exe), the vibration is there, but it is infinite (it doesn't stop until you close chiaki4deck). 

I don't know if this problem is present on Steam Deck. We are talking about chiaki4deck 1.6.6 on Windows. My device is Legion Go.

**Debug Log**
Will add soon as files.

**To Reproduce**
1. Update to chiaki4deck 1.6.6 from 1.6.5 on Windows 11.
2. Run it, play some game with vibrations.
3. You'll notice that the vibration doesn't stop.

Also:
1. Update to chiaki4deck 1.6.6 from 1.6.5 on Windows 11.
2. Add it as a Non-Steam Program in Steam.
3. Run it from Steam, play some game with vibrations.
4. You'll notice that there's no vibration at all.

**Expected behavior**
Controller vibration working like 1.6.5.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2
 - Device Lenovo Legion Go
 - Chiaki4deck Version 1.6.6

**Comment by streetpea** [comment]
It seems to be a problem isolated to the msys2 build for windows ... possibly something broke with sdl2 there. Can you try the vc build for windows and report back?

**Comment by weakvar** [comment]
> @weakvar It seems to be a problem isolated to the msys2 build for windows ... possibly something broke with sdl2 there. Can you try the vc build for windows and report back?

Yep, let me some time and I'll back with feedback

**Comment by weakvar** [comment]
@streetpea you right, VC build works. So let's close this issue. Thanks!
