### ISSUE TITLE
[BUG] Variable zoom not behaving as expected on Steam Deck

### ISSUE THREAD

**Issue by mandiller** [streetpea/chiaki4deck#308]
Hi

Thanks for implementing the variable zoom feature in the new 1.6.6 version. Great to see it's in there so quickly! However, it's not working quite like how I imagined. I wonder if it's bugged. As soon as you enable the variable zoom feature and increase it to the first step of 1.01, it jumps the zoom level in considerably. It's far, far too zoomed in.

I was hoping when you enable the variable zoom that 1.00 of zoom was the default level of the game stream, which shows the black bars at the top and bottom on Steam Deck, like normal, then 1.01 is slightly more zoomed in (but still with bars) and 1.02 slightly more etc. Until you get to a point that it cuts off the entire black bars and gives you the no-bars zoom level we are used to before this latest version of Chiaki4deck.

The idea being that I can then decrease the black bars at the top and bottom a little bit while deciding how much of the side is acceptable to cut off - so I can adjust it to keep some game UI elements on screen.

Here's what it looks like for me:

Normal default steam with black bars

![bars-default](https://github.com/streetpea/chiaki4deck/assets/161995671/ff472304-0701-4082-be10-92a645573a7c)

No bars level of zoom before enabling the first step of the new variable zoom

![nobars](https://github.com/streetpea/chiaki4deck/assets/161995671/9e3206f4-6142-48da-b989-bef311d54e4a)

Adjusting the variable zoom to the first step of 1.01. Notice how it increases the zoom level dramatically. And how it's more zoomed in than the 'no bars' zoom level, rather than just a slight increase in zoom from the default stream.

![101 zoom](https://github.com/streetpea/chiaki4deck/assets/161995671/d5c76c95-e732-4a15-9503-7a2bf6006e2b)

**Comment by streetpea** [comment]
Try 720p should work as expected. For 1080p I would need to add 0.8, etc. level of zoom to get black bars back

**Comment by streetpea** [comment]
If you try this appimage be able to set the zoom you want for 1080p https://github.com/streetpea/chiaki4deck/actions/runs/8602178840/artifacts/1394613349

**Comment by mandiller** [comment]
> Try 720p should work as expected. For 1080p I would need to add a negative level of zoom to get black bars back on a resolution greater than the max resolution of the screen.

I just tried 720p briefly and yes, the zoom works perfectly. I haven’t tried the other appimage yet for 1080p as I’m at work but I presume it’ll work fine and will be incorporated into the flatpak version?

Thanks for all the work you do on Chiaki! It’s such an excellent and essential app for the Steam Deck.

**Comment by streetpea** [comment]
Yes, the flatpak will be updated with the next release. Having said that, the appimage build is something I can provide now easily whereas the update won't be released via the flatpak until the next release so depending on how much you wanted to try out the change I wanted to give you the option to try it now vs. waiting.

**Comment by streetpea** [comment]
fixed by 3e6eb65ea653e0770f31905ea4a1c87965b6ca0f
