### ISSUE TITLE
[BUG] HDR is not working in games

### ISSUE THREAD

**Issue by antib0t** [streetpea/chiaki4deck#310]
**Describe the bug**
SteamDeck OLED. Running chiaki in game mode. 
when connected to ps5 i see “HDR” mark in deck quick access menu. 
hower when im running any game (Alan Wake 2, Ghost of Tsusima) im not able to enable or adjust any hdr setting. 
for instance in Alan Wake u have an ability to switch between SDR and HDR. 
however for me option is grayed. 
What can be the issue?

chiaki4deck - latest build from Discovery
Steamdec - latest official stable release

**Comment by streetpea** [comment]
HDR data has to be sent from ps5 for Chiaki4deck to display hdr. For this to happen, the tv has to send a signal to the ps5 to enable hdr. Most likely your tv is not currently sending that signal either because it is off or does not support hdr. This is a limitation of the ps5 and would have to be fixed by Sony in firmware and not something Chiaki4deck or any ps5 remote play solution can do anything about.

**Comment by antib0t** [comment]
Thank you for the response. 
but my ps5 is attached to tv supporting hdr. 
only thing that of course tv itself in “sleep” as well as ps5.

**Comment by streetpea** [comment]
Try with your tv on

**Comment by antib0t** [comment]
Ah. I get. So it is something, let say, TV related now. 
Some models would work, some - no? Correct?

**Comment by streetpea** [comment]
It should work with your tv on. Basically for hdr supported tvs some send the signal while the tv is off others only send when the tv is on. The ps5 needs the signal to enable hdr based on its current firmware.

**Comment by antib0t** [comment]
Thank you for the explanation. 
Basically, so far we need to maintain a list of “available for HDR on remote session” TVs 😂
Interesting how to report it to sony☺️
Thank you so much again
And really full respect on what u have done so far💪💪💪

**Comment by jbaiter** [comment]
>  Basically, so far we need to maintain a list of “available for HDR on remote session” TVs 😂

I wish it was that simple :-( According to user reports and my own experience it seems to be game-specific as well.
