### ISSUE TITLE
[BUG] Issues with "Enable gyro on Steam Deck automatically"

### ISSUE THREAD

**Issue by imwearingahat** [streetpea/chiaki4deck#313]
**Describe the bug**
The update to "Enable gyro on Steam Deck automatically" in v1.6.6 does not perform as expected. Tested in Helldivers 2: Horizontal movement barely registers, vertical movement works but is fairly jumpy. 

**To reproduce**
1. Steam Deck
2. Disable gyro input in the controller settings
3. Ensure gyro is enabled in your game settings

**Expected behavior**
Gyro when playing remotely via Steam Deck feels reasonably close to DualSense gyro when playing on the PS5 directly. 

If this can't be improved, the option to disable the automatic gyro usage would be great in order to avoid having to disable gyro in the game settings when alternating between playing on PS5 directly and remotely on Steam Deck. As it stands, it interferes with "Gyro as joystick" when gyro is enabled in the game settings, whereas this worked very well previously since the Steam Deck was not sending gyro input to the PS5 directly.

**Desktop**
 - Device: Steam Deck
 - Chiaki4deck: v1.6.6

**Comment by streetpea** [comment]
How are you holding the Steam deck when using gyro. If you are not using it in the same orientation as a ps controller, you may want to use the vertical gyro option for steam deck (if you are holding your deck vertically and not horizontally as a ps controller)

**Comment by streetpea** [comment]
Also the only case where the Steam Deck wasn’t sending gyro input to the ps5 before the auto gyro enable was when it was set to None. Steam automatically enables gyro if it’s set to any gyro option. The auto gyro just takes effect if gyro is set to none to still send gyro.
