### ISSUE TITLE
Ability to Map External Controllers when Playing Docked - OR have the "Select" button act as Trackpad Click by default on Xbox Controllers

### ISSUE THREAD

**Issue by SuttonX** [streetpea/chiaki4deck#315]
Please see this comment on reddit:

https://www.reddit.com/r/remoteplay/comments/yrnswc/comment/j9msisc/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

This guy was able to modify the Windows version of Chiaki so that when using a non-Playstation controller, the Select button acts as Trackpad click by default.  I tested this on my Windows machine and it works perfectly with my 8BitDo Ultimate controller.

Is it possible to replicate this on Chiaki4Deck as well?  I understand we can map buttons with Steam but whenever I do that it only really works handheld, when I have the Deck docked using that same 8BitDo controller, no matter how I map it in Steam, pressing the select button still activates the Share function on my Playstation.  SOMETIMES it will also act as a trackpad click, but even when it does it will still always take a screenshot too.

**Comment by streetpea** [comment]
Since this is already possible via key mapping as you have detailed I believe this is complete
