### ISSUE TITLE
[BUG]PSN Base64 not working

### ISSUE THREAD

**Issue by parkercd** [streetpea/chiaki4deck#316]
Tried to set up on steamdeck and when i select PSN login and then type my username and click submit nothing happens, and the submit is greyed out. Tried a few time but nothing.

**Comment by streetpea** [comment]
It seems like the website used for that is down

**Comment by streetpea** [comment]
In the meantime you can use the python script built into Chiaki4deck with `flatpak run --command=psn-account-id io.github.streetpea.Chiaki4deck
`

**Comment by parkercd** [comment]
Hi thanks for replying any chance you can explain the python to someone who
is not very technical.

Many thanks in advance

**Comment by streetpea** [comment]
It’s creating an auth token (token that gives it permission to access resources assigned to your user) to query the ps servers for your account id.

**Comment by parkercd** [comment]
Thanks but apologies I mean how to I do the python flatpack run?

**Comment by parkercd** [comment]
Sorted thanks for your help up and running amazing app thanks

**Comment by Ptoricanmilt** [comment]
I having similar troubles but on a Rog Ally with Windows 11.  Not familiar with how to leverage that scrip in this OS.  Any help would be greatly appreciated.

**Comment by grill2010** [comment]
I have contacted the support of that website to ask why the website is down.

**Comment by streetpea** [comment]
Update: The website is back up now and this method should work again. Additionally, I'll add alternatives to the app in the next release so as not to rely on just that website.

**Comment by grill2010** [comment]
Did not get back any answer despite the fact I was in contact with the dev of the website before, but glad it works again now
