### ISSUE TITLE
[SteamOS] I have been trying to get this flatpak to work but it just won't.

### ISSUE THREAD

**Issue by Vidiot24** [streetpea/chiaki4deck#317]
I don't know why it won't work because it honestly should but it seems to me that it is calling for a plugin my steam deck does not have
[chiaki_error.txt](https://github.com/streetpea/chiaki4deck/files/15211266/chiaki_error.txt)
Sorry that I don't have verbose logging enabled here, new to steam deck, and I don't know how to get the plugin it is asking for, and I don't want to fuck up my steam deck by doing something stupid, so I am posting this issue. Can someone help me with this please?

**Comment by Vidiot24** [comment]
Managed to figure out how to get verbose logs.
[Debug Log Chiaki4deck.txt](https://github.com/streetpea/chiaki4deck/files/15211339/Debug.Log.Chiaki4deck.txt) 
Help.

**Comment by streetpea** [comment]
It could be that you have some settings on your Steam Deck so it detects Wayland even though it should just detect x11.

try
```
sudo flatpak override --nosocket=fallback-x11 --socket=x11 io.github.streetpea.Chiaki4deck
```

**Comment by Vidiot24** [comment]
It worked wonders. Thank you. I think it might have been because waydroid
is installed on my deck. An compatibility issue between the two, makes
sense now.
