### ISSUE TITLE
[BUG] SteamOS Desktop mode - font and background are both white, text unreadable

### ISSUE THREAD

**Issue by MightyXG** [streetpea/chiaki4deck#318]
This is probably a configuration issue, not bug -

I downloaded Chiaki4deck in the discover store in my new Steam Deck OLED, no changes were made to UI or anything yet. When I open Chiaki4deck, both the setup page for my PS5 and through the gear icon are showing some texts in white, with the default white background, so they are not readable. I can't find a setting for night mode/dark background, as shown in other people's screenshots, or how to change the font. If this is the default config, then this might need to be updated.

![Screenshot_20240504_213004](https://github.com/streetpea/chiaki4deck/assets/50378499/39898823-18ed-44fe-b3e8-343b5a177b8f)

**Comment by streetpea** [comment]
It’s an issue with kdes handling of the theme…try launching it from game mode instead.

**Comment by MightyXG** [comment]
Got it, thank you!
