### ISSUE TITLE
[QUESTION] IPv6 Compatibility

### ISSUE THREAD

**Issue by noigamegun** [streetpea/chiaki4deck#319]
I'm trying to use chiaki4deck outside lan using IPv6 and it will not work even if I have a IPv6 address. Chiaki will timeout the connection instantly. My IPv4 is stuck behind a NAT so port forwarding will not work but I have a static IPv6 with the firewall disabled for the whole network. Does chiaki support IPv6 and if so what is the problem here?

**Comment by streetpea** [comment]
The automatic remote connection feature in prerelease supports IPV6. Only the flatpak has been updated so far to support IPV6 but all of the versions will be updated when it releases.

**Comment by streetpea** [comment]
@noigamegun if you are on a release other than Linux (i.e., can't use the pre-release flatpak that has the IPV6 update) I can run a build for you on your platform of choice if you are willing to test it out.

**Comment by noigamegun** [comment]
I'm on the latest AppImage version. I already try the flatpak version but it will be stuck on light mode like some issues on here.

**Comment by noigamegun** [comment]
It would be appreciated for you to build the pre release version as a AppImage

**Comment by noigamegun** [comment]
It seem like IPv6 just bugged out and now IPv6 doesn't work. Mostly like my issue.

**Comment by streetpea** [comment]
IPv6 bugged out in the prerelease flatpak? If so can you post a verbose log? Or do you still want an appimage build?

**Comment by noigamegun** [comment]
No it the ps5. It doesn't wanna work with my ps5.

**Comment by streetpea** [comment]
I made an appimage build with the ipv6 changes here: https://github.com/streetpea/chiaki4deck/releases/download/psn_test/Chiaki4deck.AppImage.zip

**Comment by streetpea** [comment]
Since this was just a question and it's been answered, I'm closing this. Progress of ipv6 support will be updated at #323

**Comment by streetpea** [comment]
So after further investigation and enabling ipv6 on the Chiaki4deck side the ps (console side implemented by Sony) does not support ipv6 so this is not possible at least up to ps5 generation.
