### ISSUE TITLE
[QUESTION] - Import chiaki.conf from SD to MacOS

### ISSUE THREAD

**Issue by RainrZufall** [streetpea/chiaki4deck#321]
Hi,

I've been able to save my config several times on Steamdeck and then import it again, so I didn't have to register chiaki with my PS5 again. 

Can I use this file (chiaki.conf) on my Mac too?
Where do I have to copy this file? 

Thank you for your help!

**Comment by hvmzx** [comment]
Did you find a solution ? I am trying to do the same

**Comment by RainrZufall** [comment]
> Did you find a solution ? I am trying to do the same

I haven't tried it any further myself. Because I have no idea which directories Chiaki accesses and i was hoping to get an answer/instructions here. 😅

I will probably try out the new function "remote connection via PSN" this weekend.

**Comment by Entropy512** [comment]
Both Chiaki and Chiaki4Deck use Qt's QSettings system - you might be able to find some documentation somewhere on where MacOS stores QSettings files.

Although https://stackoverflow.com/questions/59236289/where-to-find-qsettings-on-macos implies that there may be file format differences in a default configuration that uses a "native" settings file.
