### ISSUE TITLE
[QUESTION] in regards to the upcoming "Remote Connection Using PSN for Setup"

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#322]
Hey streetpea! 

Love that this feature is coming to chiaki. I love this feature on psplay. My question is will we still have the option to "manually" connect via our port forwarding we already have setup. I've noticed the difference manually doing it yourself with portforwarding is a faster experience in getting connected to the ps5 (atleast this is how it is on psplay).

**Comment by streetpea** [comment]
Yes once you enter your psn creds the console shows up as an additional tile in the GUI labeled with psn remote connection (consoles added manually still show as normal)

**Comment by iTsMute** [comment]
Awesome! Thanks for the quick response 😊
