### ISSUE TITLE
[BUG] Stream failed with d3d11va selected.

### ISSUE THREAD

**Issue by Mromerolillo** [streetpea/chiaki4deck#325]
![IMG_20240513_145756](https://github.com/streetpea/chiaki4deck/assets/168833361/41be9ac2-ab1b-44f0-b0c9-8e81e0bcf5f6)

Stream failed with d3d11va selected.
 Av_codec_get_hw_config failed.

Windows 11. Rog Ally.

Chiaki4deck 1.7.0v

Probably caused by "workaround patch for vulkan ffmpeg hw decoder"

![IMG_20240513_102722](https://github.com/streetpea/chiaki4deck/assets/168833361/2d876786-e74c-4587-b0bc-04f425da7726)

**Comment by streetpea** [comment]
Have you tried Vulkan hw decoder? You should be using Vulkan for the best performance bc it has zero copy. I can look into this though

**Comment by Mromerolillo** [comment]
yes, vulkan works perfectly for me.
