### ISSUE TITLE
[BUG] 1.7.0 not launching

### ISSUE THREAD

**Issue by ThaMighty90** [streetpea/chiaki4deck#327]
**Describe the bug**
After updating to 1.7.0 chiaki4deck is no longer launching neither in desktop nor in game mode

**To Reproduce**
1. Start app
2. app shows in taskbar and then vanishes

**Expected behavior**
The app starts

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Version: latest
 - Device Steam Deck
 - Chiaki4deck Version 1.70

**Additional context**
I updated today to 1.7.0 and wanted to try the new PSN login but after updating I can no longer launch chiaki4deck. I already tried reinstalling but with no luck.

**Comment by L0WR1D3Rz** [comment]
did you uninstall first?

**Comment by ThaMighty90** [comment]
yes

**Comment by streetpea** [comment]
Please launch via the konsole with `flatpak run io.github.streetpea.Chiaki4deck` and post the logs you get in the konsole

**Comment by ThaMighty90** [comment]
Logs:

```
F: Not sharing "/esp" with sandbox: Ignoring blocking autofs path "/esp"
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, xcb, vkkhrdisplay, wayland, minimalegl, offscreen, wayland-egl, vnc, linuxfb.

```

**Comment by streetpea** [comment]
Try
```
sudo flatpak override --nosocket=fallback-x11 --socket=x11 io.github.streetpea.Chiaki4deck
```
And then launch

**Comment by ThaMighty90** [comment]
now it launches again

**Comment by streetpea** [comment]
The deck should be using x11 but for some reason it’s detecting Wayland use and so since fallback-x11 is selected the x11 socket isn’t used. There must be some software on your deck causing this. Having said that, I can just use x11 instead of fallback x11 to prevent users from running into this.

**Comment by ThaMighty90** [comment]
yeah just noticed chiaki4deck isn't the only software not launching. Firefox won't launch so i can't do the PSN login process. I will do a factory reset and report back if the problem still exists.

**Comment by streetpea** [comment]
You may be able to use the same command with Firefox and see if that works as well

**Comment by ThaMighty90** [comment]
yeah, but it was kind of getting a bit wonky here and there. I think a reset is really needed

**Comment by ThaMighty90** [comment]
So after the factory reset and a few steam updates the app launches as expected.
