### ISSUE TITLE
This keeps popping up[BUG]

### ISSUE THREAD

**Issue by iTsMute** [streetpea/chiaki4deck#331]
(View image) this will pop-up everytime when pressing the steam button while at this menu. My work around is force closing instead of using the steam button to close it out. 

**To Reproduce**
1. Open chiaki via game mode
2. Press steam button

**Expected behavior**
Steam panel pops out with options

**Desktop (please complete the following information):**
 - OS:  SteamOS
 - Version latest stable branch
 - Device [oled Steam Deck]
 - Chiaki4deck Version [e.g. 1.7.0]

**Additional context**
First time seeing this issue started happening after updating chiaki to the latest
![20240515_004538](https://github.com/streetpea/chiaki4deck/assets/120707099/5cdba694-e79d-4eed-9dfd-c81e2cc2f151)

**Comment by streetpea** [comment]
I’ll look into it. Just fyi though the easiest way quit out is using the back button mapped to ctrl+q … that will quit out of the main menu or the stream menu (you can also use the x to close as well)

**Comment by iTsMute** [comment]
> I’ll look into it. Just fyi though the easiest way to quit out is using the back button mapped to ctrl+q … that will quit out of the main menu or the stream menu (you can also use the x to close as well)

I actually do use that back paddle most of the time and it did work to close it out once but after that I had to use steam+b to get out of it. It freezes the display up and the refresh is inconsistent at working unfortunately. 

Thank you as always ❤️

**Comment by streetpea** [comment]
@iTsMute do you by chance have decky loader installed? I see some ppl with it installed here having your issue: https://www.reddit.com/r/SteamDeck/s/blrutAdfFi

**Comment by iTsMute** [comment]
> @iTsMute do you by chance have decky loader installed? I see some ppl with it installed here having your issue: https://www.reddit.com/r/SteamDeck/s/blrutAdfFi

Why yes I do! I'll mess with it today and close the ticket if the issue is resolved.

Good looking out! Thank you

**Comment by iTsMute** [comment]
Decky loader was the issue. Just had to wait for some plugins to update
