### ISSUE TITLE
[BUG] Can't build with system curl

### ISSUE THREAD

**Issue by devusb** [streetpea/chiaki4deck#338]
**Describe the bug**
When using `CHIAKI_USE_SYSTEM_CURL`, builds fail with 
```
       > CMake Error at /nix/store/pb69k0zwhxg6kf9ifz13x1wjs6a9vmf0-cmake-3.29.2/share/cmake-3.29/Modules/FindCURL.cmake:190 (message):
       >   CURL: Required feature WS is not found
       > Call Stack (most recent call first):
       >   CMakeLists.txt:86 (find_package)
       >
       > 
```
even though curl is built with websocket support, as evidenced by
```
❯ curl-config --protocols   
DICT
FILE
FTP
FTPS
GOPHER
GOPHERS
HTTP
HTTPS
IMAP
IMAPS
IPFS
IPNS
LDAP
LDAPS
MQTT
POP3
POP3S
RTMP
RTSP
SCP
SFTP
SMB
SMBS
SMTP
SMTPS
TELNET
TFTP
WS
WSS
```

Believe this is due to the fact that `FindCURL.cmake` doesn't actually know `WS` and `WSS` as valid protocols, as seen [here](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindCURL.cmake?ref_type=heads#L158).

**To Reproduce**
1. Build system curl with websocket support
2. Attempt to build chiaki4deck with `CHIAKI_USE_SYSTEM_CURL` as `true`

**Expected behavior**
Chiaki4deck builds successfully.

**Desktop (please complete the following information):**
 - OS: NixOS
 - Version 24.05
 - Device: Steam Deck
 - Chiaki4deck Version 1.7.0

**Additional context**
I found this as part of packaging [chiaki4deck for nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/games/chiaki4deck/default.nix#L107) -- I discovered that `libcurl` is one of the build outputs when built without `CHIAKI_USE_SYSTEM_CURL`, so trying to use curl from `nixpkgs` to avoid that. Removing `WS WSS` from https://github.com/streetpea/chiaki4deck/blob/143425f58c32be9772c37a463b24d3df98e5d36d/CMakeLists.txt#L83 lets the build complete, and chiaki4deck seems to work normally.

I'd be good to open a PR for this, but not sure if a) I've missed something or b) how to actually detect if curl was built with websocket support.

**Comment by streetpea** [comment]
@devusb can you use the remote connection via psn? That is what’s using curl websockets.

**Comment by devusb** [comment]
@streetpea almost -- fwiw I can't actually connect via psn using flatpak or nixpkgs (errors similar to #332 and #333 even on flatpak for me, probably a network thing), but I do get these lines when using the nixpkgs build which seems to indicate that at least the websockets bit is working
```
[W] Haptics output is not using Pipewire, this may not work reliably. (was: 'pulseaudio')
[V] chiaki_holepunch_session_create: Created websocket thread
[V] chiaki_holepunch_session_create: Waiting for websocket to open...
[V] websocket_thread_func: Connected to push notification WebSocket wss://35-164-247-234-pushcl.np.communication.playstation.net/np/pushNotification
[V] Holepunch session state: 1 = [ ✅WS_OPEN ]
[V] http_create_session: Sending JSON:
{"remotePlaySessions":[{"members":[{"accountId":"me","deviceUniqueId":"me","platform":"me","pushContexts":[{"pushContextId":"689776d6-3ce7-4fa6-b724-0a064d9ddbee"}]}]}]}
[V] websocket_thread_func: PING.
[V] websocket_thread_func: Received WebSocket frame of length 0 with flags 64
[V] websocket_thread_func: Received PONG.
[V] websocket_thread_func: Received WebSocket frame of length 550 with flags 1
[V] websocket_thread_func: Received WebSocket frame with 550 bytes of payload.
```

```
[V] Received notification of type 1
[V] websocket_thread_func: Received WebSocket frame of length 736 with flags 1
[V] websocket_thread_func: Received WebSocket frame with 736 bytes of payload.
```

```
[V] Holepunch session state: 27 = [ ✅WS_OPEN ✅CREATED ✅CLIENT_JOINED ✅DATA_SENT ]
[V] websocket_thread_func: Received WebSocket frame of length 762 with flags 1
[V] websocket_thread_func: Received WebSocket frame with 762 bytes of payload.
```

**Comment by streetpea** [comment]
@jbaiter do you have any insight regarding checking if curl supports websockets?

**Comment by streetpea** [comment]
@devusb can you build the 1000_cuts branch and see if this fixes your issue (I added the FindCurl.cmake with WS and WSS protocols). You can also try remote connection via PSN and see if it works for you now on that branch as it now supports more network types.

**Comment by devusb** [comment]
@streetpea It did, but only after I made these small changes to `FindCURL.cmake` to let it use macros as builtins.
```
diff --git a/cmake/FindCURL.cmake b/cmake/FindCURL.cmake
index f27eb4e..761d356 100644
--- a/cmake/FindCURL.cmake
+++ b/cmake/FindCURL.cmake
@@ -74,7 +74,7 @@ Hints
 cmake_policy(PUSH)
 cmake_policy(SET CMP0159 NEW) # file(STRINGS) with REGEX updates CMAKE_MATCH_<n>
 
-include(${CMAKE_CURRENT_LIST_DIR}/FindPackageHandleStandardArgs.cmake)
+include(FindPackageHandleStandardArgs)
 
 if(NOT CURL_NO_CURL_CMAKE)
   # do a find package call to specifically look for the CMake version
@@ -137,7 +137,7 @@ if(NOT CURL_LIBRARY)
   )
   mark_as_advanced(CURL_LIBRARY_DEBUG)
 
-  include(${CMAKE_CURRENT_LIST_DIR}/SelectLibraryConfigurations.cmake)
+  include(SelectLibraryConfigurations)
   select_library_configurations(CURL)
 endif()
```

Thanks.

**Comment by streetpea** [comment]
fixed thanks @devusb

**Comment by devusb** [comment]
Checked again with final committed version -- worked without modification. Thanks again.
