### ISSUE TITLE
[BUG] Unable to launch streaming session with ps5. "Chiaki session has quit: unknown error in stream connection"

### ISSUE THREAD

**Issue by Kirit29** [streetpea/chiaki4deck#341]
**Describe the bug**
trying to launch a session on my local wifi network results in "Chiaki session has quit: unknown error in stream connection"

**Debug Log** on 

[chiaki_session_2024-05-22_12-19-20-941941.log](https://github.com/streetpea/chiaki4deck/files/15406200/chiaki_session_2024-05-22_12-19-20-941941.log)

**To Reproduce**
Registering the console and setting up as instructed in docs worked fine.
after shutting off console completely and turning back on i still can wake ps5 but trying to start a stream results in said error
**Expected behavior**
Ps5 should launch a stream properly with no errors?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Bazzite OS - deck
 - Version 3.0.1
 - Device Steam Deck
 - Chiaki4deck Version 1.7.0 flatpak

**Additional context**

**Comment by streetpea** [comment]
Can you try this build and see if it fairs any better? https://github.com/streetpea/chiaki4deck/actions/runs/9198990026/artifacts/1528885010

**Comment by streetpea** [comment]
Also can you use the official remote play app with this PS5?

**Comment by Kirit29** [comment]
@streetpea that did the trick.

**Comment by streetpea** [comment]
@Kirit29 awesome! Can you post an updated log just to confirm the fix is taking effect?

**Comment by Kirit29** [comment]
I will when I get home. I'm out at the moment
