### ISSUE TITLE
Add vertical scroll bar to settings menu?

### ISSUE THREAD

**Issue by JamesPConnolly91** [streetpea/chiaki4deck#35]
The Steam Deck's internal resolution is too low to show the entire settings menu in desktop mode.

**Comment by streetpea** [comment]
Kk I’ll add this asap. The latest update added the PS5 features opt-in that controls whether or not you have haptics enabled for the Steam Deck. This additional section made the settings take up more space and now it stretches far off screen if you are not using a monitor. For now (before update with scroll bar is pushed) a workaround is to maximize the window and you should be able to change all of the relevant settings, even though some of the settings menu still stretches off the screen.
