### ISSUE TITLE
ChiakiUp -- Rumble feature (Android)

### ISSUE THREAD

**Issue by Bardok1984** [streetpea/chiaki4deck#350]
Hi! I am an user Who loves Chiaki app as the BEST PlayStation streaming app in Windows /Android devices.

However I really BEG your Team to develop a better Implementation/compatibility with Rumble option on **ANDROID**

I enabled the option in settings "Rumble the Device itself" but there is no Rumble, neither the controller or the phone itself Rumble.

I am using a BSP D9 controller which has several modes for bluetooth pairing (as a Xbox wireless Controller Mode, Dual shock 4 Mode etc) and despite of this, I cannot get a Rumble as ... Better Xcloud does nowadays.

Please , are Chiaki team plans to implement It??? It is the only One feature everyone IS missing...(For Android) 

I Will wait for your answer

**Comment by streetpea** [comment]
Chiaki4deck doesn’t have an Android version nor is there any interest in supporting Android among the dev team. Chiaki4deck supports rumble for all games including ps5 games and is available on windows, Linux and Mac. Since this is an issue for Chiaki that supports Android and not Chiaki4deck I’m closing this.

**Comment by Bardok1984** [comment]
Ok, excuse me, How could I to put in Contact to Chiaki team? I just found this thread related to chiaki4deck wishing Chiaki team could read this as well...

My apologies

**Comment by streetpea** [comment]
You could email Florian Markl the creator of Chiaki but it is in a support only mode so new features will likely not be added

**Comment by Bardok1984** [comment]
I have tried to het any email for support from Florian Markt but I did not find any...

Please,  don you know It? 

It is my last chance 

Thank you , I appreciate your help

**Comment by Geocld** [comment]
> Understood,
> 
> Anyway, PsPlay has implemented Rumble for Android devices. Chiaki4deck before had not any Rumble feature for Windows as well.
> 
> Nowadays It has, PsPlay Rumbles in the same Chiaki4deck does, both "translate" and "convert" vibration haptic Signal to Rumble Standard Signal.
> 
> Chiaki itself should incorporate a similar option...
> 
> As time goes by, I Hope they Will.

@Bardok1984 I am currently planning to develop a more user-friendly PS remote streaming app for Android based on Chiaki, and I am also exploring a solution to implement rumble in Chiaki. Since I have not used Chiaki-ng on the desktop side and am currently unable to test it on the desktop, I would like to ask you if the rumble feedback in Chiaki-ng on the desktop works effectively, especially for PS5 games. Additionally, the clue you mentioned about converting haptic feedback into standard rumble feedback is very helpful to me! I hope you can provide more insights so that I can develop the ideal app more efficiently and quickly!

**Comment by Geocld** [comment]
@Bardok1984 
Thank you very much for your detailed feedback. I am currently working on developing a new PS streaming application. So far, I have completed the login and device registration functions. The information you provided is very valuable for my development!

In fact, I am the developer of [XStreaming](https://github.com/Geocld/XStreaming), which is an Xbox Android streaming application. If you're interested, you can download this app and test the controller vibration function by going to Settings-DEBUG-Rumble, even if you don't have an Xbox console. Currently, it provides very comprehensive vibration feedback functionality, and I believe I can combine the information you provided along with my experience in game controller vibration to solve the Chiaki rumble issue.

By the way, the new streaming application will continue to use Chiaki's streaming playback functionality, so you don't need to worry about video playback stuttering at all. The controller and vibration functions will be completely reimplemented. Currently, I can already achieve PS5 rumble feedback based on the original Chiaki, but I will continue to reference the implementations from chiaki-ng and @kkong/chiaki to improve the vibration functionality.

Best of luck to you!

**Comment by Bardok1984** [comment]
Hi

Yes, Kkwong implemented very well the rumble function,  it works perfect
making rumble in every action it is required,  for ps4 and also ps5.

Vibration works same with chiaki4deck. Very responsive.


However , Psxplay app ...has a different rumble, it happens just....in some
cases...it seems that the app interprets in some cases when the controller
has to rumble...so it os weird (it is better than nothing) but it works as
a "sound  vibration", neveetheles you feel here that there are moments when
you have to feel rumbling your controller (turbo boost in cars, or a
shotgun) but it does not happen....then there are cases when you jump and
you  feel rumble ...so it is not really precise.


If you get chiaki playback technology and get rumble from kkwong or
chiaki4deck...it will be a dream come drough because in Android,  chiaki is
abandoned


When do you think you will have your app ready?? Falling this year? Or
maybe begginning 2025?


Thanks

**Comment by Bardok1984** [comment]
Hi again

Regarding your new ps remote app based on chiaki with rumble, is there
any release date for launch?

I sold my S9 tab Ultra for the reason I mentioned, on Android there
was no version of chiaki with vibration before... but now that this
real possibility has been confirmed, I am considering buying a Tablet
S9 Ultra again, as it is very expensive. . Before I spend the money on
it, I would need to know if your application will finally come out or
if it has a release date.


Thanks to your application I am considering buying an S9 Tab Ultra again.


Wishing you the Best programing process and THANK you again for your
invaluable effort and support.


Thank you really for everything

**Comment by Bardok1984** [comment]
Hi Jihao Li

How does the progess of your new ps remote based on chiaki with rumble??
Did you finish? Is there any possible release date for launch?

Wishing you the Best.
If you need some feedback or something please let me know.

Kind regards

Andres

**Comment by Geocld** [comment]
@Bardok1984 The work is still in progress. Since I'm developing this in my spare time, I cannot guarantee the completion date. As this is a completely new application, many details need to be redesigned and developed from scratch. I expect to have a trial version available by the end of next month. You can follow my GitHub for the latest release information.

**Comment by Geocld** [comment]
@Bardok1984 
By the way, you can test this Chiaki version that supports PS5 vibration（https://github.com/Axixi2233/chiaki-android/releases/tag/240919）, although the interface is only in Chinese. You can check if the vibration effects meet your expectations.

**Comment by Bardok1984** [comment]
Thank you very much

The link to that chiaki version un GitHub does not work,  it Says content
didnt find


Any other wat to download and try that app to check???

I am very happy to hear thay possibly next month yoy will finish your final
version

Wishing you the best

**Comment by Geocld** [comment]
@Bardok1984 Sorry, the link is incorrect, Pls try this [link](https://github.com/Axixi2233/chiaki-android/releases/tag/240919) and download the `chiaki-240919-axixi.apk`

**Comment by Bardok1984** [comment]
Hi Joahao Li

Well, I could check the Chiaki Axixi2233 version , also your Xbox stream
app, using my S9 tab Ultra with the Gamesir G8 Galileo bluetooth controller
(for most gamers the Best android gamepad at moment)

The G8 Gamesir Galileo has several Modes for pairing,  I used the "Dual
Sense" Mode.

Unfortunately, my feedback is...negative, for several reasons.

- CHIAKI AXIXI 2232

1) problem is that the vibration feeling os so weak..., very weak. You must
sometimes focus tour attention to see it its is working, other cases you
feel it  but weak rumble. Even I confirmed that I was using the strongest
rumble option in settings (when I press the buttom of the gamepad to select
the highest level of rumble you can feel a very strong vibration from the
gamepad)
However while playing in Chiaki ...the rumble ....feeling is so weak.

2) the vibration itself it is noy very responsive. I mean...the rumble
appears when you jump playing with AstroBot game for example. So there are
times when you are not jumping but the rumble appears anyway , so ...it
results in a imprecise.


- XStreaming (YOUR APP)

Rumble vibration is more precise,  it rumbles in the correct way (using
xcloud games) but...again here...the rumble feeling is so weak..very
weak...very low rumble strength...


If you check BETTERXCLOUD app...you can feel rumble strong , so much
stronger and better for example.
With PXplay rumble is little bit stronger than chiaki Axixi2233,  and much
more precise...however PXplay suffer a lot of sttutering as I told you
before...


Maybe a possible SOLUTION is..if you are able to set up different levels of
rumble a
Strength, or ...make the rumble signal stronger...to make the
rumble/vibration better from the Gamepad...otherwise, the rumble by now is
so weak...so weak, poor and low.

Could you do it? Maybe ...you can make the Rumble Signal better or anyewy
to "amplify " the rumble strength.


Well , I will try and check other different Gamepad modes of my G8 gamesir,
and continue checking it.

Wishing you the Best and if you need more feedback or ant idea to fix it,I
can help you all you need.

Happy new year 2025 for you and familias


Kind regards

Andrés

**Comment by Bardok1984** [comment]
New update Jiahao Li

Checking rumble in PXPLAY app, here, rumble intensity is fine, it is strong
and very very responsive.

Maybe the Best rumble feeling in all apps I tried.

Regarding Chiaki Axixi2233,  I am not able to get fullscreen (stretched)
..I tried my touching the corner right left of the screen to make the icons
screen pop up but it ...is really difficult to do it..., all Chiaki in
Android has this problem.

The rumble of Chiaki Axixi2233 is the Worst for me...really por, weak and
not precise.


On the other hand, I really love from your XStreaming APP that once you are
infame and you press "back" on the screen a Quick menu appears in the
center on the screen, in that Quick menú you can set up display settings
(sharpness , color,  etc ) thats great!!!! Could you include this Quick
menú on your next PS remote app???


Lets see how tou implement the rumble function on your app...if you can
make the signal giving a stronger rumble feeling (or a intensity rumble
menú with several vibration levels) would be astonishing...
Anyway, try to copy rumble from PXPLAY app or CHIAKI4DECK,  both are the
Best for me


Kind regards

**Comment by Geocld** [comment]
@Bardok1984 
Long time no see! The new PS streaming client has been released. You can check out the project at [PeaSyo](https://github.com/Geocld/PeaSyo) and download the APK for use.

**Comment by Bardok1984** [comment]
Hi Jiahao lin

Excuse me for my late answer but I was so busy during the week.
Well I am so happy to see your app finished , checked settings and
astonishing the variety of options for rumble intensity etc

However I am not able to log in /register my ps5..., your app works
different...with chiaki and psplay I just put my iD, in my ps5 pro I enable
the code to pair a new device and so on


In your app, it tries to log in my Sony psn account, but it fails... it
says that the app is not compatible with Pass Key....

Indeed I cannot use my password,  just pass key or, if I click on "other
methods " in both, again it says the same ...(incompatibility with pass
key) showing a QR code with numbers...(I attach a screenshot in this email
to show what I see)

Should I disable pass key in my ps account?? Or ...what can I do to
register my Ps5 to your app???

Thank you so much

**Comment by Bardok1984** [comment]
Here the screenshot added to show you what I mean

**Comment by Bardok1984** [comment]
Finally I signed and registered the PS5 Pro...

Whay to say...., AMAZING, I'm so impressed...really, rumble is precise,
very precise and powerfull!! Perfect!! I selected high intensity and it is
so strong. Work perfect and responsive in all games I tried.

Video streaming is ...also perfect, smooth as chiaki offers, creaban and
Sharp. Some times appears little artefact (same as chiaki) but in general
is wonderful.

Do you recommend codec H265 ? Or H265 HDR? (I own a PS5 PRO and thinking of
getting a Redmagic NOVA tablet now when I see your app is so nice)

Congratulations...being honest, I appreciate all the effort you have
done...at the end we have a complete android PS STREAMING QUALITYZ+ RUMBLE..

Thanks , thank you for your invaluable effort

If you improve it more...its going to be awedose.

You are breathtaking

**Comment by Bardok1984** [comment]
Hi Jiahao Li

Thank you for your new release 1.0.4, it has many things fixed (the
stretched screen fixed was so neccesary)

However when the app 1.0.3 suggested to do the update,  the update process
made an error...a pop up screen said "some error with the packages occurred
"

So finally I was forced to unistall the 1.0.3 completely from my phone and
install the 1.0.4 manually from the beginning.

I had to sign to psn account again etc...

Maybe...there is any incompatibility in the update process from the own app
or I do not know.

Well so now I will continue enjoying your amazing app, it is so
breathtaking.

I will keep in touch to you with new feedback if you like.

Thank you so much

**Comment by Geocld** [comment]
@Bardok1984 
Thank you very much for your recognition of Peasyo. I believe Peasyo will continue to improve with the efforts of the community. Below are my responses to your questions:

1. **Video Encoding**: I recommend using H265. HDR can be enabled based on your needs, but sometimes HDR might not meet your expectations. My knowledge of HDR is also quite limited.

2. **Client Updates**: Sometimes, client updates encounter issues with inconsistent signatures. I haven't been able to pinpoint the reason for this. If you encounter problems updating the app, I suggest uninstalling and then installing the new version. 

   As for the issue of needing to re-register the host after reinstallation, Peasyo has a very practical feature. In `Settings -> Configuration -> Transfer`, you can export your configuration. The configuration file includes your PSN login information and PS registration details. Even if you reinstall Peasyo, you can simply import the configuration file here, eliminating the need to re-register the host or perform other setup steps. 

   It's also cool that you can transfer the exported configuration file to another device and use the same method to quickly set up Peasyo on the new device! Note that due to Android's file permission restrictions, exporting settings can only be done in the `Download` folder, e.g., `Download/peasyo/peasyo_xxxx.json`.

---

If you find Peasyo useful, I hope you can give it a **star** on its repository. This will encourage me to continue creating and improving Peasyo. Also, I warmly welcome you to recommend Peasyo to your friends, so more people can enjoy using it!

---

I look forward to your continued experience with Peasyo and your feedback. Additionally, since this is the Chiaki-NG issues page, if you have other questions, feel free to raise them in the Peasyo issues section or contact me directly via email at **lijiahao5372@gmail.com**. Good luck!

**Comment by Bardok1984** [comment]
Hi !

Cliente update fixed!! I updated with no issues.

All the new features are amazing.

Regarding the key mapper,  I wanted to suggest you something:
An interesting upgraded feature to include would be including the LEFT
STICK directions.

I mean,

Some users prefer controlling the game using the Digital Pad instead of
using the left stick and viceversa.


So, if you include to key mapp this :

"Left stick UP"
"Left stick DOWN'
"Left stick RIGHT "
"Left stick LEFT"

With it, we would be able to map those actions to the D pad (D pad up, D
pad down, D pad right etc)

Could you implement this? The majority racing games force you to use left
stick for driving...and D-pad for me is much more precise. Besides bearing
in mind kart games (the new Sonic racing crossworlds) would be wonderful to
key map the left stick fully to the D pad. (As all users are doing ob Steam
key mapping)


Well, wishing you the Best,

Last sugestión, to get it more popular, if you design the appearance icon
more close to PS design (any simbol close to ps, or similar) could make a
very possitive effect.  (You could use the dual SHOCK buttons, or a PS with
different colors of the epoch of the original PSX (ps1)

I attatch to this email a pic of similar PS simbols that could make you
feel inspired.


Thank you for your astonishing help and support.  I feel so grateful to
recibe such this ...dream app, android deserved a ps app like yours. It is
wondeful. You are definitely breathtaking.

Thanks

**Comment by mubashirbilawal5-netizen** [comment]
B bug
