### ISSUE TITLE
Multiple PSN ID’s per console

### ISSUE THREAD

**Issue by feras54** [streetpea/chiaki4deck#352]
Hi,

Is there anyway to have more than one user for the same console?

all the solutions I found in the internet is for steam deck nothing for windows 

Thanks

**Comment by streetpea** [comment]
Create a shortcut with the option --profile user1 after the path to Chiaki4deck when launching the app via windows … make another shortcut with --profile profile 2 … then when you use that shortcut you’ll be using the corresponding profile. User 1 launches via user1 shortcut and enters their credentials. User2 launches via user2 shortcut and uses their credentials.

**Comment by feras54** [comment]
@streetpea first thank you for your prompt response 

Sorry but I didn't understand what exactly should I do I went to AI chat to explain your reply and this is its response is it right?

![image](https://github.com/streetpea/chiaki4deck/assets/157243750/29014c34-38a1-4709-bc61-05e2a4950b7d)

**Comment by streetpea** [comment]
Yes except you probably need the full path to Chiaki4deck.exe rather than just Chiaki4deck.exe (if you just create a regular shortcut for Chiaki4deck it should populate the path and then you would just need to edit it to add the argument for the profile) like explained in the chat you linked.

**Comment by feras54** [comment]
@streetpea I created the shortcuts and both opened the same user 

so now do I have to open the second shortcut and delete the user in it (which is the first user) and add my second user or what ?

**Comment by streetpea** [comment]
One shortcut should have --profile user1 and the other should have --profile user2

**Comment by feras54** [comment]
@streetpea I did it and it worked except the steam app seems to not recognizing the shortcut

**Comment by streetpea** [comment]
Create new apps via Steam using the create Steam shortcut button and in the arguments/options section add the --profile=user1 for the first shortcut and --profile=user2 for the second shortcut and name each shortcut appropriately so you know which is which

**Comment by feras54** [comment]
@streetpea the only two section I have when I click on "create steam shortcut" is name of shortcut and lunch option. anyway I did add a shortcut but it doesn't show up on steam it only save pictures inside steam files

**Comment by streetpea** [comment]
@feras54 you put it in launch options --profile=user1

**Comment by streetpea** [comment]
Also you have to restart steam after adding the shortcut for it to work (restarting your computer works) otherwise you have to completely shut out of steam (not just the store) and restart it.

**Comment by feras54** [comment]
As usual you are a genius
Thank you so much it worked
