### ISSUE TITLE
[BUG] App darkens when playing in gaming mode with HDMI Output

### ISSUE THREAD

**Issue by west1nat0r** [streetpea/chiaki4deck#353]
**Describe the bug**
When starting chiaki4deck via game mode while using a HDMI output once the connection to the ps5 is started the output gets way darker. When going back to the connection menu the darker output stays. Doing the same in Desktop mode does not trigger the same behavior and works as expected. Output stays the same all the time. 

**Debug Log**
Please attach a log with verbose logging enabled.

**To Reproduce**
1. Have a HDMI Output
2. Start chiaki4deck in gaming mode
3. Connect to PS5

**Expected behavior**
I expect the brightness to remain the same level, like it does in the desktop mode

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Steam OS Holo
 - Version: 3.5.19
 - Device: Steam Deck OLED
 - Chiaki4deck Version 1.7.1

**Additional context**

**Comment by west1nat0r** [comment]
Here are some screenshot of this situation

![Gamingmode-before~2](https://github.com/streetpea/chiaki4deck/assets/43881954/f4b31f2b-89de-4910-8a53-5797caa57d93)
![Gamingmode-after~2](https://github.com/streetpea/chiaki4deck/assets/43881954/156c0ae9-34ba-46a8-a31b-8d8f97fa5a7c)
![Desktopmode~2](https://github.com/streetpea/chiaki4deck/assets/43881954/52ba76e5-b066-4775-b781-6e9ac43e2a97)
![Desktop-ingame](https://github.com/streetpea/chiaki4deck/assets/43881954/a0e5f263-1659-43df-a4f6-fa749844ef17)
![Gamingmode-ingame](https://github.com/streetpea/chiaki4deck/assets/43881954/62122dbb-063c-4e6b-8bcc-4a4d3455b219)

**Comment by streetpea** [comment]
You can check in the brightness settings of the steam deck if this is due to hdr activating.

**Comment by streetpea** [comment]
@west1nat0r can you go into the Chiaki4deck settings in video and select h265 as the codec instead of h265hdr given you are using an sdr external screen and see if that rectifies the issue.

**Comment by west1nat0r** [comment]
Damn... All that work bothering you guys for silly hdr. Just activated it manually in the settings and here we go it seems good now!

Thx for the quick help

**Comment by west1nat0r** [comment]
For me it seems like I haven't had HDR activated in gaming mode... That fixed my issues :)
