### ISSUE TITLE
[BUG] Wifi drops after first couple of minutes

### ISSUE THREAD

**Issue by agonzalezramos** [streetpea/chiaki4deck#356]
Basically, every single time that I turn on my ps5 or ps4 and I start to use chiaki4deck, the first 3 minutes works great, and suddenly starts to drop wifi packages and to stutter really bad.

The solution is simply close the app and open it again and the problem is solved until I turn off the PS.

Any idea what could be wrong?

I'm on the last chiaki4deck version (1.7.1) and the last SteamOS version on the stable channel.

Thanks a lot!

**Comment by streetpea** [comment]
This is a dup of #230, closing as this is being tracked there. @agonzalezramos please look there for suggestions
