### ISSUE TITLE
[BUG] Discovery/network connection not working using 1.7.2 under macOS (ARM64)

### ISSUE THREAD

**Issue by mserajnik** [streetpea/chiaki4deck#358]
**Describe the bug**
Using the 1.7.2 release, the network icon in the bottom left shows a disabled state and no consoles in the local network are visible. The network icon appears clickable (it visually reacts to clicking, though I don't know if that is even intended or if it's just supposed to be a status indicator) but that doesn't do anything; it seems as if chiaki4deck thinks that there is no network connection.

I've tried relaunching the application multiple times and even switched between different WiFi connections but that didn't help.

Downgrading to 1.7.1 fixes the issue.

**Debug Log**
I enabled verbose logging but it doesn't write a log file when launching the application.

**To Reproduce**
1. Launch the 1.7.2 build for macOS ARM64
2. Observe the network icon in the bottom left appearing to indicate a disabled state
3. Observe that no consoles in the local network are visible

**Expected behavior**
The network connection should work and local consoles should be discovered.

**Screenshots**
![image](https://github.com/streetpea/chiaki4deck/assets/80664890/b03ff255-0a12-4d74-9c15-e7b5475a7ea8)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.5
 - Device: MacBook Air M1
 - Chiaki4deck Version: 1.7.2

**Additional context**
None.

**Comment by streetpea** [comment]
@mserajnik download the updated build on the releases page. Should fix your issue.

**Comment by mserajnik** [comment]
> @mserajnik download the updated build on the releases page. Should fix your issue.

Thanks for the quick work, I'll give this a try tomorrow and let you know if it fixes the issue.

**Comment by nckmrtn** [comment]
I just downloaded the updated build and am experiencing the same issue @mserajnik originally described - no issues with 1.7.1 though.

**Comment by streetpea** [comment]
@nckmrtn can you try this build https://github.com/streetpea/chiaki4deck/actions/runs/9456188442/artifacts/1587390273? Maybe it didn’t get updated on the releases page properly.

**Comment by nckmrtn** [comment]
@streetpea that build worked, thank you so much! If it helps the one on the releases page has a created/modified timestamp of 2:14 PM while the one you just linked has a created/modified timestamp of 4:08 PM.

**Comment by streetpea** [comment]
@nckmrtn I tried uploading again just now ... hopefully the one on the releases page is the updated one now.

**Comment by nckmrtn** [comment]
@streetpea I just downloaded it from the releases page again and can confirm that it is now the same as https://github.com/streetpea/chiaki4deck/actions/runs/9456188442/artifacts/1587390273 - thanks again!!
