### ISSUE TITLE
Native Gyro seems a bit eratic

### ISSUE THREAD

**Issue by natcl** [streetpea/chiaki4deck#36]
First thanks a lot for native Gyro support ! It opens up various games that were impossible to play.

I tried it with Dreams and it seems that it sometimes thinks I'm holding the device upside down (my cursor will go upside down) I also noticed that when I'm still the cursor seems to drift a little bit.
Not sure what info I can provide to help you more but let me know !

Thanks !

**Comment by streetpea** [comment]
Have you turned off the gyro mapping to right joystick in Steam Input?

**Comment by natcl** [comment]
That's a good point, I tested it in Desktop mode first so I think it would be disabled there but let me check to make sure.

**Comment by streetpea** [comment]
Hmm, I haven’t tried dreams. I’ve tried concrete genie and Astros controller demo which show a cursor or whole controller and seem to work fine. I think the flipping thing happens with a traditional controller as well if you move the input too high for some PS4 games so might not be an issue with Steam Deck gyro. 

Having said that, the drifting seems strange. It’s possible there’s something specific about the way dreams is using gyro that is messing with it. I can check out dreams specifically and see if I can recreate it.

**Comment by streetpea** [comment]
I tried dreams and it’s not working right. Up/down works correctly and does switch at a point but it does the same thing on the console with a controller for me. Side to side isn’t working properly. I think it doesn’t like the Steam decks orientation values or something. It’s weird that Astro’s and concrete genie seem to like them fine (I mention these bc you can actually see the controller moving fully in Astro’s and a cursor in concrete genie).

**Comment by natcl** [comment]
I wanted to mention also that the first time I tried, I also tried the Astro demo and the onscreen controller was in the wrong orientation (sideways) which could explain why I was seeing my cursor upside down in Dreams.

I tried again and now Astro seems to work fine. Dreams is better but still get some drift (but the cursor doesn't go upside down) so perhaps something went wrong with calibration the first time I tried ?

**Comment by streetpea** [comment]
@natcl Astros does seem to have a sort of automatic calibration (really more of just resetting the base state so you can use the controller with any starting orientation such as when laying on your back) at the beginning of its controller demo so strange things can happen depending on the way you were initially holding your controller. Having said that, there is definitely a problem with dreams. It should be using side to side horizontal movement (yaw) when flat facing up not side to side tilt (roll) like it is now. For example, in concrete genie that’s what it does. I’m currently using the Steam Decks orientation values and probably need to switch back to manually calculating them (easy fix). I’ll test this and see if it fixes the problem.

**Comment by streetpea** [comment]
@natcl update: yep that fixed it. I’ll post a patch soon. I’m not getting any more drift in dreams.

**Comment by natcl** [comment]
Awesome ! thanks :)
