### ISSUE TITLE
[BUG]After updating to the latest version, the streaming screen is distorted

### ISSUE THREAD

**Issue by sunwanhe159** [streetpea/chiaki4deck#361]
**Describe the bug**
After updating to the latest version, the streaming screen is distorted
![2769491718151292_ pic](https://github.com/streetpea/chiaki4deck/assets/43960293/496f9fa3-de15-4e97-8940-654029287e32)

![2769541718151431_ pic](https://github.com/streetpea/chiaki4deck/assets/43960293/63a1e32b-3168-4660-bfb2-6c702fc1c461)

**Comment by streetpea** [comment]
@sunwanhe159 This is a dup of #359 … please look there for instructions to resolve your issue.

**Comment by sunwanhe159** [comment]
> @sunwanhe159 This is a dup of #359 … please look there for instructions to resolve your issue.

thank you so much!
