### ISSUE TITLE
Not working anymore[BUG]

### ISSUE THREAD

**Issue by Waterhazzerd** [streetpea/chiaki4deck#362]
**Describe the bug**
I connect to my PS5 and i get this

https://github.com/streetpea/chiaki4deck/assets/141873707/b868c574-f9c2-40a6-9763-5280764107f7

**Debug Log**
Please attach a log with verbose logging enabled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: SteamOS
 - Steam Deck
 - Chiaki4deck Version 1.7.2

**Additional context**

**Comment by streetpea** [comment]
Dup of #359. Look there for a solution closing..
