### ISSUE TITLE
[BUG] Windows build of chiaki4deck can't automatically detects PS5 in the local network

### ISSUE THREAD

**Issue by tutivog** [streetpea/chiaki4deck#365]
**Describe the bug**
My PS5 has wired connection to the router. My pc is wried to the router as well. And I also have a steam deck that has stable 5G connection to the router.

I have installed chiaki4deck on both my pc (win 11) and the steam deck (steamOS). A very weird bug occurs with the win version running on my pc as it can't automatically detects the PS5 in my local network while the steam deck can.

I have tried disabling the firewall, adding the chiaki.exe to the firewall exception, and reinstalling the program, but none of which solved the probelm.

While I could set up a manual connection on my pc and have my ps5 get a static ip from the router, it nevertheless bothers me from time to time as the win-version just can't detect local available PS5.

Both the steam deck and pc are running the 1.7.2 build. And the steam deck is running on SteamOS 3.6.

**Comment by streetpea** [comment]
@tutivog thanks for reporting. This build for Windows should fix your issue ... https://drive.proton.me/urls/80MXR9EDS8#bBxUqBvfQCVL

**Comment by tutivog** [comment]
> @tutivog thanks for reporting. This build for Windows should fix your issue ... https://drive.proton.me/urls/80MXR9EDS8#bBxUqBvfQCVL

Thanks for the help! But I tested this build, it only detects PS5 when there has already been a manual connection set up. But removing the manual connection entry will also disrupt the auto-discovery.

With a manual connection:
![屏幕截图 2024-06-17 100559](https://github.com/streetpea/chiaki4deck/assets/13778638/3f3ff8a7-7ce3-42af-b2e4-44d74d72233c)

Without a manual connection:
![屏幕截图 2024-06-17 100820](https://github.com/streetpea/chiaki4deck/assets/13778638/703733ea-2787-488b-9351-23ba491e90db)

As soon as I tried removing manual console, the auto-discovered entry immediately becomes a "over-PSN" connection.

**Comment by streetpea** [comment]
@tutivog this build should fix your issue https://drive.proton.me/urls/GCHGB4TZ3G#qkCW16gfzYg6

**Comment by tutivog** [comment]
Can confirm it has been fixed. Thank you so much!
