### ISSUE TITLE
[BUG] Connection from PS5 to deck stutters only while TV is off.

### ISSUE THREAD

**Issue by 6dam** [streetpea/chiaki4deck#367]
**Describe the bug**
chiaki4deck seems to stream from my PS5 to OLED Steam Deck without issue if the TV is on (regardless of what it's displaying, i.e. set to the PS5 HDMI input or the Android TV homepage, etc.) or if the PS5's HDMI cable is unplugged from the TV. However, if the TV is off, chiaki4deck will launch but the video will lag every minute or so. (can still hear game audio/actions while the video feed lags)

**Debug Log**
Log attached. 
[chiaki_session_2024-07-03_06-51-24-151151.log](https://github.com/user-attachments/files/16085973/chiaki_session_2024-07-03_06-51-24-151151.log)

**To Reproduce**
1. With the PS5 in rest mode and TV off, launch chiaki4deck and go into a game. 
2. Video will lag periodically, every minute or so regardless of what I'm doing in game or on the PS home menu.

**Expected behavior**
Smooth streaming from my PS5 without these frequent freezes.

**Desktop (please complete the following information):**
 - OS: Steam OS Holo
 - Version 3.5.19
 - Steam Deck OLED
 - Chiaki4deck Version 1.7.3

**Additional context**
TV is a TCL 50S434, compatible with HDR.

Thanks very much for any advice you can offer - I'm really enjoying chiaki4deck otherwise!

**Comment by streetpea** [comment]
This sounds like something on the remote play server side controlled by Sony on the ps itself. The client (I.e., Chiaki4deck) has no control over this so there isn’t really anything we can do on our end to “fix” it unfortunately. Having said that, on the Steam Deck oled it may help to switch on and off the wifi before playing or wake up the device from completely off.
