### ISSUE TITLE
[BUG] Crashes immediately on startup after manually adding public DNS router hostname entry for PS5

### ISSUE THREAD

**Issue by RynO-SauruS** [streetpea/chiaki4deck#368]
**Describe the bug**
Running OLED Steam Deck.

Once I have my PS5 initally registered using its local IP address, I am able to connect without issue.

Afterward, I manually add my router's public DNS hostname using the existing PS5 registration (for connecting through the Internet). The program then becomes unusable, crashing immediately on startup. The interface appears briefly then disappears.

I can disable the network connection on the Steam Deck temporarily and that prevents the crash at startup. As soon as I re-enable the network with the program running, it crashes.

I can delete my Chiaki.conf file and the program becomes stable again.

I have recreated the issue with both the Flatpak and AppImage versions of the application (version 1.7.3). I am unable to get either of them to work for me.

Below I have ran the AppImage from the terminal and pasted the interesting parts of the output.

**Debug Log**
(1)(deck@steamdeck ~)$ /home/deck/Downloads/Chiaki4deck.AppImage/Chiaki4deck.AppImage
...
[I] Discovery failed to bind port 9304, trying one higher
[I] Discovery failed to bind port 9304, trying one higher
[I] Discovery failed to bind port 9305, trying one higher
[I] Discovery failed to bind port 9304, trying one higher
[I] Discovery failed to bind port 9305, trying one higher
[I] Discovery failed to bind port 9306, trying one higher
[I] Discovery Service detected new host with id **[redacted]**
free(): invalid pointer
Aborted (core dumped)

**To Reproduce**
1. Register PS5 using local IP. Remote Play works flawlessly at first.
2. Add public DNS hostname of router afterward using existing PS5 registration.
3. Restart the application.
4. It crashes on startup every time.

**Expected behavior**
The application should not crash on startup.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: SteamOS 
 - Version: 3.5.19
 - Device: Steam Deck OLED
 - Chiaki4deck Version: 1.7.3

**Additional context**
None

**Comment by RynO-SauruS** [comment]
I managed to make the program stop crashing by deleting the DNS hostname entry and adding the public IPv4 address instead. It should be noted that my DNS record also has an IPv6 (AAAA) record which my device seemed to be pulling. So I suspect Chiaki might have been pulling the IPv6 address and choked.

**Comment by RynO-SauruS** [comment]
I managed to make the program stop crashing by deleting the DNS hostname entry and adding the public IPv4 address instead. It should be noted that my DNS record also has an IPv6 (AAAA) record which my device seemed to be pulling. So I suspect Chiaki might have pulled the IPv6 address and choked.

**Comment by streetpea** [comment]
Hmm @RynO-SauruS can you try this build and see if it helps at all https://github.com/streetpea/chiaki4deck/actions/runs/9864584127/artifacts/1684072579. You can first unzip it to your downloads folder and then make it executable with `chmod +x ~/Downloads/Chiaki4deck.Appimage` and then open it with `~/Downloads/Chiaki4deck.Appimage`. Then, close it and you can copy settings from the flatpak with
```
cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf ~/.config/Chiaki/Chiaki.conf
```
and then you can reopen the appimage and use it to test it out.

**Comment by RynO-SauruS** [comment]
> Hmm @RynO-SauruS can you try this build and see if it helps at all https://github.com/streetpea/chiaki4deck/actions/runs/9864584127/artifacts/1684072579. You can first unzip it to your downloads folder and then make it executable with `chmod +x ~/Downloads/Chiaki4deck.Appimage` and then open it with `~/Downloads/Chiaki4deck.Appimage`. Then, close it and you can copy settings from the flatpak with
> 
> ```
> cp ~/.var/app/io.github.streetpea.Chiaki4deck/config/Chiaki/Chiaki.conf ~/.config/Chiaki/Chiaki.conf
> ```
> 
> and then you can reopen the appimage and use it to test it out.

Hi, just tried to download your test build and I got a 404 not found.

**Comment by RynO-SauruS** [comment]
@streetpea  The test build appears to have fixed the crash. However Chiaki still fails to connect using my DNS record - this is most likely because it is still pulling the IPv6 address which my network is not configured to allow currently. I could correct this by removing the AAAA record and having AA only.

**Comment by streetpea** [comment]
@RynO-SauruS try this build ... it should hopefully work ... I forgot to make the change for the session hostname lookup as well and only made it for registration and discovery before.

**Comment by KrisCris** [comment]
Not sure if my experience is relevant, but I am also having the crashing issue.

I have port forwarding (10.0.0.202 -> 10.0.0.1) setup on my router, chiaki crashes immediately when my deck is connected to the local network.

**Comment by streetpea** [comment]
@RynO-SauruS @KrisCris can you try this build? https://github.com/streetpea/chiaki4deck/actions/runs/10031052771/artifacts/1723647909

**Comment by RynO-SauruS** [comment]
> @RynO-SauruS @KrisCris can you try this build? https://github.com/streetpea/chiaki4deck/actions/runs/10031052771/artifacts/1723647909

That build seems to be working perfectly; I was able to connect using my DNS hostname. However I have removed the IPv6 record. Not sure if that is relevant to what you're testing.

**Comment by KrisCris** [comment]
> @RynO-SauruS @KrisCris can you try this build? https://github.com/streetpea/chiaki4deck/actions/runs/10031052771/artifacts/1723647909

works perfectly

**Comment by streetpea** [comment]
awesome closing now then!
