### ISSUE TITLE
controls not working 

### ISSUE THREAD

**Issue by datnodude** [streetpea/chiaki4deck#37]
due to my wifi config I can only get chiaki working in desktop mode. I noticed some of my controls are no longer working. in the ps menu my left thumb stick can go up/down but not left/write, same for the dpad. my right thumb stick doesn't do anything. is there a way to reset the controls? this is what it's set to currently

![20230114_184805](https://user-images.githubusercontent.com/28940802/212502044-a0226ee3-d4d7-4c81-831e-65a0d28eb495.jpg)

**Comment by streetpea** [comment]
You can add the gui to game mode if the automation doesn’t work for you. In desktop mode, you can change your desktop mode control mapping via steam. Specifically, the desktop mode configuration. You can also edit it in game mode now too by editing desktop controller config there I believe. I wouldn’t change anything in the Chiaki gui. I should map to the controller config automatically if you select a proper mapping for your controller in Steam.

**Comment by datnodude** [comment]
I've tried editing the gamepad layout in steam settings and downloading different user templates. same behavior. I don't know what changed

**Comment by streetpea** [comment]
Something did change with the desktop mode configuration as it stopped working properly for me by default. However, when I changed the desktop configuration it worked. I would just add chiaki4deck as a game in game mode and use the gui (you mentioned network problems I’m assuming had to do with the automation). Then choose chiaki4deck+ controller template and it all should work. Alternatively, save chiaki4deck+ as a template in game mode and use it in desktop mode. Anyway, the issue seems to be that the default controller layout for desktop mode was changed by Valve and doesn’t have a controller mapping so you either have to do it yourself or use game mode.

**Comment by datnodude** [comment]
I did set up chiaki on the game side some while ago using the guide.
whenever I try to use it the steam logo just spins, so I stick to desktop
mode. desktop mode works after I toggle my WiFi on and off then the
registered system shows up. I know it's a big ask, but could you share the
proper config on steam so I can grab it?

**Comment by streetpea** [comment]
Did you set it as your config for desktop mode and make sure that Steam is running (control configs don’t work properly I believe without Steam running on Steam Deck)? When I add that config to my Steam Deck in game mode it works properly so I think it must be something specific to your Deck if you are setting the config in desktop mode correctly (I.e. Open steam go to settings -> controllers -> desktop mode configuration and then choose the right config and chose to apply it).

**Comment by datnodude** [comment]
that worked, thanks. right-pad is super sensitive but I can at least navigate in game. thanks for the support

**Comment by streetpea** [comment]
@datnodude in that control scheme gyro is activated when you touch the right analog stick so maybe that is the issue? (You can always turn this off). If not, you can adjust the acceleration/sensitivity of pretty much any control using Steam Input (though may have to dig through a few menus depending on the control) if the default is bothering you.

**Comment by streetpea** [comment]
@datnodude can this be closed or is there something else for this issue?
