### ISSUE TITLE
[REQUEST] Allow using the Enter key to confirm Console Login PIN entry

### ISSUE THREAD

**Issue by RynO-SauruS** [streetpea/chiaki4deck#371]
**Description**
Currently when entering the Console Login PIN, pressing the Enter key does nothing, and you must click the OK button on the screen to proceed.

**Describe the solution you'd like**
Login would be much faster if you could simply press the Enter key to continue.

**Additional context**
![Console_Login_PIN_Entry](https://github.com/user-attachments/assets/fe37ebf6-090d-4d97-9b3f-5e34065d7420)

**Comment by streetpea** [comment]
@RynO-SauruS you can add the pin to your console in the home menu of Chiaki4deck (when your chosen console is selected use update pin I believe or something along those lines) then you don’t need to enter it at all.

**Comment by RynO-SauruS** [comment]
> @RynO-SauruS you can add the pin to your console in the home menu of Chiaki4deck (when your chosen console is selected use update pin I believe or something along those lines) then you don’t need to enter it at all.

Yes, I understand it can be saved but I just preferred not to save it due to it being stored in plaintext and just for security in general.

**Comment by RynO-SauruS** [comment]
Awesome thanks!!
