### ISSUE TITLE
[BUG] PSN credentials expired and no notification received

### ISSUE THREAD

**Issue by L0WR1D3Rz** [streetpea/chiaki4deck#373]
Yet again remote play doesn't work when not in home network. I'm on a different wifi in a different country. While the console turns on fine using my mobile phone with the official app while connected on the same network/wifi here, my steam deck and gpd win 4 with their respective chiaki4deck versions don't see the Console. Pity after so long this still isn't fixed, it would've been an awesome feature! 

P. S. Both devices have the latest version of chiaki4deck 1.7.3 installed and both devices could see see the console just fine when in the same home wifi.

**Comment by streetpea** [comment]
This isn’t a bug. It is working as intended. The underlying method used (UDP holepunching) doesn’t support all network types.

**Comment by L0WR1D3Rz** [comment]
Pity. I guess there is no fix for this right?

Angelo Karaiannis
Mob: +41 79 278 00 25
email: ***@***.***

**Comment by streetpea** [comment]
If you are able to use the same network with the official app there is possibly something that could be done. However, it’s likely that you are SOL and will need to use manual port forwarding for that network.

**Comment by L0WR1D3Rz** [comment]
I'm not sure what for mean. I used official app on mobile on same wifi as
the handhelds. Is where still some variable that makes the official app use
it differently?

Angelo Karaiannis
Mob: +41 79 278 00 25
email: ***@***.***

**Comment by streetpea** [comment]
Does the official app on windows or Mac work with this network? If it does then we could possibly support this network.

**Comment by L0WR1D3Rz** [comment]
I'll test and report back. I tried with the official android app with my
mobile using the wifi.

Angelo Karaiannis
Mob: +41 79 278 00 25
email: ***@***.***

**Comment by L0WR1D3Rz** [comment]
Hello. I see you marked it as closed however it isn't really closed.
I just tried with official remote play app on windows pc from same remote wifi (meaning not the same as the one the ps5 is connected to) and it worked on first attempt. Chiaki4deck doesn't even see it. Of course I use the exact same wifi network.

**Comment by streetpea** [comment]
There should be an automatic remote connection via psn tab for it.

**Comment by L0WR1D3Rz** [comment]
What do you mean? Where exactly?

Angelo Karaiannis
Mob: +41 79 278 00 25
email: ***@***.***

**Comment by L0WR1D3Rz** [comment]
Ok update.. It was a token problem. I refreshed the tokens on both devices (went through the process of clearing and logging in again on both) and now they see the console again and can connect. Very weird. Can tokens expire?
