### ISSUE TITLE
[Feature Request] Enable oneclick / controller support for chiaki playstation selection screen

### ISSUE THREAD

**Issue by cmalvi** [streetpea/chiaki4deck#4]
As title, could be an appreciate improvement even if not critical to add quality of life to the app. Thanks in advance

**Comment by siler23** [comment]
Have you tried the automation? This bypasses the menu entirely. If you have multiple consoles you can make a script for each console. See https://streetpea.github.io/chiaki4deck/setup/automation/ if you haven’t. This requires 0 clicks after opening chiaki4deck.

**Comment by cmalvi** [comment]
i preferr use the menu, thanks

> Have you tried the automation? This bypasses the menu entirely. If you have multiple consoles you can make a script for each console. See https://streetpea.github.io/chiaki4deck/setup/automation/ if you haven’t. This requires 0 clicks after opening chiaki4deck.

**Comment by streetpea** [comment]
Hmm, ok. I'll look into this after all other features I have planned are implemented. I think controller navigation of the UI could be generally useful. As for one click support, I'm against that because it conflicts with Chiaki (which explicitly declares double click instead of single click). Also, if controller navigation is enabled double click should be very easy to use.

**Comment by chrissi323** [comment]
I'd love to have controller navigation. The automation causes problems if the Playstation isn't on the same subnet. 

As far as I can see, the discovery is done by a broadcast which doesn't work if you're outside your network or have the playstation for whatever reason on a different subnet. If the discovery fails, the automation script fails.

As a workaround you can use the existing Steamdeck shortcuts for navigating the GUI:

STEAM+rightt Stick = Mouse
STEAM+R2 = right mouseclick
STEAM+R1 = left mouseclick

It's a bit awkward but works and allows to keep the custom controller layout. I use it to manually send a wakeup packet to my PS5 and connect afterwards by using a double-click.

Another option would be to use the left trackpad as a mouse and sacrifice the touchpad click for the PS-Button. In this case one could use STEAM+DPad left which is mapped to ESC which is mapped to the PS-Button in chiaki. But this combination is megaawkward :-)

**Comment by streetpea** [comment]
@chrissi323 the automation works for external networks, you need to add the appropriate external ip or hostname. Right now the automation script creation script doesn’t support a hostname but that will change. The ui also requires adding an appropriate ip or hostname.

**Comment by chrissi323** [comment]
@streetpea You're right, it works.... at least on my internal networks. 

The most common way in making it work from external is by portforwarding. I'm not really comfortable with that, but Wireguard also works great, didn't try it on the deck yet.

**Comment by streetpea** [comment]
one-click controller support added with release 1.6.0
