### ISSUE TITLE
Unable to set up chiaki4deck with PS4 on wired connection

### ISSUE THREAD

**Issue by wordprank** [streetpea/chiaki4deck#41]
Hi there, I asked about this in the Steam Deck subreddits but this app seems to work fine for everyone else. Any help would be much appreciated!

For some reason I'm just not able to get my PS4 and Deck to recognize each other. My PS4 is connected directly to my router via an ethernet cable. However, when I try to register my PS4 in chiaki4deck with the remote play PIN, I can an error message saying "received HTTP code 403", "Reported Application Reason: 0x80108bff (unknown)", and that "Regist eventually failed". 

I'm following all the instructions: host has the IP address of the PS4 unit, I've selected PS4 Firmware < 7.0 (my PS4 is running 10.something), have entered my case-sensitive PSN online ID accurately, and have entered the PIN from "Add Device" in the PS4's remote play connections settings. Not sure if this is relevant, but the "PSN-Account-ID (base64)" box is greyed out for me and I'm not able to add it.

Would love to be able to solve this one. Thanks in advance!

**Comment by wordprank** [comment]
Bumping to add that I was able to add the PS4 when I connected it to WiFi, but it is no longer accessible once I switch it back to ethernet connection.

**Comment by streetpea** [comment]
It sounds like it’s not accepting your registration. Given your firmware is 10. I think you should be using account id instead of ps online id (you’ll get this if you don’t select ps firmware < 7) since your firmware is greater than 7 (I.e., 10 > 7) in order to get your account id follow [this section](https://streetpea.github.io/chiaki4deck/setup/configuration/) using the tab new to using Chiaki on Steam Deck.

**Comment by wordprank** [comment]
Thank you! I managed to get it registered, but it now won't boot up with the automated script. I can connect just fine when in SteamDeck's desktop mode, but for some reason the chiaki4deck app in my library in game mode just hangs. Any suggestions on how to fix this new issue?

**Comment by streetpea** [comment]
Can you try ysing the automated script to launch it in desktop mode using the following command in the konsole: "${HOME}/.var/app/re.chiaki.Chiaki4deck/config/Chiaki/Chiaki-launcher.sh"

**Comment by wordprank** [comment]
This also does not work unfortunately. It says to double check that my PS4 and Deck are on the same network, which they are – double-clicking my Playstation in the Chiaki4deck window in desktop mode launches remote play just fine, it's now just the script itself that won't connect.

**Comment by streetpea** [comment]
Are you using the right ip? You can double check by looking at the GUI. Also try `ping -c3 ip` where ip is the given ip.

**Comment by wordprank** [comment]
Yes, it's the right IP; that ping command returns information about bytes of data, so I assume it means it connects to it just fine?

**Comment by wordprank** [comment]
And here's what I get when I run the ping command just suggested:
![IMG_8696](https://user-images.githubusercontent.com/123257130/213884363-f61aac39-b91b-410b-92ab-520e196cade4.jpg)

**Comment by streetpea** [comment]
The picture is just the script not running the script …

**Comment by wordprank** [comment]
Not sure what you mean...

**Comment by streetpea** [comment]
You run the script by typing
```
"${HOME}/.var/app/re.chiaki.Chiaki4deck/config/Chiaki/Chiaki-launcher.sh"
```
Into the konsole

**Comment by wordprank** [comment]
Yes. I did that. Also does not work. I'll try and get a picture in a second.

**Comment by streetpea** [comment]
Like you did with ping command but use that command instead … what you posted is the first several lines of the script itself which has functions that trigger on errors …

**Comment by wordprank** [comment]
Here is the result of the script you just suggested (bottom most area of the screen):

![IMG_8695](https://user-images.githubusercontent.com/123257130/213884559-14c9b190-4dd9-44dc-8153-43fea70114b1.jpg)

**Comment by streetpea** [comment]
Hmmm 38. isn’t a local subnet …. Should be 10. 172. Or 192.

**Comment by streetpea** [comment]
That’s the ip it shows in the gui?

**Comment by wordprank** [comment]
Interesting...yes, that's the IP address in the GUI (which connects fine!) and as it shows up on my PS4 itself

**Comment by wordprank** [comment]
Is it possibly because my PS4 is connected to ethernet rather than WiFi?

**Comment by streetpea** [comment]
Maybe based on your wifi settings… when you connect via wifi does it give a different ip (specifically does it give one starting with 10. 192. Or 172.)? Note: I deleted the images of your ip because it does seem to be public and accessible via the internet as opposed to a private address which doesn’t mean anything out of your local network.

**Comment by wordprank** [comment]
Thank you! Yes, it did give a different IP, one that starts with 192. Unfortunately I can't use this reliably, since my PS4 drops WiFi signal pretty regularly and ethernet is the only reliable connection. Any workarounds for this?

**Comment by streetpea** [comment]
Can you set a reserved ip for your device following this for your router: https://www.coolblue.nl/en/advice/assign-fixed-ip-address-router.html and then try using that address (in 192. range let’s say)

**Comment by wordprank** [comment]
Thanks for the suggestion – I disconnected my ethernet cable linking my PS4 to the modem and plugged it into the remaining LAN port on my wireless router instead, which then gave the PS4 an IP beginning with 192. This seems to have resolved it! Thank you very much for the help and troubleshooting!
