### ISSUE TITLE
Trigger Issue in Astro

### ISSUE THREAD

**Issue by Drumdude26** [streetpea/chiaki4deck#42]
First, thank you for the awesome work all have done on this project. 

The issue I am having is related to Astros playroom when streaming my ps5 on Steamdeck. When I try to play the part with the monkey suit, there is a place where you have to break through a rock in order to keep climbing. Specifically, the rock is purple, where the user has to do more than just climb. Natively on the ps5 I think this is done by a hard right trigger press. I checked my steam triggers and they are both coming up good on the pressure sensitivity test. Is this a known issue or perhaps a glitch on my end?

**Comment by streetpea** [comment]
I think you need experimental ps5 features enabled for this to work atm

**Comment by Drumdude26** [comment]
That worked, thanks a lot. So just for anyone that sees this in the future, you have to open chiaki in desktop mode, go to settings and enable experimental features.

**Comment by streetpea** [comment]
@jbaiter this is due to this: https://github.com/streetpea/chiaki4deck/blob/main/lib/src/feedback.c#L84 right?

Is there a downside to using 
buf[0x1b] = enable_dualsense ? 0x1 : 0x1 instead?

(since right now Astro’s and potentially other games aren’t fully playable if dualsense enabled is not set)

would making that change break something on PS4?

**Comment by jbaiter** [comment]
I haven't actually tested that with a DS4 😬😬
Might be worth a shot, I have no clue what that flag precisely does tbh, but it was necessary to set it to `1` to fix those purple triggers in Astro when using a DualSense.

**Comment by streetpea** [comment]
Yea if I set it to 1 the purple triggers work with the Steam Deck controller, so setting
`buf[0x1b] = 0x1` instead of making it conditional would allow this to work either way.

**Comment by jbaiter** [comment]
👍🏾 Curious to see if there are any side-effects from that, maybe we'll learn more what that flag actually does :-)
