### ISSUE TITLE
Ghost of Tsushima Rumble Hints Only Work When Experimental PS5 Features Are Enabled

### ISSUE THREAD

**Issue by xCISACx** [streetpea/chiaki4deck#43]
I'm not sure if this is a Chiaki or a Steam Deck issue but I noticed that the little rumble hints you get in Ghost of Tsushima when near an artifact and wearing the Traveller's Set only work on the Steam Deck if Chiaki has the haptics turned on.
However, this makes it so everything else creates haptics, making it hard to concentrate on the rumble hints or distinguish them from everything else.

Is it possible to separate them by any chance so that the haptics don't need to be on for them to work? Or is it an issue with the way the Steam Deck handles rumble in general?
I should also add that using Chiaki on my PC with a DualSense connected to it made the hints very easy to feel without any other haptics getting in the way, but that might just be due to the DualSense.

Thanks.

**Comment by xCISACx** [comment]
Thank you for the detailed write-up.

I think I understand now that they are most likely not rumble and haptics instead.

Looking at the thread you sent, it really seems like a filter would be the best solution so the footsteps and menu sounds can be filtered out while keeping the hints functional. 
I remember doing something similar with VoiceMeeter and adjusting frequency ranges to simulate haptics for games that didn't have them on PC and it worked quite well.
Maybe an experimental version with that Haptic Low-Pass Filter toggled would be something good to try out as well?
I'd test as many games as I could with it.

Keep up the great work!
I'll be looking forward to the improvement of Chiaki4Deck :)

**Comment by streetpea** [comment]
The haptic low-pass filter has been added as well as an option that isn't noisy
