### ISSUE TITLE
Gyro from external controllers

### ISSUE THREAD

**Issue by cgarst** [streetpea/chiaki4deck#45]
With the excellent addition of deck gyro, a useful next step would be a way to use the gyro from a connected DS4, DualSense, or Switch controller.

**Comment by streetpea** [comment]
This is already done. You have to disable Steam input for the controller for this to work. See https://streetpea.github.io/chiaki4deck/setup/controlling/#using-a-dualsense-andor-dualshock4-controller-with-chiaki4deck

**Comment by cgarst** [comment]
Amazing - thank you!
