### ISSUE TITLE
Possible solution for Chiaki4Deck freezing every few minutes

### ISSUE THREAD

**Issue by tvidal-net** [streetpea/chiaki4deck#46]
So, I had both chiaki and chiaki4deck freezing on my SteamDeck every few minutes and tried several different suggestions with different video bitrates and audio buffer sizes that I found on reddit but nothing seemed to work.

As an arch linux user, I knew chiaki was working flawlessly on my workstation, so I decided to build Chiaki4Deck from scratch in a Steam OS qemu VM and was surprised to noticed the freezing had stopped. Another advantage is that the console registration information is saved on the home directory and is not lost after reinstallation cycles.

I am not sure why using a locally built executable was more stable than running it from the flatpak, but it was just SO much better. I created a small [gist](https://gist.github.com/tvidal-net/dda93291eb5898d43ae268e063c928be) with instructions on how to build it from source directly from the SteamDeck or a Steam os VM. I thought maybe I should share here as it may be helpful for someone else. I apologise in advance if that is not the case.

Cheers!

**Comment by streetpea** [comment]
Thanks for writing that up and posting it @tvidal-net. It’s a little difficult for me to check bc I’m not experiencing any issues with freezing on my end (besides not physically noticing it I also don’t have the messages in the logs that are indicative of this happening while a small amount of people have posted some logs that clearly show that they are having problems with this that I’m not able to replicate). Having said that, I can look and see what’s different between this and the flatpak as for what could possibly be causing a performance difference for you. I would think the only changes would be network permissions and dependency package versions (most packages are the latest but some are just the version provided by freedesktop os vs arch Linux). 

If I did so, would you be able to test it? (Since I’m not having problems to begin with, I wouldn’t really be able to see if a new build helped the problem at all myself).

**Comment by tvidal-net** [comment]
Thanks for your reply. I do have some linux experience and I can definitely try to reproduce it again and get some logs for you... let me know if there is anything else I can do to help.

**Comment by streetpea** [comment]
That could be helpful. Something to check logs against would be this issue (to see if they are similar if it what you are experiencing is different in nature https://github.com/streetpea/chiaki4deck/issues/39)

**Comment by streetpea** [comment]
Additionally, as for the config, for flatpaks it’s saved in your home directory under the .var/app/appid directory where appid is re.chiaki.Chiaki4deck for chiaki4deck. This isn’t deleted during uninstallation or system updates (unless you manually do so). In general flatpaks are preferable for Steam Deck and what are recommended for SteamOS, especially with potential for things to get overwritten during steam os updates (client updates are fine but SteamOS updates can delete manually installed packages) as well as just being easier to deal with / less scary for people with little Linux experience imo (which is the case for a lot of Steam Deck users specifically). Thus, I would like to improve the flatpak version looking at what you have in the native build to see what’s different as a starting point. In the meantime, the instructions you provided would be helpful if someone is having the same issues and is comfortable with going through them.

**Comment by pyrostic** [comment]
Is there going to be any movement toward fixing this? I've followed the guide and get much better performance. Again not sure why.

**Comment by calculuschild** [comment]
@streetpea Is there a chance this could be implemented? Are you still waiting on @tvidal-net to provide some logs? I was able to follow his steps but it's pretty annoying to re-do it every time SteamOS updates.

**Comment by streetpea** [comment]
@calculuschild I stopped working on chiaki4deck to deal with other things but I'm starting to work on it again so I'll take a look at this and look to have an answer by next week.

**Comment by calculuschild** [comment]
That would be amazing! Good luck!

**Comment by fede118** [comment]
Hello! reviving this oldish thread because im getting freezes every minute for about 3-5 seconds aprox. I tried following @tvidal-net  gist but couldnt make it work. I had to download a bunch of other decencies (like more than 10) for nothing because I wasnt able to install it. The last error I got was :

`chiaki4deck fatal error: linux/errno.h: No such file or directory26 | # include <linux/errno.h>`

Here is my log (its from a less than 3 or 4 minutes in which it froze 2 or 3 times):
file:///home/deck/.var/app/re.chiaki.Chiaki4deck/data/Chiaki/Chiaki/log/chiaki_session_2023-05-31_22-09-20-731731.log
Im guessing the important part is this:
```
[2023-05-31 22:09:40:848848] [E] FEC failed
[2023-05-31 22:09:40:848848] [W] Missing unit 0x1
[2023-05-31 22:09:40:848848] [W] Missing unit 0x2
[2023-05-31 22:09:40:848848] [W] Missing unit 0x3
[2023-05-31 22:09:40:848848] [W] Missing unit 0x4
[2023-05-31 22:09:40:848848] [W] Missing unit 0x5
[2023-05-31 22:09:40:848848] [W] Missing unit 0x6
[2023-05-31 22:09:40:848848] [W] Missing unit 0x7
[2023-05-31 22:09:40:848848] [W] Missing unit 0x8
[2023-05-31 22:09:40:848848] [W] Missing unit 0x9
[2023-05-31 22:09:40:848848] [W] Missing unit 0xa
[2023-05-31 22:09:40:850850] [V] Ctrl received message of type 0xfe, size 0
[2023-05-31 22:09:40:850850] [I] Ctrl received Heartbeat, sending reply
[2023-05-31 22:09:40:850850] [V] Ctrl sending message type 1fe, size 0

[2023-05-31 22:09:40:858858] [W] Detected missing or corrupt frame(s) from 599 to 600
[2023-05-31 22:09:40:859859] [D] StreamConnection reporting corrupt frame(s) from 599 to 599
[2023-05-31 22:09:40:859859] [V] Pushed seq num 0x7a38ba7a into Takion Send Buffer
```

anyone could help me out please?

**Comment by streetpea** [comment]
@fede118 it looks like you're running into general network performance issues (dropped packers) causing the stuttering.

**Comment by streetpea** [comment]
@calculuschild I tried to run through the instructions but got a key error trying to install python-setuptools ... can you run `pacman -Qi chiaki4deck-git` on your Steam Deck with chiaki4deck installed as a package and then get the version number for each dependency? I also will need someone's help with this as I'm not able to replicate the issue on my machine so I can't exactly test if what I do (regarding package versions, etc.) fixes the problem.

**Comment by streetpea** [comment]
Flatpak versions:
- qt5 5.15.10
- sdl2 2.26.1
- opus 1.4
- ffmpeg 5.0.3
- openssl 3.0.8
- gcc 12.2.0
- fftw 3.3.10
- libva-mesa-driver 23.1.1

**Comment by streetpea** [comment]
@calculuschild I updated ffmpeg libraries used by chiaki4deck to 6.0. You should see an update now to try. Let me know if this helps your issue at all. 

```
flatpak info re.chiaki.Chiaki4deck
```

should show version: 1.3.2 after updating

**Comment by musicfortea** [comment]
I still get video freezing after installing 1.3.2. 
Buttons still work so I can usually pause the game. Then I have to exit the app, reopen and connect again, 20 minutes later it happens again.

**Comment by calculuschild** [comment]
Unfortunately I continue to see the same issue. I wonder if @tvidal-net has any further insight, since a slight bump in the FFMpeg version seemed like a longshot anyway.

(apologies, I thought I had replied here already but apparently not).

**Comment by musicfortea** [comment]
I managed to get the flatpak version off discovery working almost flawlessly. After 10 hours of streaming I have had 1 crash. It was my router that was causing it, there are 3 modes to the router I own - mode 1 being the newest which has power management, mode 2 being a step down and meant for older devices, and mode 3 which is for legacy stuff. Selecting mode 2 fixed it, restarted the router, cleared proton files for chiaki4deck and rebooted the deck. The only issues I found running mode 2 is slightly reduced wifi range and slight drop in performance. It also fixed my older sonos speakers.

There's a short video here I found which I followed https://m.youtube.com/watch?v=a6g0pMQRT_U

**Comment by streetpea** [comment]
There is now an appimage version of chiaki4deck. If you were having issues with the flatpak version such as @calculuschild it might be worth a try to use the newly added appimage version. Just download it from the releases page. Move it into your home folder and make it executable with chmod +x Chiaki4deck.AppImage and then launch it with ./Chiaki4deck.Appimage / add a Steam shortcut for it and see if that is any better.

**Comment by tvidal-net** [comment]
Well, I added a pre-built (using a SteamOS vm), statically linked version of `chiaki4deck` to my [own github repo](https://github.com/tvidal-net/chiaki4deck-build), maybe this will help anyone who's still struggling with the flatpak version.

**Comment by HamzaM** [comment]
> There is now an appimage version of chiaki4deck. If you were having issues with the flatpak version such as @calculuschild it might be worth a try to use the newly added appimage version. Just download it from the releases page. Move it into your home folder and make it executable with chmod +x Chiaki4deck.AppImage and then launch it with ./Chiaki4deck.Appimage / add a Steam shortcut for it and see if that is any better.

That worked for me ! The flatpak version didn't work either set to vaapi or "none", no matter the bitrate and resolution.
The .appimage though worked well in terms of stability, no freeze or anything but it's set to "none" and i can't use vaapi unfortunately so it gives me these weird white flashing glitches.

**Comment by Sweetcheezus** [comment]
I get the same message when trying to use vaapi - "Failed to initialize Stream session: Failed to initialize FFMPEG Decoder: Trying to use hardware decoder "vaapi". The .appimage version seems more stable than flatpak so if there is a way to use vaapi for the .appimage version of Chiaki4deck, it'd be really awesome to know.

**Comment by hvmzx** [comment]
> I get the same message when trying to use vaapi - "Failed to initialize Stream session: Failed to initialize FFMPEG Decoder: Trying to use hardware decoder "vaapi". The .appimage version seems more stable than flatpak so if there is a way to use vaapi for the .appimage version of Chiaki4deck, it'd be really awesome to know.

Do you get those white flashes as well ? That's my only issue, the rest works fine, no freezing for me. But this issue could probably be resolved using vaapi

**Comment by hvmzx** [comment]
I unfortunately cannot perform the changes you mentioned above as my router is from my internet provider.

But this worked for me and it fixes everything : https://github.com/streetpea/chiaki4deck/issues/103#issuecomment-1846414293

**Comment by Sweetcheezus** [comment]
Glad you found something that worked! I actually tried that step and it didn't work for me which is another reason I believe it was my router settings. Hopefully our posts help others with similar issues.
