### ISSUE TITLE
[Feature Request] Support multiple PSN ID

### ISSUE THREAD

**Issue by NICHOLAS85** [streetpea/chiaki4deck#51]
I share a PS5 with another person and would like to be able to connect to each account via Chiaki4deck individually. Manually adding a second entry in the QT GUI with the second PSN ID info creates a new entry to use, however both of these entries log into the first configured account. It doesn't seem to be possible to connect via another account.

**Comment by lekebrett** [comment]
Im looking for this exact same thing myself - really hope it can be added!

**Comment by streetpea** [comment]
A workaround now is to use the `--profile` option when launching Chiaki4deck. If you specify a different file for both users and register user1 with --profile user1 and then register user2 with --profile user2 you can access each user separately.

**Comment by GJQ-FUN** [comment]
> 现在的解决方法是在启动 Chiaki4deck 时使用该`--profile`选项。如果为两个用户指定不同的文件，并使用 --profile user1 注册 user1，然后使用 --profile user2 注册 user2，则可以单独访问每个用户。

Do you mean we need create two system users? haha it's sounds a little bit troublesome，hoping there is a simple soulution in future

**Comment by GJQ-FUN** [comment]
> A workaround now is to use the `--profile` option when launching Chiaki4deck. If you specify a different file for both users and register user1 with --profile user1 and then register user2 with --profile user2 you can access each user separately.

Do you mean we need create two system users? haha it's sounds a little bit troublesome，hoping there is a simple soulution in future

**Comment by Jdj67** [comment]
> A workaround now is to use the `--profile` option when launching Chiaki4deck. If you specify a different file for both users and register user1 with --profile user1 and then register user2 with --profile user2 you can access each user separately.


I was able to add the profile tag when launching from konsole, and it seems to now have its own config compared to launching from Konsole without a profile tag, but how would I then launch it from steam game mode?

Is this as simple as going to game properties for the chiaki4deck tile in steam game mode, adding “—profile user 1” to the game launch options, and repeating for additional users, or am I missing some steps? When I attempted this, chiaki4deck wouldn’t launch..

**Comment by GJQ-FUN** [comment]
> > A workaround now is to use the `--profile` option when launching Chiaki4deck. If you specify a different file for both users and register user1 with --profile user1 and then register user2 with --profile user2 you can access each user separately.
> 
> I was able to add the profile tag when launching from konsole, and it seems to now have its own config compared to launching from Konsole without a profile tag, but how would I then launch it from steam game mode?
> 
> Is this as simple as going to game properties for the chiaki4deck tile in steam game mode, adding “—profile user 1” to the game launch options, and repeating for additional users, or am I missing some steps? When I attempted this, chiaki4deck wouldn’t launch..

Well, I success in game mode but don't meet this problem. My solution is creating a new chiaki shortcut in desktop and add it into steam, then add "--profile user1" in the end of starting parameter so i can use 2 psn id in 2 chiaki software.

**Comment by neilio** [comment]
> A workaround now is to use the --profile option when launching Chiaki4deck. If you specify a different file for both users and register user1 with --profile user1 and then register user2 with --profile user2 you can access each user separately.

Can you be more specific here? I got multiple accounts working under the old system but am not sure what I'm missing here. I have three different launcher files with three different remote play registration keys (after adding the PS5 as a new consoles with remote codes created in each user) but I don't know what you mean by "--profile user1"

**Comment by streetpea** [comment]
I mean either create a Steam shortcut with the Create Steam shortcut button and add --profile user1 as the launch arguments or launch manually with flatpak run io.github.streetpea.Chiaki4deck --profile user1

**Comment by Jdj67** [comment]
> I mean either create a Steam shortcut with the Create Steam shortcut button and add --profile user1 as the launch arguments or launch manually with flatpak run io.github.streetpea.Chiaki4deck --profile user1.
> 
> If you are using autoconnect or just opening chiaki manually leave it at that. If you are using a customized automation script (autoconnect or manually opening chiaki don't meet your needs) then add --profile user1 after flatpak run io.github.streetpea.Chiaki4deck

Thanks! Figured it out, had to use an = sign instead of a space into launch arguments, “--profile=user1”. Works perfect.

Having some issues getting controller profiles to stick when I rename the shortcut to something other than “chiaki4deck”, but that’s probably a steam issue. Maybe I’ll keep the names the same but just give it a different icon as a workaround to be able to tell the difference between profiles.

**Comment by streetpea** [comment]
@Jdj67 If you use the option to create the steam shortcut from within Chiaki4deck and set the arguments to --profile=user1 the controller profile with be copied properly.
