### ISSUE TITLE
[Feature Request] More Gyroscope Tuning

### ISSUE THREAD

**Issue by JimmJam** [streetpea/chiaki4deck#53]
I noticed the gyroscope when using the Steam Deck feels a lot slower than using a DS4 natively to a PS4. Mostly though, I noticed left/right aiming only seems to support yaw and pitch, but not roll. 
Having some kind of gyro sensitivity slider or option to use both roll and yaw or one or the other could be nice to more accurately emulating the DS4.

**Comment by streetpea** [comment]
Roll works as well in my testing (unless something has changed) but whether or not roll is being used is up to the game and the config it has for PlayStation. Some games use roll, most just use yaw for aiming for the PlayStation version. Maybe you want something like #54? If not, can you clarify what you would like? As for sensitivity, most games have that in game and you can adjust the sensitivity overall in the Steam Deck settings, though other tuning options could technically be added.

**Comment by JimmJam** [comment]
Would a video to help demonstrate my proposed behavior be appropriate to provide here?

**Comment by JimmJam** [comment]
Just figured it out. The gyroscope on a lot of games on the PS4 seems to assume a forward facing controller, pointing towards a TV for example. With the steam deck, being an upward facing device, screen pointing towards you, it treats it as such. My original post being mistaken, I revise it to wonder if it would be possible to, in software, add an artifical "tilt" to the sent gyro input?

**Comment by szszoke** [comment]
#54 is really only about completely inverting certain gyro axes but I think here we're talking about offsetting them with a value that is somewhere between zero and the full range of the gyro response.

**Comment by JimmJam** [comment]
An offset I think would be good to make the console think you're "pointing the controller to the TV" as is intended for some games like The Last of Us, not sure how easy to implement that would be but it would be very appreciated

**Comment by szszoke** [comment]
If it's only the gyroscope that is being used and not gyro + accelerometer (maybe someone who knows more can chime in) then it is the pitch angle that needs to be offset. How the different games will handle that.. I don't know. Untill you move your Steam Deck into playing position, it will look like your controller is positioned with the trigger/shoulder buttons facing the floor.

**Comment by JimmJam** [comment]
I think that behavior sounds right and would at least fix the deck being "pointed" the right way to match the behavior of a normal controller.

**Comment by streetpea** [comment]
Given you are using vertical orientation you want to use roll instead of yaw gyro for movement right? That's what makes sense to me but if you would still like to use yaw when in vertical orientation I can separate the 2 options (swapping accelerometer and swapping gyro).
