### ISSUE TITLE
DS5 latency

### ISSUE THREAD

**Issue by chanksworld** [streetpea/chiaki4deck#59]
So this used to work with no issue, I can't pinpoint when exactly but the latency when trying to play with Dualsense is way too high to be playable. Using the SD controls is flawless though . 
Is there anything I should be checking for?

**Comment by chanksworld** [comment]
@jbaiter 
• connected via Bluetooth (always was)
• I can navigate the steam deck UI and play other games flawlessly

**Comment by streetpea** [comment]
Unfortunately, I don't think there's really anything that we can do to fix that on the Chiaki4deck end.
