### ISSUE TITLE
Add native touchpad (touchscreen) support for Steam Deck itself

### ISSUE THREAD

**Issue by streetpea** [streetpea/chiaki4deck#6]
Add support for the Steam Deck touchscreen to perform touchpad gestures (such as swiping for the guiding wind in Ghost of Tsushima).

**Comment by ejleslie** [comment]
Super exciting that you're doing work on this - thank you! Any chance you might pursue adding haptic feedback as well? Chiaki's lack of interpretation of rumble from the PS5 is a bit of a bummer. :)

**Comment by streetpea** [comment]
@ejleslie I closed this issue because the touchscreen support is done but if you want you can add an issue for the haptic feedback. Also, if you do want to create a new feature issue can you clarify what you want haptic feedback for (i.e., the DualSense controller or the Steam Deck controller?

**Comment by ejleslie** [comment]
@streetpea Will do! I had meant on the deck since that seems to be the sole focus of this fork but if support could be added for the dualsense also that'd be amazing, is that on the table?
