### ISSUE TITLE
Resident evil 4 on PS5 - touch button

### ISSUE THREAD

**Issue by vavasjc** [streetpea/chiaki4deck#62]
Several people including myself has been having an issue where when connecting to PS5 and playing - specifically - re4 remake have not been able to call the map through touch button. Touch button is mapped to right touch on SD (T or left mouse button in layout). When you connect on PS5 using dual sense after this happens, even in dual sense playing directly you can't call the map. You must turn off and on your dual sense
Sometimes when you restart your PS5 / SD it works on Chiaki4Deck, but it's hit or miss.

I don't know if that's a Capcom bug or Chiaki bug. Wouldn't be surprised if that for subtle fixed after a game update

**Comment by Lenksi** [comment]
Is not chiaki issue is remote play issue. Streaming on Steam Deck there is a workaround - you can map a button press to trigger - triangle and 2 times L1 which will open the map. You need to map it with trigger and stop delays. Feels almost as a normal map open.

**Comment by streetpea** [comment]
Since this is a remote play bug, I'll close this since it's not something we can fix.
