### ISSUE TITLE
Volume Boost

### ISSUE THREAD

**Issue by chanksworld** [streetpea/chiaki4deck#64]
So I've noticed the volume in Chiaki is significantly lower than any other app or system volume on deck. Is this something that can be tweaked? Maybe In the options menu

**Comment by streetpea** [comment]
You can change your overall Steam Deck system volume. You can also adjust the volumes of the streamed gaming using in-game sound options (depending on the game it may be set low). I think that may help since it is plenty loud for me so it may be game-specific.

**Comment by darrenhaken** [comment]
Is there any actual solution to this? Chiaki4deck is vastly lower in volume that other games on the steam deck. It would be awesome to resolve.
