### ISSUE TITLE
PS5 Not Detected Even After Reboot

### ISSUE THREAD

**Issue by apharrison964** [streetpea/chiaki4deck#65]
Hi,

My PS5 wasn’t detected, even after rebooting the Steam Deck a few times. I added the PS5 manually, but now it won’t connect to the console unless it’s on (not in rest mode). Is anyone else having this issue?

**Comment by streetpea** [comment]
Have you made sure to set the required settings on the PS5 console.

If you haven't already, go to Settings -> System -> Power Saving -> Features Available in Rest Mode and turn on:

- Stay Connected to the Internet
- Enable Turning on PS5 from Network

See [New to Using Chiaki on Steam Deck](https://streetpea.github.io/chiaki4deck/setup/configuration/#registering-your-playstation) in the guide.

**Comment by apharrison964** [comment]
I do have those settings on and followed the guide - the PS5 wasn’t showing
up so I added in manually. If I right click and manually click on the send
wake-up packet option it works! Just not in the game mode but that’s no
problem. Thanks for all the great work!

**Comment by apharrison964** [comment]
I had somehow not pointed to the launcher for the shortcut! Thanks so much
for the tip, it works perfectly now! So cool!
