### ISSUE TITLE
Chiaki4deck Ctrl unable to obtain session id 

### ISSUE THREAD

**Issue by balcombits** [streetpea/chiaki4deck#68]
When I run chiaki4deck, my ps5 connects, turns on, logs in, and on the deck the stream window opens for a few seconds, followed by this error:  

Chiaki session has quit: Unknown Ctrl error

I ran the automation script in Konsole to test everything and it failed again but this time I can see the events in Konsole. Two errors are displayed:  

[E] Ctrl did not receive session ID
[E] Ctrl has failed, shutting down

**Comment by streetpea** [comment]
Can you turn on debug logging in the settings menu and paste the log here? 

You can also try putting your PlayStation into sleep mode and then turning it back on and see if that helps (doing that should reset the remote play server on the PlayStation itself)?

**Comment by giancoppola** [comment]
Hey, I also have this issue, attached is my log, do you have any idea what the issue could be? It works every now and then
[log.txt](https://github.com/streetpea/chiaki4deck/files/12547283/log.txt)

**Comment by streetpea** [comment]
fixed by 440b9e9ad0ef47e10f2b4d13844e7e2d588b1f66
