### ISSUE TITLE
Not a issue but a question

### ISSUE THREAD

**Issue by Treyway995** [streetpea/chiaki4deck#70]
Hello, 

Im new to this github thing so please bare with me, i have been using chaiki for a couple of days now, but i had no idea about this updated chaiki4deck thing. I want to know meaning that i already have the base chaiki installed on my steam deck and if i was to copy and paste the flatpack into my terminal will the update automatically apply to to base chaiki or is there something else i would have to do in order to trigger it?.

**Comment by jbaiter** [comment]
From a Flatpak perspective, Chiaki4Deck is a completely different application. So if you install it, it will be installed alongside the vanilla Chiaki. This also means that no settings are carried over, i.e. you will have to configure Chiaki4Deck from scratch.

**Comment by streetpea** [comment]
@Treyway995 you can copy the settings/PlayStation connections from Chiaki by following the [Setup section](https://streetpea.github.io/chiaki4deck/setup/) of the documentation. Specifically, after installation, on the configuration subsection of setup you just need to follow the "Upgrading from Chiaki flatpak on Steam Deck" to copy the configuration file from Chiaki including any connections you setup to PlayStation consoles. Then continue through the other setup sections for additional configuration/tips.

**Comment by Treyway995** [comment]
Thank you so much! I was able to get it up and running, one more question.
what is the best settings if you keep getting white flashes on your screen
or really flashes in general i have been getting it a lot very recently?

**Comment by streetpea** [comment]
In general, that is due to dropped packets from your network connection. Try the suggestions [here](https://streetpea.github.io/chiaki4deck/setup/configuration/#troubleshooting-performance-issues) to try to help with that. Using 5GHz if you aren't already can also help since there is less interference from other devices.

**Comment by Treyway995** [comment]
Thanks, I'll check it out.

**Comment by streetpea** [comment]
Closing since the question has been answered.
