### ISSUE TITLE
如何能联系到window版chiaki作者,按键映射不到触摸板的左边按下和右边按下

### ISSUE THREAD

**Issue by tangyuxian** [streetpea/chiaki4deck#72]
我快愁死了,window版的chiaki无法触摸,无法模拟touchpad的触摸,无法模拟touchpad的左边按下和右边按下,直接导致不少游戏无法玩了,作者说是最终版了,唉,这可咋整啊

**Comment by streetpea** [comment]
Are you talking about the windows version of Chiaki? That's what it looks like from the translation but I want to double check.

**Comment by tangyuxian** [comment]
That's right. I'm not very good at English, try to describe the problem as much as possible. This Chiaki cannot simulate the left and right pressing of a touchpad, with only one button mapping for pressing the entire touchpad. For most PS5 games, it is catastrophic. The original author of the Window version believes that it is the final version. The Switch version and Android version of Chiaki have done a good job, but the Window version of touchpad has not undergone any adaptation processing.

**Comment by tangyuxian** [comment]
I am unable to contact the author of Chiaki in the Window version. Do you know his email? I want to give him feedback on this issue. How does Linux handle touchpad issues on the PS5 controller? I'm about to cry now, please.

**Comment by streetpea** [comment]
There are newer builds that get the touchpad to work on Windows outside of the main project. I believe this one works for example: https://github.com/nlz242/chiaki-qt6/releases/tag/Release2. Have you tried that one?

**Comment by tangyuxian** [comment]
Thank you. I'll try it a little later.

**Comment by streetpea** [comment]
I added a Windows build to the latest release [here](https://github.com/streetpea/chiaki4deck/releases/download/v1.4.1/Chiaki4deck-win_x64-VC-Release.zip). The touchscreen can be used as the touchpad.
