### ISSUE TITLE
Automatically connect to a waking up PS5

### ISSUE THREAD

**Issue by AxelTerizaki** [streetpea/chiaki4deck#73]
Hello.

Thanks for making chiaki4deck ! :)

I have a few ideas to make the experience smoother to new users, and one of them is to automatically connect to a system once you double-click it.

Right now you have to

- Double-click to send the packet
- Answer a question
- Click on OK on the "Packet sent" dialog
- Wait a bit
- Double-click on the system again

I think that a few things would be done to make this easier : 

- Make the "send packet?" dialog optional (as in, there could be a checkbox to disable it, or a "Do not ask me again" button)
- Do not display the "Packet sent" dialog, as I feel like it's not very useful?
- From there, the app could wait like 5-10 seconds, as it's usually the time a PS system needs to wake up (at least on a PS5) and then automatically connect to the woken up system.

Do you think that'd be doable ?

Thanks in advance :)

**Comment by streetpea** [comment]
Have you tried using the automation shell script? See https://streetpea.github.io/chiaki4deck/setup/automation/ for setup.

**Comment by AxelTerizaki** [comment]
I have tried that yet, perfect for the Steam Deck, but I was referring to desktop use where you get welcomed by the PS selection screen, and you have several steps to make before you can connect to it. :)

**Comment by streetpea** [comment]
Implementing this as an option ... Do you like the double-click or would you prefer a single click?
