### ISSUE TITLE
Streaming ps5 display issues

### ISSUE THREAD

**Issue by berlin955** [streetpea/chiaki4deck#74]
Hello, may I ask why the LAN connection PS5, play for a while will be green screen? After refreshing the screen, it will restore, but after a while it will turn green, as if the screen is broken，thank you！

**Comment by streetpea** [comment]
Artifacts may appear when streaming due to the way the protocol works to prioritize responsiveness in gameplay see https://youtu.be/4I9jHjjgkSA?t=1167 for more details.

**Comment by baileyglen** [comment]
I'm having a similar issue. I have realized I only have the issue when steam launches the game. If I run the program from desktop mode I do not have issues. I do not have any compatibility mode selected. Any suggestions?

**Comment by streetpea** [comment]
Have you tried lowering your set bitrate in the settings ... it might help reducing artifacting ... the protocol allows information loss resulting in the artifacting to keep response times as low as possible. If you are getting significant artifacting your network probably can't keep up with your set bitrate...

**Comment by Kelvishi** [comment]
Just got my steam deck and a;sp getting massive green artifacts constantly, This build works fine on my windows machine https://github.com/jbg77/chiaki and it works fine on my phone using psplay

**Comment by darrenhaken** [comment]
Did you get anywhere with this? I used to have zero issues with my Steam Deck LCD. I've moved to the Steam Deck OLED and after maybe 10-20 minutes of gameplay I get severe white and green screens. I have to exit the session and reconnect for it to work.

No lag before the 10-20 min mark.

I'm struggling :(

**Comment by zhen-wang-v** [comment]
Turning off HDR on PS5 seemed to help me. Change it from on to automatic.

**Comment by streetpea** [comment]
This streaming issues should be significantly improved with the last few major updates to Chiaki4deck

**Comment by darrenhaken** [comment]
@streetpea any idea what causes the WiFi to die at about 20 minutes? Chiaki4deck shows the WiFi logo and the stream is unusable. I have to turn WiFi off and on for it to work again. 

It's almost like the device WiFi goes to sleep or there's a buffer filling up in Chiaki4deck or something. Any ideas?
