### ISSUE TITLE
Native gyroscope works only when in Steam menu

### ISSUE THREAD

**Issue by Brojasko** [streetpea/chiaki4deck#77]
Hello, I don't know if I'm doing something wrong, but my gyro works only when I press the Steam button and am in the menu.
Currently, I have not set my gyro to anything in the Steam Input. How do I fix this?
![IMG_20230809_165919](https://github.com/streetpea/chiaki4deck/assets/86663167/a398da46-1347-40c6-b0e2-29bf4142f98f)
Sorry for the low quality image

**Comment by streetpea** [comment]
Hi there. In a Steam update they made it so gyro data is only sent if you have a Steam input gyro setting on if the game is run through Steam (I.e., game mode) For gyro to work set gyro to as mouse or as joystick. (As mouse if you don't want gyro to do anything outside of native gyro as joystick if you want the gyro to be on for games that don't support native gyro)

**Comment by Brojasko** [comment]
Thank you!

niedz., 13 sie 2023, 03:05 użytkownik streetpea ***@***.***>
napisał:
