### ISSUE TITLE
Touchpad

### ISSUE THREAD

**Issue by geenaxion** [streetpea/chiaki4deck#78]
Is it not possible to use the touchpad separately left and right?
This is for dualsense trackpad.

There is only 1 button for touchpad , T button
But in some games the left and right trackpad on dualsense have different function so the chiaki4deck T single button doesn't really work

**Comment by streetpea** [comment]
It's possible ... it's based on where on the touchpad you tap ... tap the left or right of the edge of the Steam Deck screen or push down on the left or right half of the trackpad (tapping on left or right edge of screen is probably easier)

**Comment by streetpea** [comment]
Assuming you are using dualsense it should work if you turn off Steam input for the controller if using Steam Deck ... see https://streetpea.github.io/chiaki4deck/setup/controlling/#enabling-chiaki4deck-to-work-with-dualsense-dualshock-4

**Comment by streetpea** [comment]
It will need to be set like the chiaki4deck+ controller profile, see https://streetpea.github.io/chiaki4deck/setup/controlling/#default-chiaki4deck-layout-trackpad-mapping for details.
