### ISSUE TITLE
No longer connecting to PS5

### ISSUE THREAD

**Issue by Billhixson** [streetpea/chiaki4deck#79]
I've recently bought a 2nd PS5 and it's connected to the same network as the one i connect to with Chiaki. Starting this week, I can't connect to the PS5 anymore. No errors or anything. When I run Chiaki in desktop mode, I can see my registered PS5, but also the unregistered other PS5. I'm wondering if this has something to do with the issue. It won't let me delete it since it's not registered. Anything I can do?

**Comment by gabrielVRcode** [comment]
Right, I have the same issue, I don't know if the problem was the last update in PS5.

**Comment by streetpea** [comment]
This likely has to do with the local network. If you can't see the ps5 on your local network can you try using a remote connection instead (see https://streetpea.github.io/chiaki4deck/setup/remoteconnection/)

**Comment by Billhixson** [comment]
I just did some testing in desktop mode. If I double click the ps5 that used to work and don't send a wakeup packet, it launches, but I get "unknown Ctrl error". If I connect again, it works, but only if I wait 15 seconds or so. It won't work on gaming mode at all though.

**Comment by streetpea** [comment]
It sounds like the discover request isn't going through. It's possible that port is being blocked by something ... does wake-up work?

**Comment by Billhixson** [comment]
Yup wake up works fine

**Comment by Billhixson** [comment]
Just an update - I unregistered the first ps5 and registered the new one and still get the same behavior. No indication the port is being blocked.
