### ISSUE TITLE
Duplicate button presses

### ISSUE THREAD

**Issue by TheRetroCarrot** [streetpea/chiaki4deck#8]
I've just got my Steam Deck yesterday and have mainly been playing around in Chiaki streaming the PS5, it works absolutely flawlessly for the most part however a slightly major issue I'm getting is what appears to be duplicate button presses.

Playing Ni No Kuni II I've noticed in menus as well as dialogues if I press the A button it sometimes will act like a double press. This is especially noticeable with the bumpers as pressing a bumper in the menu will cause it to cycle menus unusably fast rather than just performing a single press to the next menu.

Is there a fix for this either in Chiaki or Steam controls I haven't been able to find?

Thank you.

**Comment by streetpea** [comment]
Hi @TheRetroCarrot, 

I haven't personally experienced this issue. The controls have worked fine for me (I haven't noticed double input). Having said that, I have some questions for you that might give me insight into what's happening to see if I can help you either:

- fix the issue on your system 
OR (if necessary)
- make a fix in Chiaki to address the issue

1. Have you tried playing the game (Ni No Kuni II) on PS5 directly? If so, can you confirm the issue doesn't appear there? (if it occurs using the PS5 directly, then it's an issue with the game running on PS5, not a remote play issue. This is good to rule out first.)
2. Are you using the Chiaki flatpak or the `chiaki4deck` flatpak?
3. Which control scheme are you using on Steam Deck for the game? For example, are you using [this control scheme](https://streetpea.github.io/chiaki4deck/setup/controlling/#default-controller-profile)
4. Have you noticed this with other games or just Ni No Kuni II? If you haven't played any other games, can you try playing a different game and seeing if you have the same issue?

**Comment by TheRetroCarrot** [comment]
Thank you for the response:

1. It works perfect directly, one thing I haven't tried is pairing a dual sense controller to the Steam Deck though, I could test this.
2. This occurred with both flatpaks, I initially was using the base Chiaki, then removed it and went through the installation again when I learned of chiaki4deck.
3. I've tried that control scheme, as well as a couple other community profiles and my own profiles. I've also attempted every combination possible of input types Steam allows for face buttons and bumpers, and played around with delays however none of this seemed to help. Setting a face button to "toggle" technically removes the issue in menus so long as the menu doesn't allow for held button presses, but this isn't really a solution just an observation.
4. I have yet to actually try any other games, I'll do this and report my findings, it's a little hard to tell what inputs it will affect but I'm sure I can find something. It basically only affects actions that allow for held down button presses with repeatable actions, such as cycling through menus with shoulder buttons or skimming through dialogue with face buttons.

One other observation I've had is occasionally this issue simply goes away for a second, I'll be standing around go into a menu and it's perfect, then I move my character 2 feet and it's back. It makes me wonder if it's some sort of framerate/pacing latency issue that's occurring but I haven't been able to ever replicate it working correctly playing around with settings.

Thanks again!

**Comment by streetpea** [comment]
Thanks for the info. As far as trying it with another game, if you could replicate it in a game available via [PS Plus Extra games catalogue](https://www.playstation.com/en-us/ps-plus/games/) that would be ideal. (I want to try to replicate your issue on my device if possible but don't own Ni No Kuni II on PlayStation, but do have PS Plus Extra.)

**Comment by TheRetroCarrot** [comment]
I'll try it on Demons Souls and let you know. If I recall it has similar menu systems and I do own that one. Thanks!

**Comment by streetpea** [comment]
@TheRetroCarrot any update on this?

**Comment by Nikita01589** [comment]
found a solution to this problem? I have the same

**Comment by streetpea** [comment]
@Nikita01589 can you mention the game this is happening with? Like I mentioned above, as far as trying it with another game, if you could replicate it in a game available via [PS Plus Extra games catalogue](https://www.playstation.com/en-us/ps-plus/games/) that would be ideal. (I want to try to replicate your issue on my device if possible and have PS Plus Extra.) That way I can try to debug it more easily and rule out it being an issue with your specific installation / Steam Deck.

**Comment by streetpea** [comment]
closing stale issue as cannot repro and can't get any info from afflicted users
