### ISSUE TITLE
Could a arm64 version be built for Linux and MacOS?

### ISSUE THREAD

**Issue by lavavex** [streetpea/chiaki4deck#80]
Hi, I was wondering if you could get a version of this to build for arm64 MacOS and Linux as I have been unable to do so without errors. Thanks!

**Comment by streetpea** [comment]
Hmm ... have you tried the flathub build for arm linux? It says it builds an arm version there but I haven't tested it on Linux arm.

**Comment by streetpea** [comment]
Arm64 Linux release on flathub Mac release in GitHub release
