### ISSUE TITLE
Stretch/zoom options -- Chiaki Standalone

### ISSUE THREAD

**Issue by Bardok1984** [streetpea/chiaki4deck#82]
The new features for Chiaki4Deck (stretch or zoom the image) to get 16:10 aspect ratio fullscreen with no black bars , has become essential for Steam deck users.

However, for Windows users when are using 16:10 aspect ratio on their display (the New Legion Go Device has 16:10 screen) will need It as well.

Could Chiaki4Deck stretch functions be added to Chiaki "Standard" for Windows ??

Would there be any possibility to modify Chiaki4Deck to make It running on Windows ? (Modifying Gamepad function to Xbox controller for instance )

Thank you All so much for your invaluable attention

**Comment by streetpea** [comment]
I have good news on that front. It's already been added to upstream Chiaki and is part of release 2.2.
