### ISSUE TITLE
Improve picture quality

### ISSUE THREAD

**Issue by kLeR1k** [streetpea/chiaki4deck#83]
Any ways to improve picture quality of streaming? 
Those "gradients" transitions with noise (especially in right part of screenshot) looks disappointing. My PS5 default settings are 4k/60hz with HDR on (TV with OLED screen). Thought that HDR is the reason of those "gradients" on Steam Deck, but tried to set 1080p/60hz with HDR off on PS5 and nothing changed.
Chiaki4deck settings are 1080p/60hz with H265 codec and vaapi decode mode, tried different bitrates (up to 70 Mbps) and nothing changes too.
Same "gradients" transitions with noise are visible in some "foggy" games and them looks like splashes on the screen.
Or it is the way it is?
Anyway thanks for great app, it takes SD to new level.
![20230926185128_1](https://github.com/streetpea/chiaki4deck/assets/43771254/5bc76c27-69a4-4c85-868f-dc8b6a2b7418)

**Comment by streetpea** [comment]
The picture quality should be improved with update 1.5 with the libplacebo renderer on the high preset. You can also now stream in HDR if you have a Steam Deck OLED or are connected to an HDR monitor/TV.
