### ISSUE TITLE
Merge v2.2.0 update from ~thestr4ng3r/chiaki

### ISSUE THREAD

**Issue by Burner911** [streetpea/chiaki4deck#84]
I notice v2.2.0 was recently released on this branch:
https://git.sr.ht/~thestr4ng3r/chiaki/refs/v2.2.0

Curious how closely this branch is tracked and if recent changes can be incorporated.

**Comment by streetpea** [comment]
I have incorporated the relevant changes from 2.2.0 into chiaki4deck as of 1.3.4 (everything except some changes related to the release scripts that chiaki4deck doesn't use)

**Comment by Burner911** [comment]
Awesome! Thanks for the quick response.
