### ISSUE TITLE
v 1.4.0

### ISSUE THREAD

**Issue by chanksworld** [streetpea/chiaki4deck#85]
Newest version is still 1.3.4 on flathub and discover, also when trying to update via terminal - am I doing something wrong or does it have to be built from source?

**Comment by streetpea** [comment]
Flathub shows 1.4.0 for me .. https://flathub.org/apps/io.github.streetpea.Chiaki4deck and I'm able to update via my Steam Deck

**Comment by streetpea** [comment]
If you tried earlier maybe it wasn't released yet on Flathub (it takes about a day for releases to become available). Can you try again and make sure it's still not available as it shows as available for me when I check now.

**Comment by chanksworld** [comment]
It now worked thanks, I had tried yesterday and earlier today and my sources in discover still said 1.3.4, after downloading the 1.4.0 flatpack from Flathub. Thanks as well for bringing mic support - indispensable feature
