### ISSUE TITLE
How are you getting vaapi to work? Any way to get Vulcan to work?

### ISSUE THREAD

**Issue by futurepr0n** [streetpea/chiaki4deck#86]
Just curious how you manage to get vaapi to work in your build as the default chiaki does not work with the hardware decoding. Could you help get the Vulkan to work? When I set it, it will fail. Vaapi works perfect and is clean! Great work! This build is great, just wondered what differs as the regular one will not natively work with any of the hardware decoders.

**Comment by streetpea** [comment]
Vulkan-powered decoding will be added to ffmpeg 6.1 when that's released [see ffmpeg news item form May 31, 2023](https://www.ffmpeg.org) When it is, I'll update the build to use ffmpeg 6.1 and it should work for hw that supports it. 

As for vaapi, given the hw supports it, it should work. For the flatpak you need to enable the decoders in ffmpeg and use mesa with extra (I.e., version-extra) which has codecs enabled

**Comment by Geier97332** [comment]
Hi @streetpea,

what do you mean by enabling hardware decoding in ffmpeg und use mesa extra? Do we have to do that? There are no instructions in your wiki.

I never did that and i use vaapi without getting an error message.

**Comment by streetpea** [comment]
@Geier97332 when I say you I mean the builder/maintainer not the end user. Enabling hw decoding in ffmpeg is something that needs to be done for the build not by the end user. Using mesa with extra is done by default unless otherwise specified.

**Comment by futurepr0n** [comment]
What I mean is - when you install chiaki from flatpack in desktop mode, you will be unable to select the hw decoders, it will crash. And in steam deck big picture or regular mode it will also crash if trying to select those in options. But chiaki4deck will work in both modes for the HW decoders. It’s like it’s included or packaged in where as the other one requires additional dependencies. I think you explained it - I’ll try adding ffmpeg and mesa extras from flatpack or pacman see if it works

**Comment by streetpea** [comment]
@futurepr0n The chiaki flatpak and the chiaki4deck flatpak both work with vaapi for me on Steam Deck. You says it crashes when you select vaapi. Does it fail with "failed to initialize ffmpeg decoder" or something else?

**Comment by samiur** [comment]
Ffmpeg 6.1 is out now!

**Comment by streetpea** [comment]
Thanks, I'll switch to 6.1 for the next update.

**Comment by streetpea** [comment]
Update: I was able to switch to install ffmpeg 6.1 which enables vulkan support for graphics cards that support it. This will benefit users which have these cards. However, it appears the Steam Deck doesn't (at least not with the current drivers) as I get the following error when I try to use vulkan video decode on the Steam Deck:
```
[hevc @ 0x555a71d4ba80] Device does not support the VK_KHR_video_decode_queue extension!
[hevc @ 0x555a71d4ba80] Failed setup for format vulkan: hwaccel initialisation returned error.
```

**Comment by darrenhaken** [comment]
@streetpea do you still think you'll release an update with ffmpeg 6.1? Will it still have benefits over the previous version anyway?

**Comment by streetpea** [comment]
Yes I'll switch to ffmpeg 6.1 when I release the next update.

**Comment by darrenhaken** [comment]
Is it best to use Vaapi with a steam deck, then?

**Comment by streetpea** [comment]
You can use vaapi or Vulcan with Steam deck. I personally have found vaapi to perform better but ymmv

**Comment by darrenhaken** [comment]
@streetpea I didn't realise both worked. Even with hdr?

**Comment by streetpea** [comment]
Yes, both work

**Comment by darrenhaken** [comment]
Thanks @streetpea
