### ISSUE TITLE
Analogue Triggers for PS4 controllers jittering on MGS Master Collection

### ISSUE THREAD

**Issue by Mindofone** [streetpea/chiaki4deck#87]
Currently playing through the MGS legacy collection on my PS5 through chiaki4deck and noticed when I hold down the triggers to peek around the corner in MGS 2, it will jitter like crazy. In MGS3, it doesn’t even register as an input so I can’t access the left and right trigger menus during gameplay. I have tried both native input and steam input but it doesn’t change anything. I have also enabled and disabled DualSense options in the menus but it doesn’t seem to change anything.

**Comment by streetpea** [comment]
@Mindofone do you mean metal gear solid master collection volume 1 or MGS legacy collection? It looks like MGS legacy collection is PS3 only which is why I'm asking.

**Comment by Mindofone** [comment]
@streetpea Sorry I realized I jumbled the names in my post, but I definitely mean the MGS Master Collection volume 1. The triggers work fine on the PS5 itself with a dualsense but when I play with my steamdeck docked using a PS4 controller, the peaking around corners and standing on tip toes starts to jitter like crazy. And like I said before, MGS 3’s quick menus don’t work at all. It could be a problem with the master collection itself based on the amount of bugs I’ve found. However, this was the first game I’ve played on chiaki4deck that actually uses the analogue triggers at different increments so I have no reference on whether this feature is working correctly or not. I’ll try testing another controller with analogue triggers tomorrow.

**Comment by streetpea** [comment]
@Mindofone thanks for the clarification. I'll take a look.

**Comment by jbaiter** [comment]
When you say "jitter", do you mean that it rapidly switches between peeking and not peeking?
Can you try the official Remote Play application and check if this occurs in there as well?

**Comment by Mindofone** [comment]
@jbaiter Yes you have it right, Snake/Raiden will lean and unlean rapidly while holding down the trigger completely. Different pressures have the same result as well. This is consistent in everything I’ve tested aside from an official dualsense on the PS5. In MGS 3, the weapon menus will randomly appear and unappear. Depending on the controller/device used, they won’t activate at all. Unfortunately, I have some bad news. The official remote play app and the steamdeck in handheld mode are both doing it as well. (Steamdeck + Remote play randomly appear/unappear while PS4 controller on docked steamdeck doesn’t work at all.) The more I look into it, the more it seems like it’s on Konami’s side of the fence considering how many other glitches there are in the collection. It’s just weird the official remote play app has the problem as well when the dualsense doesn’t.

**Comment by streetpea** [comment]
@Mindofone do you get the same behavior with a Dualsense controller in Chiaki / the official ps remote play app?

**Comment by Mindofone** [comment]
@streetpea Yep it looks like the dualsense has the same problem when connected to my phone or steamdeck.

**Comment by streetpea** [comment]
@Mindofone unfortunately it sounds like an issue with remote play then and not specific to Chiaki4deck so I don't think it's something we can fix.
