### ISSUE TITLE
Invert buton pad option X, O, Δ, П 

### ISSUE THREAD

**Issue by masies-hack** [streetpea/chiaki4deck#89]
i use Ubuntu 22.04 on modded nitendo switch
so the pad butons are:
____X
__Y___A
____B

so PSx pads has same config like XBOX pads:
_____Y
__X____B
_____A
so when conect on PS4 console, the buttons are inverted
The place where the cross should be is the circle, and where the circle should be is the cross.
The same with the triangle and the square.

I use Moonlight on this same system and there is an option to reverse these buttons.
thank you so much.

**Comment by streetpea** [comment]
I can add the option to invert the buttons to Nintendo-style for non-Nintendo controllers / PS/XBOX style for Nintendo controllers.

**Comment by masies-hack** [comment]
Fantastic, I will be waiting for this option.
When it's ready, I will dedicate a video to you on my humble YouTube channel.
Thank you very much for the dedication.
