### ISSUE TITLE
DDNS not allowed in automation script for Chiachi-launcher.sh

### ISSUE THREAD

**Issue by SuttonX** [streetpea/chiaki4deck#91]
Title. When we get prompted for the second "away" IP, we can only enter a numerical IP and not a DDNS address. However the DDNS works fine in Chiaki4Deck when manually added.

I went back in to the Chiaki-launcher.sh with my text editor and manually changed my public IP there to my DDNS and it works fine.

Please allow DDNS input during the automated setup instead of restricting to numerical IP.

Also for the first IP prompt in that setup script, I recommend specifying that you want the local IP and there will be an opportunity to add the away IP later. I didn't know there would be a second IP input so I put my public IP initially to be safe for when I'm out of the house, so I had to close Konsole out and start over once I realized you were going to store both IPs for us.

**Comment by streetpea** [comment]
@SuttonX you already have the option to use a hostname for your away address. If you want to use a FQDN/DNS you select the hostname option to this prompt
```
AWAY ADDRESS
-------------
1) IP
2) hostname
NOTICE: Use 1 unless you created a hostname (FQDN) for your PlayStation
```
As for the opportunity to add an away address this is mentioned in a tip in step 3 of the documentation (https://streetpea.github.io/chiaki4deck/setup/automation/) but I could also mention it in the script itself.

**Comment by SuttonX** [comment]
Oh ok, thank you.  Not sure about most of the public but I didn't make the connection between hostname and DDNS.  To me hostname is the device name not a dedicated URL.  If you go in to the script to modify it for the away address mention, might be worth changing option 2 to read "hostname/DDNS" instead.

Anyway thanks for the great project, definitely improves the experience on the Deck!

**Comment by streetpea** [comment]
Thanks for the suggestions! I'll update the script with a note about the option for an external ip and add ddns to hostname / FQDN to clear up confusion.
