### ISSUE TITLE
[Feedback] Automation - /setup/automation/

### ISSUE THREAD

**Issue by Haagenati** [streetpea/chiaki4deck#94]
This guide is incredible, I'd just add a note to turn on show hidden files as .var is hidden by default on Steamdeck I believe. Thank you so much for putting this together! (If I just missed it, forgive me!)

**Comment by streetpea** [comment]
I thought show hidden files was on by default for me. I'll add a reminder to show hidden files if .var doesn't appear.

**Comment by streetpea** [comment]
Checking this on my deck it looks like the default changed from showing hidden files to not showing them in one of the deck updates. Thanks for pointing this out to me :)

**Comment by Haagenati** [comment]
Ahh that makes sense! I appreciate the followup and must say again, the
guide is wonderful! Thank you so much, documentation of this quality is too
rare!

**Comment by streetpea** [comment]
fixed with version 1.5.0
