### ISSUE TITLE
ERROR: "Failed to initialize Stream Session: Failed to initialize FFMPEG Decoder"

### ISSUE THREAD

**Issue by tvidal-net** [streetpea/chiaki4deck#97]
Hi, I am the author of a [gist](https://gist.github.com/tvidal-net/dda93291eb5898d43ae268e063c928be) to install chiaki4deck via PKGBUILD on the steamdeck. That approach has many problems and it breaks every time SteamOS gets an update. I am trying to use Chiaki 4 Deck without all that hassle, but it is not working for me.

I saw a recent suggestion by the author (unfortunately, I don't have the link), to use the AppImage and it is not working for me, with the following error:

> Failed to initialize Stream Session: Failed to initialize FFMPEG Decoder:
> [I] Using hardware decoder "vaapi"
> [E] Failed to create hwdevice context

The flatpak version only gives me a black screen when I try to connect. I wonder if this is because you build the AppImage from ubuntu instead of an Arch Linux or even a Steam OS image and the dependency versions are different.

Do you have a suggestion on how I could get a statically linked image of chiaki4deck so I wouldn't need any external dependency to make it work?

Thank you.
Regards.

**Comment by streetpea** [comment]
For the flatpak version, I'm not sure why you get a black screen as it works fine on my deck. It may be that it is just initially giving a black screen while failing the senkusha test and will work shortly thereafter. In desktop mode you can run the flatpak from the konsole to see the logs directly like:
```
flatpak run io.github.streetpea.Chiaki4deck
```
or you can check the logs directory for the flatpak (`~/.var/app/io.github.streetpea.Chiaki4deck/data/Chiaki/Chiaki/log/` for the logs). 

As for the appimage, I believe vaapi won't work with an appimage unless it is created on hardware/os which has similar hwcontext so you have to set the hw decode method to none for it to work or build it on Steam Deck and then it will work for Steam Deck but not other devices. The regular Chiaki appimage has the same limitations. See this link: https://www.cinelerra-gg.org/bugtracker/view.php?id=604 for an explanation.

**Comment by tvidal-net** [comment]
So, I managed to sort the black screen, it's because I left my PS5 running YouTube which for some reason, cannot be streamed. Apologies for that.

I had a few crashes and started digging a little bit and noticed a few things:

The worst possible scenario was:
- PS5 configured for 4K + HDR
- bluetooth headset
- default chiaki4deck settings

With the following changes, the experience improved A LOT:
- PS5 configured for 720p without HDR
- wired headset
- 30000 video bitrate & 7200 audio buffer size

both with chiaki4deck @ 720p60hz

I was able to play for a few hours without any crash, the major issue being a green image that last for a few seconds every few minutes. The custom build chiaki4deck did not have this issue.

I have a theory that people who do not use 4K+HDR on the PS have way less problems with streaming, which is why it works so well for a group of people and others have problems. __Maybe__ when there is a bad key frame or dropped network package, there was something in the old versions that would cause chiaki4deck to crash and now just shows the green image (I don't know, just guessing here), in any case, it feels like running the most recent version of the dependencies (from Arch Linux repository) instead of the ones from ubuntu bionic that chiaki4deck is built with, improves the overall resilience.

I'll try to build a custom flatpak directly from the SteamOS image itself and see if that fixes these green screen image glitches and will give you feedback. If that works, maybe I could contribute with new build scripts that use SteamOS instead of bionic.

Thank you for taking the time to read.
Regards.

**Comment by tvidal-net** [comment]
Well, I managed to get a somewhat statically linked exec, requiring only a single external lib `libfftw3.so.3`, by using SteamOS 3.5 image on a VM and calling `cmake` with `-DBUILD_SHARED_LIBS=OFF`.

Copied this lib along the `chiaki` exec to my steamdeck and was able to run it from the home dir, without needing to disable `steamos-readonly`, which is what I wanted.  I'll test it tonight and over the next few days for stability, but initial test shows no green image glitches and other issues I had with the flatpak.

I can help you use a steam os image instead of `ubuntu:bionic` to build chiaki4deck if you are interested, otherwise, I'll just keep recommending people that have the same issues I had, to use the custom built exe.

**Comment by streetpea** [comment]
So the appimage is using ubuntu bionic for maximum compatibility.. I could create an appimage with a different os for steam deck users if that has better results ... the flatpak uses the kde runtime with the dependencies for that runtime. Currently it uses 22.08 of the freedesktop runtime as its container os. https://invent.kde.org/packaging/flatpak-kde-runtime

**Comment by tvidal-net** [comment]
I can definitely confirm that everything else being equal, the native build glitches and performs way better than the flatpak build. 

I have been using the [statically linked executable built on the steam deck image vm](/github.com/tvidal-net/chiaki4deck-build/blob/main/chiaki4deck-static.sh) and the glitches are pretty much gone, but I'm afraid I cannot explain or even understand why.

I'll leave a [tarball](//github.com/tvidal-net/chiaki4deck-build/releases/tag/v1.0) with the static executable and the single lib it depends on my github repo in case anyone else could benefit from it, but from my side, my problem is resolved and I thank you for taking the time to answer and explain everything.

Best regards.

**Comment by streetpea** [comment]
@tvidal-net Unfortunately, so I can't tell what's causing the difference other than it running natively at this point I'm not sure how (if) I can change the flatpak to replicate the results you're getting locally. Having said that, I will definitely point people to your static build if they have issues. Thanks for your work building that out :)
