### ISSUE TITLE
Stream setting profiles for each playstation connection

### ISSUE THREAD

**Issue by sharzy720** [streetpea/chiaki4deck#99]
I have 2 connections when playing on my Steam Deck, one for when I am on the same network as my PS5 and one for when I am away from the house. I have to go into the settings and change the stream settings when I change the connection. Is it possible to make it so that each connection has its own stream setting 'profile' that way when switching between connections I don't have to change each setting manually.

**Comment by jbaiter** [comment]
I have a script for that which symlinks an environment specific config file depending on the current ESSID of the WiFi. Could probably add something like that to the launch script.
